const fs = require("fs");
let c = fs.readFileSync("src/app/data/formulas.ts", "utf8");

// Helper: safe replace
function replace(oldStr, newStr, label) {
    if (c.includes(oldStr)) {
        c = c.replace(oldStr, newStr);
        console.log("OK: " + label);
        return true;
    }
    console.log("NOT FOUND: " + label);
    return false;
}

// 1. crontab - add warnings + more presets
const oldCron = `    'crontab-generator': {
    inputs: [{key:'min',label:'Minute',type:'text',defaultValue:'0'},{key:'hr',label:'Hour',type:'text',defaultValue:'2'},{key:'dom',label:'Day of Month',type:'text',defaultValue:'*'},{key:'mon',label:'Month',type:'text',defaultValue:'*'},{key:'dow',label:'Day of Week',type:'text',defaultValue:'*'}],
    formula: (v) => { var c=v.min+' '+v.hr+' '+v.dom+' '+v.mon+' '+v.dow; var d=''; if(v.min==='0'&&v.hr==='2'&&v.dom==='*'&&v.mon==='*'&&v.dow==='*')d='Daily at 2:00 AM'; else if(v.min==='*/5'&&v.hr==='*')d='Every 5 minutes'; else if(v.min==='0'&&v.hr==='0'&&v.dom==='1')d='Midnight on 1st of month'; else if(v.min==='*/15'&&v.hr==='*')d='Every 15 minutes'; else if(v.min==='0'&&v.hr==='*')d='Every hour'; else d='Custom schedule'; var parts=c.split(/\\s+/); var min=parts[0],hr=parts[1],dom=parts[2],mon=parts[3],dow=parts[4]; var next=[]; var now=new Date(); now.setSeconds(0,0); now.setMinutes(now.getMinutes()+1); var limit=0; while(next.length<5&&limit<525600){limit++; var y=now.getFullYear(),mo=now.getMonth(),day=now.getDate(),h=now.getHours(),m=now.getMinutes(); if(mon!=='*'){var mNum=parseInt(mon); if(isNaN(mNum)||(mo+1)!==mNum){now.setMinutes(now.getMinutes()+1);continue;}} if(dom!=='*'){var dNum=parseInt(dom); if(isNaN(dNum)||day!==dNum){now.setDate(now.getDate()+1);now.setHours(0,0,0,0);continue;}} if(dow!=='*'){var dowNum=parseInt(dow); if(isNaN(dowNum)||now.getDay()!==dowNum){now.setDate(now.getDate()+1);now.setHours(0,0,0,0);continue;}} if(hr!=='*'){var hNum=parseInt(hr); if(!isNaN(hNum)&&h!==hNum){now.setMinutes(0);now.setHours(now.getHours()+1);continue;}} if(min!=='*'){ if(min.indexOf('*/')===0){var interval=parseInt(min.slice(2)); if(m%interval!==0){now.setMinutes(Math.ceil(m/interval)*interval);continue;}} else{var minNum=parseInt(min); if(!isNaN(minNum)&&m!==minNum){now.setMinutes(minNum);continue;}}} var ts=now.toLocaleString('en-US',{timeZoneName:'short'}); next.push(ts); now.setMinutes(now.getMinutes()+1);} return [{label:'Cron Expression',value:c},{label:'Meaning',value:d},{label:'Next 5 Executions',value:next.length>0?next.join('\\n'):'Could not compute',insight:'Times shown in your local timezone. For production, always test cron expressions with crontab -l or online validators.'}]; },
    presets: [{label:'Daily 2AM',values:{min:'0',hr:'2',dom:'*',mon:'*',dow:'*'}},{label:'Every 5min',values:{min:'*/5',hr:'*',dom:'*',mon:'*',dow:'*'}},{label:'Every Hour',values:{min:'0',hr:'*',dom:'*',mon:'*',dow:'*'}},{label:'Mon-Fri 9AM',values:{min:'0',hr:'9',dom:'*',mon:'*',dow:'1-5'}},{label:'Midnight 1st',values:{min:'0',hr:'0',dom:'1',mon:'*',dow:'*'}}],
  },`;

const newCron = `    'crontab-generator': {
    inputs: [{key:'min',label:'Minute',type:'text',defaultValue:'0'},{key:'hr',label:'Hour',type:'text',defaultValue:'2'},{key:'dom',label:'Day of Month',type:'text',defaultValue:'*'},{key:'mon',label:'Month',type:'text',defaultValue:'*'},{key:'dow',label:'Day of Week',type:'text',defaultValue:'*'}],
    formula: (v) => { var c=v.min+' '+v.hr+' '+v.dom+' '+v.mon+' '+v.dow; var d=''; if(v.min==='0'&&v.hr==='2'&&v.dom==='*'&&v.mon==='*'&&v.dow==='*')d='Daily at 2:00 AM'; else if(v.min==='*/5'&&v.hr==='*')d='Every 5 minutes'; else if(v.min==='0'&&v.hr==='0'&&v.dom==='1')d='Midnight on 1st of month'; else if(v.min==='*/15'&&v.hr==='*')d='Every 15 minutes'; else if(v.min==='0'&&v.hr==='*')d='Every hour'; else d='Custom schedule'; var warns=[]; if((v.dom!=='*'||v.mon!=='*')&&v.dow!=='*')warns.push('Day-of-month AND day-of-week both set - cron runs when EITHER matches (may be unintended).'); if(v.mon.indexOf('*/')>=0&&v.mon!=='*'&&v.dom!=='*')warns.push('Step value combined with specific dates may produce unexpected results.'); var parts=c.split(/\\s+/); var min=parts[0],hr=parts[1],dom=parts[2],mon=parts[3],dow=parts[4]; var next=[]; var now=new Date(); now.setSeconds(0,0); now.setMinutes(now.getMinutes()+1); var limit=0; while(next.length<5&&limit<525600){limit++; var y=now.getFullYear(),mo=now.getMonth(),day=now.getDate(),h=now.getHours(),m=now.getMinutes(); if(mon!=='*'){var mNum=parseInt(mon); if(isNaN(mNum)||(mo+1)!==mNum){now.setMinutes(now.getMinutes()+1);continue;}} if(dom!=='*'){var dNum=parseInt(dom); if(isNaN(dNum)||day!==dNum){now.setDate(now.getDate()+1);now.setHours(0,0,0,0);continue;}} if(dow!=='*'){var dowNum=parseInt(dow); if(isNaN(dowNum)||now.getDay()!==dowNum){now.setDate(now.getDate()+1);now.setHours(0,0,0,0);continue;}} if(hr!=='*'){var hNum=parseInt(hr); if(!isNaN(hNum)&&h!==hNum){now.setMinutes(0);now.setHours(now.getHours()+1);continue;}} if(min!=='*'){ if(min.indexOf('*/')===0){var interval=parseInt(min.slice(2)); if(m%interval!==0){now.setMinutes(Math.ceil(m/interval)*interval);continue;}} else{var minNum=parseInt(min); if(!isNaN(minNum)&&m!==minNum){now.setMinutes(minNum);continue;}}} var ts=now.toLocaleString('en-US',{timeZoneName:'short'}); next.push(ts); now.setMinutes(now.getMinutes()+1);} return [{label:'Cron Expression',value:c},{label:'Meaning',value:d},{label:'Next 5 Executions',value:next.length>0?next.join('\\n'):'Could not compute',insight:'Times in your local timezone. Test with crontab -l before deploying.'},{label:warns.length?'Warnings':'Valid',value:warns.join('; ')||'No conflicts detected'}]; },
    presets: [{label:'Every Minute (* * * * *)',values:{min:'*',hr:'*',dom:'*',mon:'*',dow:'*'}},{label:'Daily 2AM (0 2 * * *)',values:{min:'0',hr:'2',dom:'*',mon:'*',dow:'*'}},{label:'Every 5min (*/5 * * * *)',values:{min:'*/5',hr:'*',dom:'*',mon:'*',dow:'*'}},{label:'Every 15min (*/15 * * * *)',values:{min:'*/15',hr:'*',dom:'*',mon:'*',dow:'*'}},{label:'Every Hour (0 * * * *)',values:{min:'0',hr:'*',dom:'*',mon:'*',dow:'*'}},{label:'Mon-Fri 9AM (0 9 * * 1-5)',values:{min:'0',hr:'9',dom:'*',mon:'*',dow:'1-5'}},{label:'Midnight 1st (0 0 1 * *)',values:{min:'0',hr:'0',dom:'1',mon:'*',dow:'*'}},{label:'Every 3mo (0 0 1 */3 *)',values:{min:'0',hr:'0',dom:'1',mon:'*/3',dow:'*'}}],
  },`;

// 2. annuity - add inflation
const oldAnn = `    'annuity-calculator': {
    inputs: [{key:'pmt',label:'Payment ($)',type:'number',defaultValue:1000},{key:'rate',label:'Rate (%)',type:'number',defaultValue:6},{key:'n',label:'Periods (yr)',type:'number',defaultValue:20},{key:'timing',label:'Payment Timing',type:'select',options:[{label:'End of Period (Ordinary)',value:'end'},{label:'Beginning of Period (Due)',value:'begin'}],defaultValue:'end'}],
    formula: (v) => { var pmt=F(v.pmt),r=F(v.rate)/100,n=F(v.n); var fv=r>0?pmt*((Math.pow(1+r,n)-1)/r):pmt*n; if(v.timing==='begin')fv=fv*(1+r); var inv=pmt*n; return [{label:'Future Value ('+(v.timing==='begin'?'Annuity Due':'Ordinary Annuity')+')',value:'$'+fv.toFixed(2),emphasis:true,insight:v.timing==='begin'?'Annuity Due: payments at start of each period. Grows more because each payment earns an extra period of interest.':v.timing==='end'?'Ordinary Annuity: payments at end of each period. Standard for most loan/lease calculations.':''},{label:'Total Invested',value:'$'+inv.toFixed(0)},{label:'Interest Earned',value:'$'+(fv-inv).toFixed(0)},{label:'Present Value',value:'$'+(fv/Math.pow(1+r,n)).toFixed(2),insight:'What this future stream is worth today. Useful for valuing bonds, leases, or retirement income.'}]; },
  },`;

const newAnn = `    'annuity-calculator': {
    inputs: [{key:'pmt',label:'Payment ($)',type:'number',defaultValue:1000},{key:'rate',label:'Rate (%)',type:'number',defaultValue:6},{key:'n',label:'Periods (yr)',type:'number',defaultValue:20},{key:'timing',label:'Payment Timing',type:'select',options:[{label:'End of Period (Ordinary)',value:'end'},{label:'Beginning of Period (Due)',value:'begin'}],defaultValue:'end'},{key:'infl',label:'Inflation Rate (%)',type:'number',defaultValue:2.5}],
    formula: (v) => { var pmt=F(v.pmt),r=F(v.rate)/100,n=F(v.n),infl=F(v.infl)/100; var fv=r>0?pmt*((Math.pow(1+r,n)-1)/r):pmt*n; if(v.timing==='begin')fv=fv*(1+r); var inv=pmt*n; var realRate=(1+r)/(1+infl)-1; var realFV=r>0?pmt*((Math.pow(1+realRate,n)-1)/realRate):pmt*n; if(v.timing==='begin')realFV=realFV*(1+realRate); var pv=fv/Math.pow(1+r,n); return [{label:'Future Value (Nominal '+F(v.rate).toFixed(0)+'%)',value:'$'+fv.toFixed(2),emphasis:true},{label:'Inflation-Adjusted ('+F(v.infl).toFixed(1)+'% infl)',value:'$'+realFV.toFixed(2),insight:'In '+F(v.n).toFixed(0)+' years, $'+fv.toFixed(2)+' will buy what $'+realFV.toFixed(2)+' buys today. Real return rate: '+(realRate*100).toFixed(2)+'%.'},{label:'Total Invested',value:'$'+inv.toFixed(0)},{label:'Interest Earned (nominal)',value:'$'+(fv-inv).toFixed(0)},{label:'Present Value',value:'$'+pv.toFixed(2),insight:'Lump sum needed today to equal this annuity stream.'}]; },
  },`;

// 3. tariff - FOB/CIF + VAT
const oldTariff = `    'tariff-impact-calculator': {
    inputs: [{key:'fob',label:'FOB/Unit ($)',type:'number',defaultValue:100},{key:'old',label:'Old Tariff (%)',type:'number',defaultValue:10},{key:'new',label:'New Tariff (%)',type:'number',defaultValue:25},{key:'units',label:'Units',type:'number',defaultValue:1000}],
    formula: (v) => { const o=F(v.fob)*F(v.old)/100*F(v.units),n=F(v.fob)*F(v.new)/100*F(v.units); return [{label:'Old Duty',value:'$'+o.toFixed(0)},{label:'New Duty',value:'$'+n.toFixed(0)},{label:'Increase',value:'$'+(n-o).toFixed(0)}]; },
  },`;

const newTariff = `    'tariff-impact-calculator': {
    inputs: [{key:'basis',label:'Price Basis',type:'select',options:[{label:'FOB (Free On Board)',value:'fob'},{label:'CIF (Cost+Insurance+Freight)',value:'cif'}],defaultValue:'fob'},{key:'price',label:'Unit Price ($)',type:'number',defaultValue:100},{key:'freight',label:'Freight/Unit ($)',type:'number',defaultValue:5},{key:'ins',label:'Insurance/Unit ($)',type:'number',defaultValue:1},{key:'old',label:'Old Tariff (%)',type:'number',defaultValue:10},{key:'new',label:'New Tariff (%)',type:'number',defaultValue:25},{key:'vat',label:'VAT/GST Rate (%)',type:'number',defaultValue:0},{key:'units',label:'Quantity',type:'number',defaultValue:1000}],
    formula: (v) => { var price=F(v.price),fr=F(v.freight),ins=F(v.ins),cif=price+fr+ins; var dutiable=v.basis==='cif'?cif:price; var oldTar=dutiable*F(v.old)/100,newTar=dutiable*F(v.new)/100; var oldVat=(dutiable+oldTar)*F(v.vat)/100,newVat=(dutiable+newTar)*F(v.vat)/100; var oldTotal=(dutiable+oldTar+oldVat)*F(v.units); var newTotal=(dutiable+newTar+newVat)*F(v.units); return [{label:'Dutiable Value ('+v.basis.toUpperCase()+')',value:'$'+dutiable.toFixed(2)+'/unit',insight:'CIF = FOB + Freight + Insurance. Most countries assess tariffs on CIF value.'},{label:'Old Total (Duty '+F(v.old).toFixed(0)+'%)',value:'$'+oldTotal.toLocaleString(),insight:F(v.vat)>0?'Includes '+F(v.vat).toFixed(0)+'% VAT on (price+duty).':'Add VAT rate to see full landed cost impact.'},{label:'New Total (Duty '+F(v.new).toFixed(0)+'%)',value:'$'+newTotal.toLocaleString(),emphasis:true,insight:F(v.vat)>0?'VAT is applied ON TOP of duty (compounding effect). Standard in EU/UK/most countries.':'VAT compounds on top of duty in most jurisdictions.'},{label:'Cost Increase',value:'$'+(newTotal-oldTotal).toLocaleString()+' ('+((newTotal/oldTotal-1)*100).toFixed(1)+'%)'}]; },
  },`;

// 4. tire-size - fix formula bug + old/new comparison
const oldTire = `    'tire-size-calculator': {
    inputs: [{key:'width',label:'Width (mm)',type:'number',defaultValue:225},{key:'aspect',label:'Aspect',type:'number',defaultValue:65},{key:'rim',label:'Rim (in)',type:'number',defaultValue:17}],
    formula: (v) => { var w=F(v.width)||225,ar=F(v.ratio)||55,d=F(v.dia)||17; var sh=(w*ar/100)/25.4,od=sh*2+d,circ=od*Math.PI,rpm=63360/circ; return [{label:"Diameter",value:od.toFixed(1)+" in",insight:"Stay within 3% of OEM diameter to avoid ABS/TC issues. Larger tires = speedometer reads low."},{label:"Sidewall",value:sh.toFixed(1)+" in"},{label:"Rev/Mile",value:Math.round(rpm)+" revs"}] },
  },`;

const newTire = `    'tire-size-calculator': {
    inputs: [{key:'w1',label:'Old Width (mm)',type:'number',defaultValue:225},{key:'ar1',label:'Old Aspect Ratio',type:'number',defaultValue:65},{key:'r1',label:'Old Rim (in)',type:'number',defaultValue:17},{key:'w2',label:'New Width (mm)',type:'number',defaultValue:245},{key:'ar2',label:'New Aspect Ratio',type:'number',defaultValue:45},{key:'r2',label:'New Rim (in)',type:'number',defaultValue:18}],
    formula: (v) => { var w1=F(v.w1),ar1=F(v.ar1),r1=F(v.r1); var w2=F(v.w2),ar2=F(v.ar2),r2=F(v.r2); var sh1=w1*ar1/100/25.4,od1=sh1*2+r1; var sh2=w2*ar2/100/25.4,od2=sh2*2+r2; var diaDiff=(od2-od1)/od1*100; var s60=60*od2/od1; var safe=Math.abs(diaDiff)<=3; return [{label:"Old Tire",value:w1.toFixed(0)+"/"+ar1.toFixed(0)+"R"+r1.toFixed(0)+" - "+od1.toFixed(2)+"in dia"},{label:"New Tire",value:w2.toFixed(0)+"/"+ar2.toFixed(0)+"R"+r2.toFixed(0)+" - "+od2.toFixed(2)+"in dia"},{label:"Diameter Change",value:(diaDiff>=0?"+":"")+diaDiff.toFixed(1)+"%",insight:safe?"Safe within 3% - ABS and gearing unaffected.":diaDiff>3?"TOO LARGE - speedo reads LOW, ABS may malfunction.":"TOO SMALL - speedo reads HIGH, less ground clearance."},{label:"Speedo at 60mph indicated",value:"Actual: "+s60.toFixed(1)+" mph",insight:od2>od1?"Speedo shows 60 but going FASTER - ticket risk!":"Speedo shows 60 but going SLOWER."},{label:"Mobile CSS Tip",value:"Use appearance:none on number inputs to hide spinners on narrow mobile screens."}]; },
  },`;

// 5. beam-load - disclaimer
const oldBeam = `    'beam-load-calculator': {
    inputs: [{key:'span',label:'Span (ft)',type:'number',defaultValue:12},{key:'load',label:'Load (lbs/ft)',type:'number',defaultValue:40},{key:'mat',label:'Material',type:'select',options:[{label:'Wood SPF #2',value:'1000'},{label:'LVL (Laminated Veneer)',value:'2800'},{label:'Steel A36',value:'24000'},{label:'Douglas Fir #1',value:'1400'},{label:'Glulam',value:'2100'}],defaultValue:'1000'},{key:'support',label:'Support Type',type:'select',options:[{label:'Simply Supported',value:'simple'},{label:'Fixed Both Ends',value:'fixed'},{label:'Cantilever',value:'cant'}],defaultValue:'simple'}],
    formula: (v) => { var L=F(v.span),w=F(v.load),M,divider; if(v.support==='fixed'){M=w*L*L/12;divider='M=wL²/12';} else if(v.support==='cant'){M=w*L*L/2;divider='M=wL²/2';} else {M=w*L*L/8;divider='M=wL²/8';} var Fb=parseFloat(String(v.mat)),S=M*12/Fb; var sections=[{name:'2×6',S:7.56},{name:'2×8',S:13.14},{name:'2×10',S:21.39},{name:'2×12',S:31.64},{name:'4×10',S:42.78},{name:'4×12',S:63.28}]; var ok=sections.filter(function(s){return s.S>=S;}); return [{label:'Max Moment ('+divider+')',value:M.toFixed(0)+' ft-lb'},{label:'Required Section Modulus (S)',value:S.toFixed(2)+' in³'},{label:'Suitable Sections',value:ok.length>0?ok.map(function(s){return s.name;}).join(', '):'No standard section works — reduce span or increase beam size'},{label:'Deflection Check',value:'Δ ≤ L/360 = '+((L*12)/360).toFixed(2)+'" max for live load. For dead+live: L/240 = '+((L*12)/240).toFixed(2)+'".'}]; },
  },`;

const newBeam = `    'beam-load-calculator': {
    inputs: [{key:'span',label:'Span (ft)',type:'number',defaultValue:12},{key:'load',label:'Load (lbs/ft)',type:'number',defaultValue:40},{key:'mat',label:'Material',type:'select',options:[{label:'Wood SPF #2 (Fb=1000)',value:'1000'},{label:'LVL (Fb=2800)',value:'2800'},{label:'Steel A36 (Fb=24000)',value:'24000'},{label:'Douglas Fir #1 (Fb=1400)',value:'1400'},{label:'Glulam (Fb=2100)',value:'2100'}],defaultValue:'1000'},{key:'support',label:'Support Type',type:'select',options:[{label:'Simply Supported',value:'simple'},{label:'Fixed Both Ends',value:'fixed'},{label:'Cantilever',value:'cant'}],defaultValue:'simple'}],
    formula: (v) => { var L=F(v.span),w=F(v.load),Fb=parseFloat(String(v.mat)); if(L<=0||w<=0)return[{label:'Error',value:'Span and load must be positive values.'}]; var extreme=''; if(L>50||w>1000)extreme='Extreme values - verify with a licensed structural engineer. Building codes mandate safety factors (~1.5x for live loads).'; var M,divider; if(v.support==='fixed'){M=w*L*L/12;divider='M=wL^2/12';} else if(v.support==='cant'){M=w*L*L/2;divider='M=wL^2/2';} else {M=w*L*L/8;divider='M=wL^2/8';} var S=M*12/Fb; var sections=[{name:'2x6',S:7.56},{name:'2x8',S:13.14},{name:'2x10',S:21.39},{name:'2x12',S:31.64},{name:'4x10',S:42.78},{name:'4x12',S:63.28}]; var ok=sections.filter(function(s){return s.S>=S;}); return [{label:'Max Moment ('+divider+')',value:M.toFixed(0)+' ft-lb'},{label:'Required Section Modulus (S)',value:S.toFixed(2)+' in3'},{label:'Suitable Beams',value:ok.length>0?ok.map(function(s){return s.name;}).join(', '):'None - reduce span or use steel'},{label:'Deflection',value:'L/360 = '+((L*12)/360).toFixed(2)+'in (live) | L/240 = '+((L*12)/240).toFixed(2)+'in (total)'},{label:'DISCLAIMER',value:'ESTIMATE ONLY. Not a substitute for professional structural engineering. Consult a licensed engineer for actual construction. '+extreme}]; },
  },`;

// 6. currency-hedge - forward points
const oldHedge = `    'currency-hedge-calculator': {
    inputs: [{key:'amt',label:'Amount (foreign currency)',type:'number',defaultValue:100000},{key:'cur',label:'Spot Rate (current)',type:'number',defaultValue:1.10,step:0.01},{key:'fwd',label:'Forward Rate (12mo)',type:'number',defaultValue:1.08,step:0.01},{key:'type',label:'Hedge Type',type:'select',options:[{label:'Forward Contract',value:'fwd'},{label:'No Hedge (Spot)',value:'spot'}],defaultValue:'fwd'}],
    formula: (v) => { var amt=F(v.amt),spot=F(v.cur),fwd=F(v.fwd),hedged=amt*fwd,unhedged=amt*spot; var diff=hedged-unhedged; var advice=diff>0?'Forward rate is worse than spot — you lock in a $'+Math.abs(diff).toFixed(0)+' loss. Consider waiting or partial hedge.':diff<0?'Forward rate is better than spot — you save $'+Math.abs(diff).toFixed(0)+' by hedging. Lock it in!':'No difference between hedging and spot.'; return [{label:'Hedged (Forward)',value:'$'+hedged.toFixed(0),insight:'Locked-in rate. Zero uncertainty. Common for importers/exporters. Forward points = '+(fwd-spot).toFixed(4)+' ('+((fwd/spot-1)*100).toFixed(2)+'% premium/discount).'},{label:'Unhedged (Spot)',value:'$'+unhedged.toFixed(0),insight:'Exposed to currency fluctuation. If rate moves 10% against you: potential loss of $'+(amt*spot*0.1).toFixed(0)+'.'},{label:'Hedge Analysis',value:advice},{label:'Risk Note',value:'This is a simplification. Forward contracts have minimums ($1M+ typically). Retail users can use currency futures or options. Consult a treasury professional for large exposures.'}]; },
  },`;

const newHedge = `    'currency-hedge-calculator': {
    inputs: [{key:'amt',label:'Amount (foreign currency)',type:'number',defaultValue:100000},{key:'cur',label:'Spot Rate',type:'number',defaultValue:1.10,step:0.0001},{key:'fwdPts',label:'Forward Points (from bank quote)',type:'number',defaultValue:-200,step:1,unit:'pts',hint:'+200 = premium, -200 = discount. Get live points from your FX broker.'}],
    formula: (v) => { var amt=F(v.amt),spot=F(v.cur),fwdPts=F(v.fwdPts),fwd=spot+fwdPts/10000; var hedged=amt*fwd,unhedged=amt*spot; var diff=hedged-unhedged,costPct=Math.abs(fwdPts/10000)/spot*100; var advice=diff>0?'Forward rate worse by $'+Math.abs(diff).toFixed(0)+' (cost: '+costPct.toFixed(3)+'%). Weigh against FX risk.':diff<0?'Forward rate BETTER - save $'+Math.abs(diff).toFixed(0)+'. Lock it in!':'No difference.'; return [{label:'Spot Rate',value:spot.toFixed(4)},{label:'Forward Rate ('+(fwdPts>0?'+':'')+fwdPts.toFixed(0)+' pts)',value:fwd.toFixed(4),insight:'Forward points = interest rate differential between currencies. Banks quote these live. Positive = premium, negative = discount.'},{label:'Hedged Value',value:'$'+hedged.toFixed(2),insight:'Locked-in. Hedging cost: '+costPct.toFixed(3)+'%. Guaranteed rate regardless of market.'},{label:'Unhedged (at spot)',value:'$'+unhedged.toFixed(2),insight:'Exposed to FX risk. 5% adverse move loses ~$'+(amt*spot*0.05).toFixed(0)+'.'},{label:'IMPORTANT',value:'Uses manual forward point input. FX rates change by the second. For real hedging, obtain live quotes from your bank or FX broker (Interactive Brokers, Wise Business). Forward contracts typically require $100K+ notional.'}]; },
  },`;

// 7. ovulation - irregular cycle + disclaimer
const oldOv = `    'ovulation-calculator': {
    inputs: [{key:'lmp',label:'Last Period',type:'text',defaultValue:'2026-06-01'},{key:'cycle',label:'Cycle (days)',type:'number',defaultValue:28}],
    formula: (v) => { const l=new Date(String(v.lmp)); if(isNaN(l.getTime()))return[{label:'Error',value:'Invalid date'}]; const c=F(v.cycle); const o=new Date(l);o.setDate(o.getDate()+c-14);const f=new Date(o);f.setDate(f.getDate()-5);const e=new Date(o);e.setDate(e.getDate()+2); const earlyOv=new Date(l);earlyOv.setDate(earlyOv.getDate()+21); const lateOv=new Date(l);lateOv.setDate(lateOv.getDate()+35); return[{label:'Predicted Ovulation',value:o.toISOString().slice(0,10),insight:'Based on '+c.toFixed(0)+'-day cycle. Actual ovulation varies +/-2 days. For irregular cycles (21-35 days), ovulation window may span '+earlyOv.toISOString().slice(0,10)+' to '+lateOv.toISOString().slice(0,10)+'.'},{label:'Fertile Window',value:f.toISOString().slice(0,10)+' to '+e.toISOString().slice(0,10),insight:'Sperm survive 5 days; egg survives 24h. Highest conception probability: 2 days before ovulation.'}]; },
  },`;

const newOv = `    'ovulation-calculator': {
    inputs: [{key:'lmp',label:'Last Period (YYYY-MM-DD)',type:'text',defaultValue:'2026-06-01'},{key:'cycle',label:'Typical Cycle (days)',type:'number',defaultValue:28}],
    formula: (v) => { var l=new Date(String(v.lmp)); if(isNaN(l.getTime()))return[{label:'Error',value:'Invalid date. Use YYYY-MM-DD format.'}]; var c=F(v.cycle); var irregular=c<21||c>45; var warn=irregular?'YOUR CYCLE ('+c.toFixed(0)+' days) IS OUTSIDE 21-45 DAY RANGE. This estimate may be INACCURATE. This tool assumes a regular luteal phase. For irregular cycles, use ovulation test kits (OPKs) or consult a fertility specialist.':''; var o=new Date(l);o.setDate(o.getDate()+c-14);var f=new Date(o);f.setDate(f.getDate()-5);var e=new Date(o);e.setDate(e.getDate()+1); return[{label:'Predicted Ovulation ('+c.toFixed(0)+'-day cycle)',value:o.toISOString().slice(0,10),insight:irregular?'UNRELIABLE for irregular cycles. See warning.':'Based on '+c.toFixed(0)+'-day cycle. May vary by 2 days. Confirm with BBT or OPK.'},{label:'Fertile Window',value:f.toISOString().slice(0,10)+' to '+e.toISOString().slice(0,10),insight:'Sperm survive 5 days. Egg survives 12-24h. Best chance: 2 days before ovulation.'},{label:irregular?'IRREGULAR CYCLE WARNING':'Medical Disclaimer',value:warn||'For informational purposes only. NOT a substitute for professional medical advice. Consult your healthcare provider for fertility planning.'}]; },
  },`;

replace(oldCron, newCron, "crontab-generator");
replace(oldAnn, newAnn, "annuity-calculator");
replace(oldTariff, newTariff, "tariff-impact-calculator");
replace(oldTire, newTire, "tire-size-calculator");
replace(oldBeam, newBeam, "beam-load-calculator");
replace(oldHedge, newHedge, "currency-hedge-calculator");
replace(oldOv, newOv, "ovulation-calculator");

fs.writeFileSync("src/app/data/formulas.ts", c, "utf8");
console.log("\nDone! Applied changes.");
