with open("src/app/data/formulas.ts", "r", encoding="utf-8") as f:
    content = f.read()

F = {}
F['ba-zi-calculator'] = "  'ba-zi-calculator': {\n    inputs: [{key:'year',label:'Birth Year',type:'number',defaultValue:1990},{key:'month',label:'Birth Month',type:'number',defaultValue:5},{key:'day',label:'Birth Day',type:'number',defaultValue:15},{key:'hour',label:'Birth Hour (0-23)',type:'number',defaultValue:12}],\n    formula: (v) => { var s=['Jia Yang Wood','Yi Yin Wood','Bing Yang Fire','Ding Yin Fire','Wu Yang Earth','Ji Yin Earth','Geng Yang Metal','Xin Yin Metal','Ren Yang Water','Gui Yin Water']; var b=['Zi Rat','Chou Ox','Yin Tiger','Mao Rabbit','Chen Dragon','Si Snake','Wu Horse','Wei Goat','Shen Monkey','You Rooster','Xu Dog','Hai Pig']; var y=F(v.year),m=F(v.month),d=F(v.day),h=F(v.hour); var ys=(y-4)%10,yb=(y-4)%12; var ms=(y*12+m+13)%10,mb=(m+1)%12; var ds=(y+m+d+9)%10,db=(y+m+d+5)%12; var hi=Math.floor((h+1)/2)%12; var hs=(((y-4)%10)*2+hi)%10; var el=['Wood','Wood','Fire','Fire','Earth','Earth','Metal','Metal','Water','Water']; var dayEl=el[ds]; var tr={Wood:'Growth-oriented, flexible, idealistic',Fire:'Passionate, dynamic, charismatic',Earth:'Stable, nurturing, practical',Metal:'Disciplined, principled, determined',Water:'Intuitive, wise, adaptable'}; return [{label:'Year Pillar',value:s[ys]+' / '+b[yb]},{label:'Month Pillar',value:s[ms]+' / '+b[mb]},{label:'Day Pillar (You)',value:s[ds]+' / '+b[db]},{label:'Hour Pillar',value:s[hs]+' / '+b[hi]},{label:'Day Master',value:dayEl},{label:'Personality',value:tr[dayEl]||'Balanced'}]; },\n  },"

F['i-ching-divination'] = "  'i-ching-divination': {\n    inputs: [{key:'q',label:'Your Question',type:'text',defaultValue:''}],\n    formula: (v) => { var n={1:'Qian The Creative',2:'Kun The Receptive',3:'Zhun Difficulty',4:'Meng Youthful Folly',5:'Xu Waiting',6:'Song Conflict',11:'Tai Peace',12:'Pi Standstill',15:'Qian Modesty',24:'Fu Return',31:'Xian Influence',32:'Heng Duration',42:'Yi Increase',63:'Ji Ji After Completion',64:'Wei Ji Before Completion'}; var g={1:'Take bold action',2:'Be receptive',11:'Harmony prevails',12:'Wait for timing',24:'New cycle begins',31:'Gentle influence wins',32:'Stay the course',42:'Abundance flows',63:'Near completion,watch details',64:'Goal in sight,navigate carefully'}; var q=String(v.q||''); var seed=0; for(var i=0;i<q.length;i++)seed+=q.charCodeAt(i); var h=((seed*7919+Date.now()%86400000)%64)+1; return [{label:'Hexagram #'+h,value:n[h]||'Hexagram '+h},{label:'Wisdom',value:g[h]||'Reflect with an open mind'}]; },\n  },"

F['tarot-reading'] = "  'tarot-reading': {\n    inputs: [{key:'spread',label:'Spread',type:'select',options:[{label:'3-Card Past/Present/Future',value:'3'},{label:'Single Card',value:'1'}],defaultValue:'3'},{key:'focus',label:'Focus',type:'select',options:[{label:'Love',value:'love'},{label:'Career',value:'career'},{label:'Growth',value:'growth'}],defaultValue:'love'}],\n    formula: (v) => { var M=['The Fool New beginnings','The Magician Skill,manifestation','The High Priestess Intuition,wisdom','The Empress Abundance,nurturing','The Emperor Authority,structure','The Lovers Love,harmony','The Chariot Willpower,victory','Strength Courage,power','The Hermit Soul-searching','Wheel of Fortune Destiny,turning point','Justice Fairness,truth','The Hanged Man Surrender,perspective','Death Transformation,rebirth','Temperance Balance,harmony','The Star Hope,renewal','The Moon Subconscious,illusion','The Sun Joy,success','The World Completion,wholeness']; var m={love:['Ace of Cups New love awakens','Two of Cups Deep connection','Ten of Cups Lasting fulfillment','Knight of Cups Romance','Queen of Cups Emotional wisdom'],career:['Ace of Pentacles Opportunity','Three of Pentacles Teamwork','Eight of Pentacles Mastery','Ten of Pentacles Security','King of Pentacles Leadership'],growth:['Four of Swords Rest,recovery','Seven of Cups Possibilities','The Star Spiritual guidance','Nine of Pentacles Self-sufficiency','Judgment Higher calling']}; var p=function(a){return a[Math.floor(Math.random()*a.length)]}; var c1=Math.random()>0.4?p(M):p(m[v.focus]||m.love); var c2=Math.random()>0.4?p(M):p(m[v.focus]||m.love); var c3=Math.random()>0.4?p(M):p(m[v.focus]||m.love); if(v.spread==='1')return[{label:'Your Card',value:c1}]; return [{label:'Past',value:c1},{label:'Present',value:c2},{label:'Future',value:c3}]; },\n  },"

F['past-life-finder'] = "  'past-life-finder': {\n    inputs: [{key:'bday',label:'Your Birth Date',type:'text',defaultValue:'1990-05-15'}],\n    formula: (v) => { var s=String(v.bday).replace(/-/g,'').split('').reduce(function(a,b){return a+Number(b)},0); var E=['Ancient Egypt','Viking Age','Medieval Europe','Renaissance Italy','Edo Japan','Victorian England','Roaring Twenties','Ancient Rome','Ming Dynasty','Mughal India']; var J=['Philosopher Teacher','Warrior Strategist','Artist Dreamer','Merchant Explorer','Healer Herbalist','Priest Mystic','Musician Poet','Builder Architect','Royal Advisor','Navigator']; var L=['in the Himalayas','near the Nile','in a port city','under Northern Lights','in a monastery','on an island','in a desert city','in a palace']; var K=['Love without attachment','Speak your truth','Trust your intuition','Find balance','Forgive yourself','Embrace change','Cultivate patience','Lead with compassion','Seek wisdom','Protect the vulnerable']; var T=['Adventurous Curious','Intuitive Mysterious','Creative Expressive','Practical Grounded','Charismatic Bold','Analytical Precise','Empathetic Nurturing','Ambitious Determined']; return [{label:'Past Era',value:E[s%E.length]},{label:'You Were',value:J[Math.floor(s*1.7)%J.length]},{label:'You Lived',value:L[Math.floor(s*2.3)%L.length]},{label:'Karmic Lesson',value:K[Math.floor(s*3.1)%K.length]},{label:'Soul Trait',value:T[Math.floor(s*5.7)%T.length]}]; },\n  },"

F['name-compatibility'] = "  'name-compatibility': {\n    inputs: [{key:'n1',label:'Your Name',type:'text',defaultValue:'Alice Chen'},{key:'n2',label:'Partner Name',type:'text',defaultValue:'Bob Wang'}],\n    formula: (v) => { var H=function(s){return s.toLowerCase().replace(/[^a-z]/g,'').split('').reduce(function(a,c){return a+c.charCodeAt(0)},0)}; var n1=String(v.n1),n2=String(v.n2); var s1=H(n1),s2=H(n2); var sc=((s1*s2*7919+104729)%89)+11; var FL=['Friends','Lovers','Affection','Marriage','Enemies','Soulmates']; var f=FL[(s1+s2)%6]; var v1=(n1.match(/[aeiou]/gi)||[]).length,v2=(n2.match(/[aeiou]/gi)||[]).length; var vS=Math.abs(v1-v2)<=1?85:Math.abs(v1-v2)<=2?65:45; var p1=n1.split('').reduce(function(a,c){var v=(c.charCodeAt(0)-96)%9||9;return a+v},0),p2=n2.split('').reduce(function(a,c){var v=(c.charCodeAt(0)-96)%9||9;return a+v},0); var nS=Math.abs(p1-p2)<=2?88:Math.abs(p1-p2)<=5?70:50; var comp=Math.round(vS*0.3+nS*0.3+sc*0.4); return [{label:'Compatibility',value:comp+'%'},{label:'FLAMES',value:f},{label:'Vowel Harmony',value:vS+'%'},{label:'Numerology',value:nS+'%'}]; },\n  },"

F['daily-fortune'] = "  'daily-fortune': {\n    inputs: [{key:'sign',label:'Your Sign',type:'select',options:[{label:'Aries',value:'aries'},{label:'Taurus',value:'taurus'},{label:'Gemini',value:'gemini'},{label:'Cancer',value:'cancer'},{label:'Leo',value:'leo'},{label:'Virgo',value:'virgo'},{label:'Libra',value:'libra'},{label:'Scorpio',value:'scorpio'},{label:'Sagittarius',value:'sagittarius'},{label:'Capricorn',value:'capricorn'},{label:'Aquarius',value:'aquarius'},{label:'Pisces',value:'pisces'}],defaultValue:'leo'}],\n    formula: (v) => { var t=new Date(); var seed=t.getFullYear()*10000+(t.getMonth()+1)*100+t.getDate()+String(v.sign).length; var F=['Unexpected joy is heading your way. Stay open to new possibilities.','Your creative energy peaks today. Share your ideas boldly.','Financial luck favors you. Consider that calculated risk.','A meaningful conversation awaits. Speak from the heart.','Trust your intuition on a decision you have been weighing.','Your hard work is about to pay off. Keep pushing forward.','Someone from your past brings valuable insight today.','Love and warmth surround you. Nurture your closest bonds.','A new opportunity appears. Say yes before overthinking.','Self-care day. Rest and recharge your spirit.','Your leadership shines. Others look to you for guidance.','Learning opens unexpected doors today.']; var C=['Royal Blue','Emerald Green','Crimson Red','Golden Yellow','Deep Purple','Ocean Teal','Rose Pink','Warm Amber','Silver Grey','Pearl White','Sage Green','Midnight Black']; var nums=[((seed*7+13)%49)+1,((seed*11+7)%49)+1,((seed*17+3)%49)+1,((seed*23+11)%49)+1,((seed*29+5)%49)+1,((seed*31+17)%49)+1]; return [{label:'Fortune',value:F[seed%F.length]},{label:'Color',value:C[seed%C.length]},{label:'Numbers',value:nums.join(', ')}]; },\n  },"

F['lucky-number-generator'] = "  'lucky-number-generator': {\n    inputs: [{key:'bday',label:'Birth Date',type:'text',defaultValue:'1990-05-15'},{key:'count',label:'Count',type:'number',defaultValue:6},{key:'max',label:'Max',type:'number',defaultValue:49}],\n    formula: (v) => { var rd=function(n){while(n>9&&n!==11&&n!==22&&n!==33)n=String(n).split('').reduce(function(a,b){return a+Number(b)},0);return n;}; var s=String(v.bday).replace(/-/g,''); var lp=rd(s.split('').reduce(function(a,b){return a+Number(b)},0)); var t=new Date(); var seed=lp*100+t.getDate()+t.getMonth(); var nums=[],used={}; for(var i=0;i<F(v.count);i++){var n=((seed*(i*7+3)+lp*(i*13+5)+t.getFullYear()*(i+1))%F(v.max))+1; var tries=0; while(used[n]&&tries<100){n=((n*17+13)%F(v.max))+1;tries++;} used[n]=true; nums.push(n);} nums.sort(function(a,b){return a-b}); return [{label:'Life Path',value:String(lp)},{label:'Lucky Numbers',value:nums.join(', ')}]; },\n  },"

count = 0
for tid, replacement in F.items():
    start = content.find("'"+tid+"': {")
    if start < 0: continue
    depth = 0; end = start
    for i in range(start, len(content)):
        if content[i] == '{': depth += 1
        if content[i] == '}': depth -= 1
        if depth == 0 and content[i] == '}':
            end = i + 1
            if end < len(content) and content[end] == ',': end += 1
            break
    content = content[:start] + replacement + content[end:]
    count += 1

with open("src/app/data/formulas.ts", "w", encoding="utf-8") as f:
    f.write(content)
print(f"Fixed {count} fortune tools")
