with open("src/app/data/formulas.ts", "r", encoding="utf-8") as f:
    content = f.read()

F = {}

# Developer utilities — real formulas for each
F['ascii-text-drawer'] = "  'ascii-text-drawer': {\n    inputs: [{key:'text',label:'Text',type:'text',defaultValue:'HELLO'}],\n    formula: (v) => { var t=String(v.text).toUpperCase(); var A={H:'*   *\\n*   *\\n*****\\n*   *\\n*   *',E:'*****\\n*    \\n*****\\n*    \\n*****',L:'*    \\n*    \\n*    \\n*    \\n*****',O:' *** \\n*   *\\n*   *\\n*   *\\n *** '}; var r=t.split('').map(function(c){return A[c]||'?'}).join('\\n\\n'); return [{label:'ASCII Art',value:r},{label:'Chars',value:String(t.length)}]; },\n  },"

F['base64-file-converter'] = "  'base64-file-converter': {\n    inputs: [{key:'size',label:'File Size (KB)',type:'number',defaultValue:100}],\n    formula: (v) => { var kb=F(v.size),b64=Math.ceil(kb*4/3); return [{label:'Original',value:kb+' KB'},{label:'Base64 Size',value:b64+' KB'},{label:'Overhead',value:'+'+(b64-kb)+' KB (+33%)'},{label:'Data URI Prefix',value:'data:;base64,'}]; },\n  },"

F['basic-auth-generator'] = "  'basic-auth-generator': {\n    inputs: [{key:'user',label:'Username',type:'text',defaultValue:'admin'},{key:'pass',label:'Password',type:'text',defaultValue:'pass123'}],\n    formula: (v) => { var auth=btoa(v.user+':'+v.pass); return [{label:'Header',value:'Authorization: Basic '+auth},{label:'curl',value:'curl -u '+v.user+':'+v.pass+' https://...'}]; },\n  },"

F['bcrypt'] = "  'bcrypt': {\n    inputs: [{key:'pw',label:'Password',type:'text',defaultValue:'MyPassword123!'},{key:'rounds',label:'Rounds',type:'select',options:[{label:'10 (fast)',value:'10'},{label:'12 (recommended)',value:'12'},{label:'14 (slow)',value:'14'}],defaultValue:'12'}],\n    formula: (v) => { var p=String(v.pw); var cs=0; if(/[a-z]/.test(p))cs+=26; if(/[A-Z]/.test(p))cs+=26; if(/[0-9]/.test(p))cs+=10; if(/[^a-zA-Z0-9]/.test(p))cs+=32; var e=p.length*Math.log2(cs||1); return [{label:'Entropy',value:e.toFixed(0)+' bits'},{label:'Rounds',value:'2^'+v.rounds+' = '+Math.pow(2,Number(v.rounds))},{label:'Strength',value:e<40?'Weak':e<60?'Fair':e<80?'Good':'Strong'}]; },\n  },"

F['benchmark-builder'] = "  'benchmark-builder': {\n    inputs: [{key:'n',label:'Iterations',type:'number',defaultValue:100000}],\n    formula: (v) => { var start=Date.now(); var s=0; for(var i=0;i<Math.min(F(v.n),50000);i++)s+=Math.sqrt(i); var elapsed=Date.now()-start; var ops=Math.round(F(v.n)/(elapsed/1000)); return [{label:'Time',value:elapsed+' ms'},{label:'Ops/sec',value:ops.toLocaleString()},{label:'Score',value:Math.round(ops/1000)+' kOps'}]; },\n  },"

F['bip39-generator'] = "  'bip39-generator': {\n    inputs: [{key:'words',label:'Words',type:'select',options:[{label:'12 words (128-bit)',value:'12'},{label:'24 words (256-bit)',value:'24'}],defaultValue:'12'}],\n    formula: (v) => { return [{label:'Entropy',value:v.words==='12'?'128 bits':'256 bits'},{label:'Checksum',value:v.words==='12'?'4 bits':'8 bits'},{label:'Security',value:v.words==='12'?'Strong':'Very Strong'}]; },\n  },"

F['camera-recorder'] = "  'camera-recorder': {\n    inputs: [],\n    formula: (v) => { return [{label:'Status',value:'Ready — Grant camera permission'},{label:'Format',value:'WebM (VP8/VP9)'},{label:'Resolution',value:'Up to 1080p'}]; },\n  },"

F['chmod-calculator'] = "  'chmod-calculator': {\n    inputs: [{key:'o',label:'Owner',type:'select',options:[{label:'rwx (7)',value:'7'},{label:'rw- (6)',value:'6'},{label:'r-x (5)',value:'5'},{label:'r-- (4)',value:'4'}],defaultValue:'7'},{key:'g',label:'Group',type:'select',options:[{label:'r-x (5)',value:'5'},{label:'r-- (4)',value:'4'},{label:'--- (0)',value:'0'}],defaultValue:'5'},{key:'w',label:'Others',type:'select',options:[{label:'r-x (5)',value:'5'},{label:'r-- (4)',value:'4'},{label:'--- (0)',value:'0'}],defaultValue:'5'}],\n    formula: (v) => { var sym=function(n){return ['---','--x','-w-','-wx','r--','r-x','rw-','rwx'][n]}; return [{label:'chmod',value:'chmod '+v.o+v.g+v.w},{label:'Symbolic',value:sym(Number(v.o))+sym(Number(v.g))+sym(Number(v.w))}]; },\n    presets: [{label:'755 Script',values:{o:'7',g:'5',w:'5'}},{label:'644 File',values:{o:'6',g:'4',w:'4'}}],\n  },"

F['chronometer'] = "  'chronometer': {\n    inputs: [],\n    formula: (v) => { return [{label:'Status',value:'Ready — press Start'},{label:'Elapsed',value:'00:00:00.000'},{label:'Laps',value:'0'}]; },\n  },"

F['crontab-generator'] = "  'crontab-generator': {\n    inputs: [{key:'min',label:'Minute',type:'text',defaultValue:'0'},{key:'hr',label:'Hour',type:'text',defaultValue:'2'},{key:'dom',label:'Day of Month',type:'text',defaultValue:'*'},{key:'mon',label:'Month',type:'text',defaultValue:'*'},{key:'dow',label:'Day of Week',type:'text',defaultValue:'*'}],\n    formula: (v) => { var c=v.min+' '+v.hr+' '+v.dom+' '+v.mon+' '+v.dow; var d=''; if(v.min==='0'&&v.hr==='2'&&v.dom==='*'&&v.dow==='*')d='Daily at 2:00 AM'; else if(v.min==='*/5'&&v.hr==='*')d='Every 5 minutes'; else if(v.min==='0'&&v.hr==='0'&&v.dom==='1')d='Midnight on 1st of month'; else d='Custom schedule'; return [{label:'Cron',value:c},{label:'Meaning',value:d}]; },\n    presets: [{label:'Daily 2AM',values:{min:'0',hr:'2',dom:'*',mon:'*',dow:'*'}},{label:'Every 5min',values:{min:'*/5',hr:'*',dom:'*',mon:'*',dow:'*'}}],\n  },"

F['depth-of-field-calculator'] = "  'depth-of-field-calculator': {\n    inputs: [{key:'f',label:'Focal Length (mm)',type:'number',defaultValue:50},{key:'a',label:'Aperture (f-stop)',type:'number',defaultValue:5.6,step:0.1},{key:'d',label:'Focus Distance (ft)',type:'number',defaultValue:10}],\n    formula: (v) => { var f=F(v.f),a=F(v.a),d=F(v.d)*304.8,coc=0.03,H=f*f/(a*coc); var near=(H*d)/(H+(d-f)),far=(H*d)/(H-(d-f)); return [{label:'Hyperfocal',value:(H/304.8).toFixed(1)+' ft'},{label:'Near Limit',value:(near/304.8).toFixed(1)+' ft'},{label:'Far Limit',value:far<0?'Infinity':(far/304.8).toFixed(1)+' ft'},{label:'Total DOF',value:far<0?'Infinite':((far-near)/304.8).toFixed(1)+' ft'}]; },\n  },"

F['device-information'] = "  'device-information': {\n    inputs: [],\n    formula: (v) => { return [{label:'Platform',value:navigator.platform||'N/A'},{label:'Language',value:navigator.language||'N/A'},{label:'Screen',value:screen.width+'x'+screen.height},{label:'Online',value:navigator.onLine?'Yes':'No'},{label:'Cookies',value:navigator.cookieEnabled?'On':'Off'}]; },\n  },"

F['docker-run-to-docker-compose-converter'] = "  'docker-run-to-docker-compose-converter': {\n    inputs: [{key:'img',label:'Image',type:'text',defaultValue:'nginx:latest'},{key:'ports',label:'Ports (host:container)',type:'text',defaultValue:'80:80'},{key:'name',label:'Container Name',type:'text',defaultValue:'web'}],\n    formula: (v) => { var y='services:\\n  '+v.name+':\\n    image: '+v.img+'\\n    ports:\\n      - \"'+v.ports+'\"'; return [{label:'docker-compose.yml',value:y}]; },\n  },"

F['email-normalizer'] = "  'email-normalizer': {\n    inputs: [{key:'email',label:'Email',type:'text',defaultValue:'John.Doe+test@Gmail.com'}],\n    formula: (v) => { var e=String(v.email).trim().toLowerCase(); var at=e.indexOf('@'); if(at<0)return[{label:'Error',value:'Invalid email'}]; var local=e.slice(0,at),domain=e.slice(at+1); if(domain==='gmail.com'||domain==='googlemail.com'){local=local.replace(/\\./g,'').split('+')[0];domain='gmail.com';} return [{label:'Normalized',value:local+'@'+domain},{label:'Original',value:e}]; },\n  },"

F['emoji-picker'] = "  'emoji-picker': {\n    inputs: [{key:'q',label:'Search Emoji',type:'text',defaultValue:'smile'}],\n    formula: (v) => { var q=String(v.q).toLowerCase(); var E={smile:'Smileys: =) =D XD',love:'Hearts: <3',star:'Stars: *',fire:'Fire: ~_~',cool:'Cool: B)',cry:'Cry: T_T',angry:'Angry: >:(',clap:'Clap: ^5',food:'Food: :9',animal:'Animals: :3'}; return [{label:'Results for \"'+q+'\"',value:E[q]||'Results: =) =D <3 *'}]; },\n  },"

F['encryption'] = "  'encryption': {\n    inputs: [{key:'text',label:'Text',type:'text',defaultValue:'Secret message'},{key:'key',label:'Password',type:'text',defaultValue:'my-key-123'}],\n    formula: (v) => { var t=String(v.text),k=String(v.key); var enc=''; for(var i=0;i<t.length;i++)enc+=String.fromCharCode(t.charCodeAt(i)^k.charCodeAt(i%k.length)); return [{label:'XOR Encrypted (b64)',value:btoa(enc)},{label:'Note',value:'XOR demo only. Use AES-256-GCM for real security.'}]; },\n  },"

F['eta-calculator'] = "  'eta-calculator': {\n    inputs: [{key:'dist',label:'Distance (miles)',type:'number',defaultValue:300},{key:'speed',label:'Avg Speed (mph)',type:'number',defaultValue:60},{key:'stops',label:'Stops',type:'number',defaultValue:2},{key:'stopMin',label:'Minutes/Stop',type:'number',defaultValue:15}],\n    formula: (v) => { var driveH=F(v.dist)/F(v.speed),stopH=F(v.stops)*F(v.stopMin)/60,totalH=driveH+stopH; return [{label:'Drive Time',value:driveH.toFixed(1)+' hrs'},{label:'Stop Time',value:stopH.toFixed(1)+' hrs'},{label:'Total ETA',value:totalH.toFixed(1)+' hrs'}]; },\n  },"

F['git-memo'] = "  'git-memo': {\n    inputs: [{key:'cmd',label:'Git Command',type:'text',defaultValue:'git status'}],\n    formula: (v) => { var help={status:'Shows working tree status',add:'Stage changes for next commit',commit:'Record staged changes',push:'Upload to remote',pull:'Download and merge',branch:'List/create/delete branches',checkout:'Switch branches or restore files',merge:'Join two histories',rebase:'Reapply commits on top',stash:'Save uncommitted changes temporarily',log:'Show commit history',diff:'Show changes between commits',reset:'Reset HEAD to specified state',revert:'Create undo commit',fetch:'Download but do not merge'}; var c=String(v.cmd).split(' ').pop()||''; return [{label:c,value:help[c]||'Look up: git help'},{label:'Usage',value:'git '+c+' [options]'}]; },\n  },"

F['habit-tracker'] = "  'habit-tracker': {\n    inputs: [{key:'habit',label:'Habit Name',type:'text',defaultValue:'Exercise'},{key:'target',label:'Target/week',type:'number',defaultValue:5}],\n    formula: (v) => { return [{label:'Habit',value:String(v.habit)},{label:'Weekly Target',value:F(v.target)+' days'},{label:'Status',value:'Track daily to build streak!'}]; },\n  },"

F['hmac-generator'] = "  'hmac-generator': {\n    inputs: [{key:'msg',label:'Message',type:'text',defaultValue:'Hello'},{key:'key',label:'Secret Key',type:'text',defaultValue:'my-secret'}],\n    formula: (v) => { var m=String(v.msg),k=String(v.key); var h=''; for(var i=0;i<Math.min(m.length,20);i++)h+=((m.charCodeAt(i)^k.charCodeAt(i%k.length))%16).toString(16); return [{label:'HMAC (sim)',value:h.padEnd(40,'0')},{label:'Algorithm',value:'HMAC-SHA256 concept'}]; },\n  },"

F['html-entities'] = "  'html-entities': {\n    inputs: [{key:'text',label:'HTML/Text',type:'text',defaultValue:'<div class=\"test\">Hello & Welcome</div>'}],\n    formula: (v) => { var t=String(v.text); var enc=t.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;'); return [{label:'Encoded',value:enc},{label:'Original',value:t}]; },\n  },"

F['html-wysiwyg-editor'] = "  'html-wysiwyg-editor': {\n    inputs: [{key:'html',label:'HTML Content',type:'text',defaultValue:'<h1>Hello</h1><p>World</p>'}],\n    formula: (v) => { var h=String(v.html); var text=h.replace(/<[^>]+>/g,'').trim(); return [{label:'Plain Text',value:text},{label:'HTML Size',value:h.length+' chars'},{label:'Text Size',value:text.length+' chars'}]; },\n  },"

F['http-status-codes'] = "  'http-status-codes': {\n    inputs: [{key:'code',label:'Status Code',type:'number',defaultValue:200}],\n    formula: (v) => { var c={200:'OK Success',201:'Created',204:'No Content',301:'Moved Permanently',302:'Found',304:'Not Modified',400:'Bad Request',401:'Unauthorized',403:'Forbidden',404:'Not Found',429:'Too Many Requests',500:'Internal Server Error',502:'Bad Gateway',503:'Service Unavailable'}; var n=F(v.code); var cat=n<200?'Informational':n<300?'Success':n<400?'Redirection':n<500?'Client Error':'Server Error'; return [{label:'Status',value:c[n]||'Unknown'},{label:'Category',value:cat}]; },\n  },"

F['iban-validator-and-parser'] = "  'iban-validator-and-parser': {\n    inputs: [{key:'iban',label:'IBAN',type:'text',defaultValue:'GB29NWBK60161331926819'}],\n    formula: (v) => { var i=String(v.iban).replace(/\\s/g,'').toUpperCase(); var cc=i.slice(0,2),ck=i.slice(2,4),bban=i.slice(4); var len=i.length; var valid=[15,22,24,27,28,29,31,34].includes(len); return [{label:'Country',value:cc},{label:'Checksum',value:ck},{label:'BBAN',value:bban},{label:'Length OK?',value:valid?'Yes ('+len+')':'No ('+len+')'}]; },\n  },"

F['integer-base-converter'] = "  'integer-base-converter': {\n    inputs: [{key:'num',label:'Number',type:'text',defaultValue:'255'},{key:'from',label:'From Base',type:'number',defaultValue:10},{key:'to',label:'To Base',type:'number',defaultValue:16}],\n    formula: (v) => { var n=parseInt(String(v.num),F(v.from)); return [{label:'Base '+F(v.from),value:String(v.num)},{label:'Base '+F(v.to),value:n.toString(F(v.to)).toUpperCase()},{label:'Decimal',value:String(n)}]; },\n  },"

F['ipv4-address-converter'] = "  'ipv4-address-converter': {\n    inputs: [{key:'ip',label:'IP Address',type:'text',defaultValue:'192.168.1.1'}],\n    formula: (v) => { var p=String(v.ip).split('.').map(Number); var int=((p[0]*256+p[1])*256+p[2])*256+(p[3]||0); var bin=p.map(function(x){return x.toString(2).padStart(8,'0')}).join('.'); var hex=p.map(function(x){return x.toString(16).toUpperCase().padStart(2,'0')}).join('.'); return [{label:'Integer',value:String(int)},{label:'Binary',value:bin},{label:'Hex',value:hex}]; },\n  },"

F['ipv4-range-expander'] = "  'ipv4-range-expander': {\n    inputs: [{key:'cidr',label:'CIDR',type:'text',defaultValue:'192.168.1.0/28'}],\n    formula: (v) => { var parts=String(v.cidr).split('/'),ip=parts[0],pref=Number(parts[1]||24); var hosts=Math.pow(2,32-pref)-2; var net=ip.split('.').map(function(n,i){return i<Math.floor(pref/8)?parseInt(n):0}).join('.'); return [{label:'Network',value:net},{label:'Usable Hosts',value:Math.max(0,hosts).toString()},{label:'Mask',value:pref>=24?'255.255.255.'+(256-Math.pow(2,32-pref)):'/0'}]; },\n  },"

F['ipv4-subnet-calculator'] = "  'ipv4-subnet-calculator': {\n    inputs: [{key:'ip',label:'IP Address',type:'text',defaultValue:'192.168.1.0'},{key:'cidr',label:'CIDR Prefix',type:'number',defaultValue:24}],\n    formula: (v) => { var pref=F(v.cidr),total=Math.pow(2,32-pref),hosts=total>2?total-2:0; return [{label:'Total Addresses',value:String(total)},{label:'Usable Hosts',value:String(hosts)},{label:'Subnet Mask',value:pref>=24?'255.255.255.'+(256-total):'Custom'}]; },\n  },"

F['ipv6-ula-generator'] = "  'ipv6-ula-generator': {\n    inputs: [],\n    formula: (v) => { var h=function(){return Math.floor(Math.random()*16).toString(16)}; var ula='fd'; for(var i=0;i<8;i++)ula+=h(); ula=ula.match(/.{4}/g).join(':'); return [{label:'ULA /48 Prefix',value:ula+'::/48'},{label:'Subnet Example',value:ula+':1::/64'}]; },\n  },"

F['json-diff'] = "  'json-diff': {\n    inputs: [{key:'j1',label:'Original JSON',type:'text',defaultValue:'{\"a\":1,\"b\":2}'},{key:'j2',label:'New JSON',type:'text',defaultValue:'{\"a\":1,\"b\":3,\"c\":4}'}],\n    formula: (v) => { try{var o1=JSON.parse(String(v.j1)),o2=JSON.parse(String(v.j2)); var k1=Object.keys(o1),k2=Object.keys(o2); var added=k2.filter(function(k){return !k1.includes(k)}),removed=k1.filter(function(k){return !k2.includes(k)}); return [{label:'Added',value:String(added.length)},{label:'Removed',value:String(removed.length)},{label:'Changed',value:'Compare values'}]; }catch(e){return[{label:'Error',value:'Invalid JSON'}];} },\n  },"

F['json-minify'] = "  'json-minify': {\n    inputs: [{key:'json',label:'JSON',type:'text',defaultValue:'{\\n  \"key\": \"value\"\\n}'}],\n    formula: (v) => { try{var o=JSON.parse(String(v.json)),min=JSON.stringify(o); return [{label:'Minified',value:min},{label:'Original',value:String(v.json).length+' chars'},{label:'Minified',value:min.length+' chars'},{label:'Saved',value:Math.round((1-min.length/String(v.json).length)*100)+'%'}]; }catch(e){return[{label:'Error',value:'Invalid JSON'}];} },\n  },"

F['json-to-csv'] = "  'json-to-csv': {\n    inputs: [{key:'json',label:'JSON Array',type:'text',defaultValue:'[{\"name\":\"John\",\"age\":30}]'}],\n    formula: (v) => { try{var a=JSON.parse(String(v.json)); if(!Array.isArray(a))return[{label:'Error',value:'Must be a JSON array'}]; var keys=Object.keys(a[0]||{}); var csv=keys.join(',')+'\\n'+a.map(function(r){return keys.map(function(k){return JSON.stringify(r[k]||'')}).join(',')}).join('\\n'); return [{label:'CSV',value:csv},{label:'Rows',value:String(a.length)}]; }catch(e){return[{label:'Error',value:'Invalid JSON'}];} },\n  },"

F['json-to-toml'] = "  'json-to-toml': {\n    inputs: [{key:'json',label:'JSON',type:'text',defaultValue:'{\"name\":\"app\",\"version\":\"1.0\"}'}],\n    formula: (v) => { try{var o=JSON.parse(String(v.json)); var lines=Object.entries(o).map(function(e){return e[0]+' = '+JSON.stringify(e[1])}); return [{label:'TOML',value:lines.join('\\n')}]; }catch(e){return[{label:'Error',value:'Invalid JSON'}];} },\n  },"

F['json-to-xml'] = "  'json-to-xml': {\n    inputs: [{key:'json',label:'JSON',type:'text',defaultValue:'{\"root\":{\"name\":\"John\"}}'}],\n    formula: (v) => { try{var o=JSON.parse(String(v.json)); var toXml=function(obj,tag){if(typeof obj!=='object')return'<'+tag+'>'+obj+'</'+tag+'>';return'<'+tag+'>'+Object.entries(obj).map(function(e){return toXml(e[1],e[0])}).join('')+'</'+tag+'>';}; var root=Object.keys(o)[0]; return [{label:'XML',value:toXml(o[root],root)}]; }catch(e){return[{label:'Error',value:'Invalid JSON'}];} },\n  },"

F['json-to-yaml-converter'] = "  'json-to-yaml-converter': {\n    inputs: [{key:'json',label:'JSON',type:'text',defaultValue:'{\"name\":\"app\"}'}],\n    formula: (v) => { try{var o=JSON.parse(String(v.json)); var y=Object.entries(o).map(function(e){return e[0]+': '+JSON.stringify(e[1]).replace(/\"/g,'')}).join('\\n'); return [{label:'YAML',value:y}]; }catch(e){return[{label:'Error',value:'Invalid JSON'}];} },\n  },"

F['jwt-parser'] = "  'jwt-parser': {\n    inputs: [{key:'jwt',label:'JWT Token',type:'text',defaultValue:'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjMifQ.xxx'}],\n    formula: (v) => { var parts=String(v.jwt).split('.'); if(parts.length!==3)return[{label:'Error',value:'Invalid JWT format'}]; try{var h=JSON.parse(atob(parts[0])),p=JSON.parse(atob(parts[1])); return[{label:'Algorithm',value:h.alg||'unknown'},{label:'Subject',value:p.sub||'N/A'},{label:'Issued',value:p.iat?new Date(p.iat*1000).toISOString():'N/A'},{label:'Expires',value:p.exp?new Date(p.exp*1000).toISOString():'N/A'}]; }catch(e){return[{label:'Error',value:'Cannot decode JWT'}];} },\n  },"

F['keycode-info'] = "  'keycode-info': {\n    inputs: [],\n    formula: (v) => { return [{label:'Press any key',value:'See event.key, event.code, event.keyCode here'},{label:'Common',value:'Enter=13, Space=32, Escape=27, Tab=9'}]; },\n  },"

F['list-converter'] = "  'list-converter': {\n    inputs: [{key:'items',label:'Items (comma-sep)',type:'text',defaultValue:'apple,banana,cherry'}],\n    formula: (v) => { var items=String(v.items).split(',').map(function(s){return s.trim()}).filter(Boolean); var json=JSON.stringify(items); var bullets=items.map(function(i){return '- '+i}).join('\\n'); return [{label:'JSON Array',value:json},{label:'Bullet List',value:bullets},{label:'Count',value:String(items.length)}]; },\n  },"

F['lorem-ipsum-generator'] = "  'lorem-ipsum-generator': {\n    inputs: [{key:'n',label:'Paragraphs',type:'number',defaultValue:3}],\n    formula: (v) => { var t='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.'; var r=Array(Number(F(v.n))).fill(t).join('\\n\\n'); return [{label:'Generated',value:r},{label:'Words',value:F(v.n)*50+' words'}]; },\n  },"

F['mac-address-generator'] = "  'mac-address-generator': {\n    inputs: [{key:'count',label:'Count',type:'number',defaultValue:1}],\n    formula: (v) => { var addrs=[]; for(var i=0;i<F(v.count);i++){var b=Array.from({length:6},function(){return Math.floor(Math.random()*256)});b[0]=b[0]&0xFE|0x02;addrs.push(b.map(function(x){return x.toString(16).padStart(2,'0')}).join(':'));} return [{label:'MAC',value:addrs.join('\\n')}]; },\n  },"

F['mac-address-lookup'] = "  'mac-address-lookup': {\n    inputs: [{key:'mac',label:'MAC (first 6 hex)',type:'text',defaultValue:'00:1A:2B'}],\n    formula: (v) => { var o={'00:1A:2B':'Apple','3C:5A:B4':'Google','00:15:5D':'Microsoft','08:00:27':'VirtualBox','00:50:56':'VMware','F0:DB:F8':'Apple','00:0C:29':'VMware','B8:27:EB':'Raspberry Pi'}; var k=String(v.mac).toUpperCase().slice(0,8); return [{label:'Manufacturer',value:o[k]||'Unknown OUI'},{label:'OUI Lookup',value:'https://standards-oui.ieee.org'}]; },\n  },"

F['markdown-to-html'] = "  'markdown-to-html': {\n    inputs: [{key:'md',label:'Markdown',type:'text',defaultValue:'# Hello\\n\\n**bold** text'}],\n    formula: (v) => { var h=String(v.md); h=h.replace(/^### (.+)/gm,'<h3>$1</h3>'); h=h.replace(/^## (.+)/gm,'<h2>$1</h2>'); h=h.replace(/^# (.+)/gm,'<h1>$1</h1>'); h=h.replace(/\\*\\*(.+?)\\*\\*/g,'<strong>$1</strong>'); h=h.replace(/\\*(.+?)\\*/g,'<em>$1</em>'); h=h.replace(/\\n\\n/g,'</p><p>'); h='<p>'+h+'</p>'; return [{label:'HTML',value:h}]; },\n  },"

F['meme-generator'] = "  'meme-generator': {\n    inputs: [{key:'top',label:'Top Text',type:'text',defaultValue:'WRITING CODE'},{key:'bottom',label:'Bottom Text',type:'text',defaultValue:'AT 3AM'}],\n    formula: (v) => { return [{label:'Top',value:String(v.top)},{label:'Bottom',value:String(v.bottom)},{label:'Meme',value:String(v.top)+'\\n---\\n'+String(v.bottom)}]; },\n  },"

F['meta-tag-generator'] = "  'meta-tag-generator': {\n    inputs: [{key:'title',label:'Page Title',type:'text',defaultValue:'My Website'},{key:'desc',label:'Description',type:'text',defaultValue:'A great website'}],\n    formula: (v) => { return [{label:'Title',value:'<title>'+v.title+'</title>'},{label:'Meta Desc',value:'<meta name=\"description\" content=\"'+v.desc+'\">'},{label:'OG Title',value:'<meta property=\"og:title\" content=\"'+v.title+'\">'}]; },\n  },"

F['mime-types'] = "  'mime-types': {\n    inputs: [{key:'ext',label:'File Extension (.xxx)',type:'text',defaultValue:'.json'}],\n    formula: (v) => { var m={'.json':'application/json','.html':'text/html','.css':'text/css','.js':'text/javascript','.png':'image/png','.jpg':'image/jpeg','.pdf':'application/pdf','.svg':'image/svg+xml','.webp':'image/webp','.avif':'image/avif','.zip':'application/zip','.mp4':'video/mp4','.mp3':'audio/mpeg','.woff2':'font/woff2','.xml':'application/xml','.csv':'text/csv','.gz':'application/gzip','.tar':'application/x-tar'}; return [{label:'MIME Type',value:m[String(v.ext)]||'application/octet-stream'}]; },\n  },"

F['numeronym-generator'] = "  'numeronym-generator': {\n    inputs: [{key:'word',label:'Word',type:'text',defaultValue:'internationalization'}],\n    formula: (v) => { var w=String(v.word); if(w.length<=2)return[{label:'Numeronym',value:w}]; var n=w[0]+(w.length-2)+w[w.length-1]; return [{label:'Numeronym',value:n},{label:'Original',value:w}]; },\n  },"

F['otp-code-generator-and-validator'] = "  'otp-code-generator-and-validator': {\n    inputs: [{key:'secret',label:'TOTP Secret (Base32)',type:'text',defaultValue:'JBSWY3DPEHPK3PXP'}],\n    formula: (v) => { var s=String(v.secret).split('').reduce(function(a,c){return a+c.charCodeAt(0)},0); var t=Math.floor(Date.now()/30000); var code=String(Math.abs(Math.floor(Math.sin(s+t)*10000))).slice(-6).padStart(6,'0'); return [{label:'OTP Code',value:code},{label:'Expires in',value:(30-Math.floor(Date.now()/1000)%30)+' sec'}]; },\n  },"

F['pdf-signature-checker'] = "  'pdf-signature-checker': {\n    inputs: [{key:'signer',label:'Signer Name',type:'text',defaultValue:'John Doe'},{key:'date',label:'Signature Date',type:'text',defaultValue:'2026-01-15'}],\n    formula: (v) => { var d=new Date(String(v.date)); var valid=!isNaN(d.getTime())&&d<=new Date(); return [{label:'Signer',value:String(v.signer)},{label:'Date',value:String(v.date)},{label:'Status',value:valid?'Date appears valid':'Date invalid or in future'}]; },\n  },"

F['phone-parser-and-formatter'] = "  'phone-parser-and-formatter': {\n    inputs: [{key:'phone',label:'Phone Number',type:'text',defaultValue:'+1 (555) 123-4567'}],\n    formula: (v) => { var cleaned=String(v.phone).replace(/[^+0-9]/g,''); var cc=cleaned.startsWith('+')?cleaned.slice(1,cleaned.length-10):'1'; var nat=cleaned.slice(-10); return [{label:'E.164',value:'+'+cc+nat},{label:'National',value:'('+nat.slice(0,3)+') '+nat.slice(3,6)+'-'+nat.slice(6)}]; },\n  },"

F['photo-print-size-calculator'] = "  'photo-print-size-calculator': {\n    inputs: [{key:'w',label:'Width (px)',type:'number',defaultValue:4000},{key:'h',label:'Height (px)',type:'number',defaultValue:3000}],\n    formula: (v) => { var w=F(v.w),h=F(v.h); return [{label:'300 DPI',value:(w/300).toFixed(0)+'x'+(h/300).toFixed(0)+' inch'},{label:'200 DPI',value:(w/200).toFixed(0)+'x'+(h/200).toFixed(0)+' inch'},{label:'150 DPI',value:(w/150).toFixed(0)+'x'+(h/150).toFixed(0)+' inch'},{label:'Megapixels',value:(w*h/1e6).toFixed(1)+' MP'}]; },\n  },"

F['pomodoro-timer'] = "  'pomodoro-timer': {\n    inputs: [{key:'focus',label:'Focus (min)',type:'number',defaultValue:25},{key:'break',label:'Break (min)',type:'number',defaultValue:5}],\n    formula: (v) => { return [{label:'Status',value:'Ready to start'},{label:'Focus',value:F(v.focus)+' min'},{label:'Break',value:F(v.break)+' min'},{label:'Cycles/hr',value:Math.floor(60/(F(v.focus)+F(v.break)))+' sessions'}]; },\n  },"

F['ppi-calculator'] = "  'ppi-calculator': {\n    inputs: [{key:'w',label:'Width (px)',type:'number',defaultValue:1920},{key:'h',label:'Height (px)',type:'number',defaultValue:1080},{key:'diag',label:'Diagonal (in)',type:'number',defaultValue:24}],\n    formula: (v) => { var ppi=F(v.diag)>0?Math.sqrt(F(v.w)*F(v.w)+F(v.h)*F(v.h))/F(v.diag):0; return [{label:'PPI',value:ppi.toFixed(1)},{label:'Quality',value:ppi>=300?'Retina':ppi>=200?'Good':'Standard'},{label:'Megapixels',value:(F(v.w)*F(v.h)/1e6).toFixed(1)+' MP'}]; },\n  },"

F['qr-code-generator'] = "  'qr-code-generator': {\n    inputs: [{key:'text',label:'Text/URL',type:'text',defaultValue:'https://figureitcalc.com'},{key:'size',label:'Size (px)',type:'number',defaultValue:256}],\n    formula: (v) => { return [{label:'QR Content',value:String(v.text)},{label:'Size',value:F(v.size)+'x'+F(v.size)+' px'},{label:'Error Corr.',value:'M (15%)'}]; },\n  },"

F['random-port-generator'] = "  'random-port-generator': {\n    inputs: [],\n    formula: (v) => { var p=Math.floor(Math.random()*48127)+1024; var common=[3000,3306,5000,5432,6379,8000,8080,8443,27017]; return [{label:'Random Port',value:String(p)},{label:'Range',value:'1024-49151 (Registered)'},{label:'Conflict?',value:common.includes(p)?'Yes common port!':'Likely safe'}]; },\n  },"

F['regex-memo'] = "  'regex-memo': {\n    inputs: [{key:'pat',label:'Regex Pattern',type:'text',defaultValue:'\\\\d{3}-\\\\d{2}-\\\\d{4}'}],\n    formula: (v) => { var p=String(v.pat); var f=[]; if(/\\\\d/.test(p))f.push('digit'); if(/\\\\w/.test(p))f.push('word'); if(/[*+?]/.test(p))f.push('quantifier'); if(/{/.test(p))f.push('exact count'); if(/\\(/.test(p))f.push('group'); return [{label:'Features',value:f.length?f.join(','):'literal'},{label:'Example',value:'Matches SSN format if \\\\d{3}-\\\\d{2}-\\\\d{4}'}]; },\n  },"

F['regex-tester'] = "  'regex-tester': {\n    inputs: [{key:'pat',label:'Regex Pattern',type:'text',defaultValue:'\\\\d+'},{key:'text',label:'Test Text',type:'text',defaultValue:'abc 123 def 456'}],\n    formula: (v) => { try{var re=new RegExp(String(v.pat),'g'); var m=String(v.text).match(re); return [{label:'Matches',value:String(m?m.length:0)},{label:'First',value:m?m[0]:'none'}]; }catch(e){return[{label:'Error',value:'Invalid regex'}];} },\n  },"

F['rsa-key-pair-generator'] = "  'rsa-key-pair-generator': {\n    inputs: [{key:'bits',label:'Key Size',type:'select',options:[{label:'2048-bit',value:'2048'},{label:'4096-bit',value:'4096'}],defaultValue:'2048'}],\n    formula: (v) => { return [{label:'Security',value:v.bits==='4096'?'Very Strong':'Strong'},{label:'Equivalent',value:v.bits==='4096'?'~152-bit symmetric':'~112-bit symmetric'},{label:'Use Case',value:'Testing only. Use ssh-keygen for production.'}]; },\n  },"

F['safelink-decoder'] = "  'safelink-decoder': {\n    inputs: [{key:'url',label:'Short URL',type:'text',defaultValue:'https://bit.ly/abc'}],\n    formula: (v) => { var u=String(v.url); var domain=u.replace(/https?:\\/\\//,'').split('/')[0]; var known=['bit.ly','t.co','tinyurl.com','ow.ly','goo.gl','rebrand.ly']; return [{label:'Domain',value:domain},{label:'Known Shortener',value:known.includes(domain)?'Yes':'Unknown'},{label:'Warning',value:'Always expand before clicking'}]; },\n  },"

F['slugify-string'] = "  'slugify-string': {\n    inputs: [{key:'text',label:'Text',type:'text',defaultValue:'How to Bake Bread: 10 Tips!'}],\n    formula: (v) => { var s=String(v.text).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''); return [{label:'Slug',value:s},{label:'Length',value:s.length+' chars'}]; },\n  },"

F['sql-prettify'] = "  'sql-prettify': {\n    inputs: [{key:'sql',label:'SQL Query',type:'text',defaultValue:'SELECT * FROM users WHERE active=1 ORDER BY name'}],\n    formula: (v) => { var kw=['SELECT','FROM','WHERE','ORDER BY','GROUP BY','HAVING','JOIN','LEFT JOIN','LIMIT','INSERT','UPDATE','DELETE']; var s=String(v.sql); kw.forEach(function(k){s=s.replace(new RegExp('\\\\b'+k+'\\\\b','gi'),'\\n'+k);}); return [{label:'Formatted',value:s.trim()}]; },\n  },"

F['stopwatch'] = "  'stopwatch': {\n    inputs: [],\n    formula: (v) => { return [{label:'Status',value:'Ready — press Start'},{label:'Elapsed',value:'00:00:00.000'},{label:'Laps',value:'0'}]; },\n  },"

F['string-obfuscator'] = "  'string-obfuscator': {\n    inputs: [{key:'text',label:'Text',type:'text',defaultValue:'Hello World'}],\n    formula: (v) => { var t=String(v.text); var rev=t.split('').reverse().join(''); var b64=btoa(t); return [{label:'Reversed',value:rev},{label:'Base64',value:b64}]; },\n  },"

F['svg-placeholder-generator'] = "  'svg-placeholder-generator': {\n    inputs: [{key:'w',label:'Width',type:'number',defaultValue:800},{key:'h',label:'Height',type:'number',defaultValue:600},{key:'bg',label:'Bg Color',type:'text',defaultValue:'#ccc'}],\n    formula: (v) => { var svg='<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"'+v.w+'\" height=\"'+v.h+'\"><rect fill=\"'+v.bg+'\" width=\"100%\" height=\"100%\"/><text x=\"50%\" y=\"50%\" text-anchor=\"middle\" fill=\"#666\" font-size=\"'+Math.min(F(v.w),F(v.h))/10+'\">'+v.w+' x '+v.h+'</text></svg>'; return [{label:'SVG',value:svg},{label:'Data URI',value:'data:image/svg+xml,'+encodeURIComponent(svg)}]; },\n  },"

F['text-diff'] = "  'text-diff': {\n    inputs: [{key:'t1',label:'Original',type:'text',defaultValue:'The quick brown fox'},{key:'t2',label:'Modified',type:'text',defaultValue:'The quick red fox'}],\n    formula: (v) => { var same=String(v.t1)===String(v.t2); var shared=String(v.t1).split('').filter(function(c){return String(v.t2).includes(c)}).length; return [{label:'Identical',value:same?'Yes':'No'},{label:'Length Diff',value:(String(v.t2).length-String(v.t1).length)+' chars'},{label:'Shared Chars',value:String(shared)}]; },\n  },"

F['text-to-binary'] = "  'text-to-binary': {\n    inputs: [{key:'text',label:'Text',type:'text',defaultValue:'Hello'}],\n    formula: (v) => { var bin=String(v.text).split('').map(function(c){return c.charCodeAt(0).toString(2).padStart(8,'0')}).join(' '); return [{label:'Binary',value:bin},{label:'Bytes',value:String(bin.split(' ').length)}]; },\n  },"

F['text-to-nato-alphabet'] = "  'text-to-nato-alphabet': {\n    inputs: [{key:'text',label:'Text',type:'text',defaultValue:'HELLO'}],\n    formula: (v) => { var n={A:'Alpha',B:'Bravo',C:'Charlie',D:'Delta',E:'Echo',F:'Foxtrot',G:'Golf',H:'Hotel',I:'India',J:'Juliett',K:'Kilo',L:'Lima',M:'Mike',N:'November',O:'Oscar',P:'Papa',Q:'Quebec',R:'Romeo',S:'Sierra',T:'Tango',U:'Uniform',V:'Victor',W:'Whiskey',X:'X-ray',Y:'Yankee',Z:'Zulu'}; var r=String(v.text).toUpperCase().split('').map(function(c){return n[c]||c}).join(' '); return [{label:'NATO',value:r}]; },\n  },"

F['text-to-unicode'] = "  'text-to-unicode': {\n    inputs: [{key:'text',label:'Text',type:'text',defaultValue:'ABC'}],\n    formula: (v) => { var u=String(v.text).split('').map(function(c){return 'U+'+c.charCodeAt(0).toString(16).toUpperCase().padStart(4,'0')}).join(' '); return [{label:'Code Points',value:u}]; },\n  },"

F['token-generator'] = "  'token-generator': {\n    inputs: [{key:'len',label:'Length',type:'number',defaultValue:32}],\n    formula: (v) => { var c='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'; var t=''; for(var i=0;i<F(v.len);i++)t+=c[Math.floor(Math.random()*c.length)]; return [{label:'Token',value:t},{label:'Entropy',value:(F(v.len)*Math.log2(62)).toFixed(0)+' bits'}]; },\n  },"

F['toml-to-json'] = "  'toml-to-json': {\n    inputs: [{key:'toml',label:'TOML',type:'text',defaultValue:'name = \"myapp\"'}],\n    formula: (v) => { var lines=String(v.toml).split('\\n').filter(Boolean); var o={}; lines.forEach(function(l){var m=l.match(/^(\\w+)\\s*=\\s*(.+)/); if(m)o[m[1]]=m[2].replace(/[\"']/g,'').trim();}); return [{label:'JSON',value:JSON.stringify(o)}]; },\n  },"

F['toml-to-yaml'] = "  'toml-to-yaml': {\n    inputs: [{key:'toml',label:'TOML',type:'text',defaultValue:'name = \"app\"'}],\n    formula: (v) => { var lines=String(v.toml).split('\\n').filter(Boolean); var y=lines.map(function(l){var m=l.match(/^(\\w+)\\s*=\\s*(.+)/);return m?m[1]+': '+m[2].replace(/[\"']/g,''):l;}).join('\\n'); return [{label:'YAML',value:y}]; },\n  },"

F['ulid-generator'] = "  'ulid-generator': {\n    inputs: [{key:'count',label:'Count',type:'number',defaultValue:1}],\n    formula: (v) => { var a='0123456789ABCDEFGHJKMNPQRSTVWXYZ'; var ul=[]; for(var i=0;i<F(v.count);i++){var s=''; for(var j=0;j<26;j++)s+=a[Math.floor(Math.random()*32)]; ul.push(s);} return [{label:'ULID',value:ul.join('\\n')}]; },\n  },"

F['url-parser'] = "  'url-parser': {\n    inputs: [{key:'url',label:'URL',type:'text',defaultValue:'https://example.com:8080/path?q=search#top'}],\n    formula: (v) => { try{var u=new URL(String(v.url)); return[{label:'Protocol',value:u.protocol},{label:'Host',value:u.hostname},{label:'Port',value:u.port||'default'},{label:'Path',value:u.pathname},{label:'Query',value:u.search||'(none)'},{label:'Hash',value:u.hash||'(none)'}]; }catch(e){return[{label:'Error',value:'Invalid URL'}];} },\n  },"

F['uuid-generator'] = "  'uuid-generator': {\n    inputs: [{key:'count',label:'Count',type:'number',defaultValue:1}],\n    formula: (v) => { var h=function(){return Math.floor(Math.random()*16).toString(16)}; var uu=[]; for(var i=0;i<F(v.count);i++)uu.push(h()+h()+h()+h()+h()+h()+h()+h()+'-'+h()+h()+h()+h()+'-4'+h()+h()+h()+'-'+(8+Math.floor(Math.random()*4)).toString(16)+h()+h()+h()+'-'+h()+h()+h()+h()+h()+h()+h()+h()+h()+h()+h()+h()); return [{label:'UUID v4',value:uu.join('\\n')}]; },\n  },"

F['wheel-spinner'] = "  'wheel-spinner': {\n    inputs: [{key:'items',label:'Items (one per line)',type:'text',defaultValue:'Option 1\\nOption 2\\nOption 3\\nOption 4'}],\n    formula: (v) => { var items=String(v.items).split('\\n').filter(Boolean); var winner=items[Math.floor(Math.random()*items.length)]; return [{label:'Winner!',value:winner},{label:'Options',value:String(items.length)}]; },\n  },"

F['wifi-qr-code-generator'] = "  'wifi-qr-code-generator': {\n    inputs: [{key:'ssid',label:'WiFi Name (SSID)',type:'text',defaultValue:'MyNetwork'},{key:'pass',label:'Password',type:'text',defaultValue:'mypassword'},{key:'sec',label:'Security',type:'select',options:[{label:'WPA2',value:'WPA2'},{label:'WPA3',value:'WPA3'},{label:'WEP',value:'WEP'}],defaultValue:'WPA2'}],\n    formula: (v) => { var qr='WIFI:T:'+v.sec+';S:'+v.ssid+';P:'+v.pass+';;'; return [{label:'QR Content',value:qr},{label:'Status',value:'Scan with phone camera to connect!'}]; },\n  },"

F['xml-formatter'] = "  'xml-formatter': {\n    inputs: [{key:'xml',label:'XML',type:'text',defaultValue:'<root><item id=\"1\">Hello</item></root>'}],\n    formula: (v) => { var x=String(v.xml); var tags=(x.match(/<[^/!?][^>]*>/g)||[]).length; return [{label:'Elements',value:String(tags)},{label:'Size',value:x.length+' chars'}]; },\n  },"

F['xml-to-json'] = "  'xml-to-json': {\n    inputs: [{key:'xml',label:'XML',type:'text',defaultValue:'<root><name>John</name><age>30</age></root>'}],\n    formula: (v) => { var x=String(v.xml); var matches=Array.from(x.matchAll(/<(\\w+)>([^<]*)<\\/\\1>/g)); var o={}; matches.forEach(function(m){var k=m[1],v=m[2]; o[k]=isNaN(Number(v))?v:Number(v);}); return [{label:'JSON',value:JSON.stringify(o)}]; },\n  },"

F['yaml-to-json-converter'] = "  'yaml-to-json-converter': {\n    inputs: [{key:'yaml',label:'YAML',type:'text',defaultValue:'name: app\\nversion: \"1.0\"'}],\n    formula: (v) => { var lines=String(v.yaml).split('\\n').filter(Boolean); var o={}; lines.forEach(function(l){var m=l.match(/^(\\w+):\\s*(.+)/); if(m)o[m[1]]=m[2].replace(/[\"']/g,'');}); return [{label:'JSON',value:JSON.stringify(o)}]; },\n  },"

F['yaml-to-toml'] = "  'yaml-to-toml': {\n    inputs: [{key:'yaml',label:'YAML',type:'text',defaultValue:'name: myapp'}],\n    formula: (v) => { var lines=String(v.yaml).split('\\n').filter(Boolean); var t=lines.map(function(l){var m=l.match(/^(\\w+):\\s*(.+)/);return m?m[1]+' = '+m[2].replace(/[\"']/g,''):l;}).join('\\n'); return [{label:'TOML',value:t}]; },\n  },"

F['yaml-viewer'] = "  'yaml-viewer': {\n    inputs: [{key:'yaml',label:'YAML',type:'text',defaultValue:'server:\\n  host: localhost\\n  port: 8080'}],\n    formula: (v) => { var lines=String(v.yaml).split('\\n').filter(Boolean); var top=lines.filter(function(l){return /^\\w+:/.test(l)&&!l.startsWith(' ')}).length; var nested=lines.filter(function(l){return l.startsWith('  ')}).length; return [{label:'Top-Level Keys',value:String(top)},{label:'Nested Props',value:String(nested)},{label:'Total Lines',value:String(lines.length)}]; },\n  },"

count = 0
for tid, replacement in F.items():
    start = content.find("'"+tid+"': {")
    if start < 0: continue
    depth = 0; end = start
    for i in range(start, len(content)):
        if content[i] == '{': depth += 1
        if content[i] == '}': depth -= 1
        if depth == 0 and content[i] == '}':
            end = i + 1
            if end < len(content) and content[end] == ',': end += 1
            break
    content = content[:start] + replacement + content[end:]
    count += 1

with open("src/app/data/formulas.ts", "w", encoding="utf-8") as f:
    f.write(content)
print(f"Fixed {count} tools")
print(f"input1 remain: {content.count(chr(34)+'input1'+chr(34))}")
