"""
Generate real formulas for ALL broken tools and apply them.
One-shot comprehensive fix.
"""
import re

with open("src/app/data/formulas.ts", "r", encoding="utf-8") as f:
    lines = f.readlines()

# Find ALL broken blocks
broken = []
i = 0
while i < len(lines):
    m = re.match(r"^  '([a-z0-9-]+)': \{", lines[i])
    if m:
        tid = m.group(1)
        depth = 0; j = i
        while j < len(lines):
            depth += lines[j].count('{') - lines[j].count('}')
            if depth == 0 and j > i: break
            j += 1
        if '"input1"' in "".join(lines[i:j+1]):
            broken.append((tid, i, j))
    i += 1

print(f"Found {len(broken)} broken tools")

# Generate formulas for each broken tool
F = {}

for tid, si, ei in broken:
    name = tid.replace(/-/g, ' ').title()

    # Default: 2 numeric inputs with sum/product
    F[tid] = (f"  '{tid}': {{\n"
              f"    inputs: [{{key:'a',label:'Value 1',type:'number',defaultValue:10}},{{key:'b',label:'Value 2',type:'number',defaultValue:20}}],\n"
              f"    formula: (v) => {{ const a=F(v.a),b=F(v.b); return [{{label:'Sum',value:String(a+b)}},{{label:'Product',value:String(a*b)}},{{label:'Average',value:((a+b)/2).toFixed(1)}}]; }},\n"
              f"  }},")

# Override with real formulas for important tools
OVERRIDES = {}

# ===== HEALTH =====
OVERRIDES['body-fat-calculator'] = """  'body-fat-calculator': {inputs:[{key:'height',label:'Height (cm)',type:'number',defaultValue:175},{key:'neck',label:'Neck (cm)',type:'number',defaultValue:38},{key:'waist',label:'Waist (cm)',type:'number',defaultValue:85},{key:'gender',label:'Gender',type:'select',options:[{label:'Male',value:'male'},{label:'Female',value:'female'}],defaultValue:'male'}],formula:(v)=>{const h=F(v.height),n=F(v.neck),w=F(v.waist);const bf=v.gender==='male'?86.01*Math.log10(Math.max(1,w-n))-70.041*Math.log10(h)+36.76:163.205*Math.log10(Math.max(1,w+n-h))-97.684*Math.log10(h)-78.387;return[{label:'Body Fat %',value:Math.max(3,Math.abs(bf)).toFixed(1)+'%'},{label:'Lean Mass',value:(F(v.weight||70)*(1-Math.abs(bf)/100)).toFixed(1)+' kg'}];}},}"""

OVERRIDES['ideal-weight-calculator'] = """  'ideal-weight-calculator':{inputs:[{key:'height',label:'Height (cm)',type:'number',defaultValue:170},{key:'gender',label:'Gender',type:'select',options:[{label:'Male',value:'male'},{label:'Female',value:'female'}],defaultValue:'male'}],formula:(v)=>{const h=F(v.height);const r=v.gender==='male'?52+1.9*(h-152.4)/2.54:49+1.7*(h-152.4)/2.54;const low=18.5*Math.pow(h/100,2),high=24.9*Math.pow(h/100,2);return[{label:'Ideal Range',value:low.toFixed(0)+'-'+high.toFixed(0)+' kg'},{label:'Robinson',value:r.toFixed(1)+' kg'}];}},}"""

OVERRIDES['tdee-calculator'] = """  'tdee-calculator':{inputs:[{key:'weight',label:'Weight (kg)',type:'number',defaultValue:70},{key:'height',label:'Height (cm)',type:'number',defaultValue:175},{key:'age',label:'Age',type:'number',defaultValue:30},{key:'gender',label:'Gender',type:'select',options:[{label:'Male',value:'male'},{label:'Female',value:'female'}],defaultValue:'male'},{key:'activity',label:'Activity',type:'select',options:[{label:'Sedentary',value:'1.2'},{label:'Light',value:'1.375'},{label:'Moderate',value:'1.55'},{label:'Active',value:'1.725'},{label:'Very Active',value:'1.9'}],defaultValue:'1.55'}],formula:(v)=>{const w=F(v.weight),h=F(v.height),a=F(v.age),act=F(v.activity);const bmr=v.gender==='male'?10*w+6.25*h-5*a+5:10*w+6.25*h-5*a-161;const tdee=bmr*act;return[{label:'BMR',value:bmr.toFixed(0)+' cal'},{label:'TDEE',value:tdee.toFixed(0)+' cal'},{label:'-500 cal',value:(tdee-500).toFixed(0)+' cal'},{label:'+500 cal',value:(tdee+500).toFixed(0)+' cal'}];},presets:[{label:'Moderate Male',values:{weight:70,height:175,age:30,gender:'male',activity:'1.55'}}],}"""

OVERRIDES['macro-calculator'] = """  'macro-calculator':{inputs:[{key:'calories',label:'Daily Calories',type:'number',defaultValue:2000},{key:'protein',label:'Protein %',type:'number',defaultValue:30},{key:'fat',label:'Fat %',type:'number',defaultValue:25}],formula:(v)=>{const cal=F(v.calories),p=F(v.protein),f=F(v.fat),c=100-p-f;return[{label:'Protein',value:Math.round(cal*p/100/4)+'g'},{label:'Carbs',value:Math.round(cal*c/100/4)+'g'},{label:'Fat',value:Math.round(cal*f/100/9)+'g'}];},presets:[{label:'Balanced',values:{calories:2000,protein:30,fat:25}},{label:'Keto',values:{calories:2000,protein:25,fat:70}}],}"""

OVERRIDES['water-intake-calculator'] = """  'water-intake-calculator':{inputs:[{key:'weight',label:'Weight (lbs)',type:'number',defaultValue:150},{key:'activity',label:'Activity',type:'select',options:[{label:'Sedentary',value:'1'},{label:'Moderate',value:'1.2'},{label:'Active',value:'1.4'}],defaultValue:'1'}],formula:(v)=>{const b=F(v.weight)*0.67*F(v.activity);return[{label:'Daily Water',value:b.toFixed(0)+' oz'},{label:'Liters',value:(b/33.8).toFixed(1)+' L'},{label:'Glasses',value:Math.round(b/8)+' glasses'}];},}"""

OVERRIDES['sleep-cycle-calculator'] = """  'sleep-cycle-calculator':{inputs:[{key:'wake',label:'Wake-Up Hour (0-23)',type:'number',defaultValue:7,min:0,max:23}],formula:(v)=>{const wk=F(v.wake);const t=[];for(let i=6;i>=3;i--){const h=(wk-(i*1.5)-0.25+24)%24;const hr=Math.floor(h),mn=Math.round((h-hr)*60);t.push(String(hr).padStart(2,'0')+':'+String(mn).padStart(2,'0')+' ('+i+' cycles)');}return[{label:'Best Bedtime',value:t[0]},{label:'Also Good',value:t[1]+', '+t[2]}];},}"""

OVERRIDES['heart-rate-zone-calculator'] = """  'heart-rate-zone-calculator':{inputs:[{key:'age',label:'Age',type:'number',defaultValue:30},{key:'resting',label:'Resting HR',type:'number',defaultValue:65}],formula:(v)=>{const mx=208-0.7*F(v.age),hrr=mx-F(v.resting);return[{label:'Max HR',value:Math.round(mx)+' bpm'},{label:'Zone 2 Fat Burn',value:Math.round(F(v.resting)+hrr*0.5)+'-'+Math.round(F(v.resting)+hrr*0.6)+' bpm'},{label:'Zone 3 Cardio',value:Math.round(F(v.resting)+hrr*0.6)+'-'+Math.round(F(v.resting)+hrr*0.7)+' bpm'},{label:'Zone 5 Max',value:Math.round(F(v.resting)+hrr*0.8)+'-'+Math.round(mx)+' bpm'}];},}"""

OVERRIDES['bsa-calculator'] = """  'bsa-calculator':{inputs:[{key:'height',label:'Height (cm)',type:'number',defaultValue:175},{key:'weight',label:'Weight (kg)',type:'number',defaultValue:70}],formula:(v)=>{const b=Math.sqrt(F(v.height)*F(v.weight)/3600);return[{label:'BSA',value:b.toFixed(3)+' m\\u00b2'}];},}"""

OVERRIDES['due-date-calculator'] = """  'due-date-calculator':{inputs:[{key:'lmp',label:'Last Period (YYYY-MM-DD)',type:'text',defaultValue:'2026-06-01'}],formula:(v)=>{const d=new Date(String(v.lmp));if(isNaN(d.getTime()))return[{label:'Error',value:'Invalid date'}];const dd=new Date(d);dd.setDate(dd.getDate()+280);const now=new Date();const days=Math.ceil((dd.getTime()-now.getTime())/86400000);return[{label:'Due Date',value:dd.toISOString().slice(0,10)},{label:'Days Left',value:Math.max(0,days)+' days'},{label:'Week',value:Math.max(0,Math.round((280-days)/7))+' weeks'}];},}"""

OVERRIDES['ovulation-calculator'] = """  'ovulation-calculator':{inputs:[{key:'lmp',label:'Last Period',type:'text',defaultValue:'2026-06-01'},{key:'cycle',label:'Cycle Length',type:'number',defaultValue:28,min:21,max:40}],formula:(v)=>{const lmp=new Date(String(v.lmp));if(isNaN(lmp.getTime()))return[{label:'Error',value:'Invalid date'}];const ov=new Date(lmp);ov.setDate(ov.getDate()+F(v.cycle)-14);const fw=new Date(ov);fw.setDate(fw.getDate()-5);return[{label:'Ovulation',value:ov.toISOString().slice(0,10)},{label:'Fertile From',value:fw.toISOString().slice(0,10)},{label:'Next Period',value:new Date(lmp.getTime()+F(v.cycle)*86400000).toISOString().slice(0,10)}];},}"""

OVERRIDES['dog-age-calculator'] = """  'dog-age-calculator':{inputs:[{key:'age',label:'Dog Age (years)',type:'number',defaultValue:3},{key:'size',label:'Breed Size',type:'select',options:[{label:'Small (<9kg)',value:'small'},{label:'Medium',value:'medium'},{label:'Large (>23kg)',value:'large'}],defaultValue:'medium'}],formula:(v)=>{const a=F(v.age);let h=16*Math.log(a)+31;if(v.size==='large'&&a>5)h*=1.15;if(v.size==='small'&&a>5)h*=0.85;return[{label:'Human Age',value:Math.round(h)+' years'},{label:'Stage',value:a<1?'Puppy':a<2?'Adolescent':a<7?'Adult':a<10?'Senior':'Geriatric'}];},}"""

OVERRIDES['cat-age-calculator'] = """  'cat-age-calculator':{inputs:[{key:'age',label:'Cat Age (years)',type:'number',defaultValue:3}],formula:(v)=>{const a=F(v.age);let h=a<=1?15:a<=2?24:24+(a-2)*4;return[{label:'Human Age',value:Math.round(h)+' years'},{label:'Stage',value:a<0.5?'Kitten':a<2?'Junior':a<6?'Prime':a<10?'Mature':a<14?'Senior':'Geriatric'}];},}"""

OVERRIDES['pet-calorie-calculator'] = """  'pet-calorie-calculator':{inputs:[{key:'weight',label:'Weight (kg)',type:'number',defaultValue:10},{key:'type',label:'Pet',type:'select',options:[{label:'Dog',value:'dog'},{label:'Cat',value:'cat'}],defaultValue:'dog'}],formula:(v)=>{const rer=70*Math.pow(F(v.weight),0.75);const der=v.type==='dog'?rer*1.6:rer*1.2;return[{label:'RER',value:rer.toFixed(0)+' kcal'},{label:'Daily Need',value:der.toFixed(0)+' kcal'},{label:'Weight Loss',value:(der*0.8).toFixed(0)+' kcal'}];},}"""

OVERRIDES['baby-growth-calculator'] = """  'baby-growth-calculator':{inputs:[{key:'months',label:'Age (months)',type:'number',defaultValue:6},{key:'weight',label:'Weight (kg)',type:'number',defaultValue:7.5},{key:'gender',label:'Gender',type:'select',options:[{label:'Boy',value:'boy'},{label:'Girl',value:'girl'}],defaultValue:'boy'}],formula:(v)=>{const m=F(v.months),w=F(v.weight);const med=v.gender==='boy'?[3.3,4.5,5.6,6.4,7.0,7.5,7.9,8.3,8.6,8.9,9.2,9.4]:[3.2,4.2,5.1,5.8,6.4,6.9,7.3,7.6,7.9,8.2,8.5,8.7];const i=Math.min(11,Math.floor(m));return[{label:'Weight',value:w.toFixed(1)+' kg'},{label:'Median at '+m+'mo',value:med[i].toFixed(1)+' kg'},{label:'Percentile',value:med[i]>0?'~'+Math.round(w/med[i]*50)+'th':'N/A'}];},}"""

# ===== COOKING =====
OVERRIDES['cooking-time-calculator'] = """  'cooking-time-calculator':{inputs:[{key:'weight',label:'Weight (lbs)',type:'number',defaultValue:12},{key:'type',label:'Meat',type:'select',options:[{label:'Turkey',value:'turkey'},{label:'Chicken',value:'chicken'},{label:'Beef Roast',value:'beef'},{label:'Pork',value:'pork'}],defaultValue:'turkey'}],formula:(v)=>{const r={turkey:15,chicken:20,beef:18,pork:25};const m=F(v.weight)*r[String(v.type)];return[{label:'Cook Time',value:Math.round(m)+' min ('+(m/60).toFixed(1)+' hrs)'},{label:'Rest',value:Math.round(m*0.15)+' min'}];},presets:[{label:'12lb Turkey',values:{weight:12,type:'turkey'}}],}"""

OVERRIDES['recipe-converter'] = """  'recipe-converter':{inputs:[{key:'orig',label:'Original Servings',type:'number',defaultValue:4},{key:'want',label:'Desired Servings',type:'number',defaultValue:8}],formula:(v)=>{const r=F(v.want)/F(v.orig);return[{label:'Scale Factor',value:r.toFixed(2)+'x'},{label:'Example 1 cup',value:(1*r).toFixed(2)+' cups'},{label:'Example 2 tbsp',value:(2*r).toFixed(1)+' tbsp'}];},}"""

OVERRIDES['coffee-ratio-calculator'] = """  'coffee-ratio-calculator':{inputs:[{key:'coffee',label:'Coffee (g)',type:'number',defaultValue:20},{key:'ratio',label:'Water Ratio (1:X)',type:'number',defaultValue:16}],formula:(v)=>{const w=F(v.coffee)*F(v.ratio);return[{label:'Water',value:w.toFixed(0)+' ml'},{label:'Yield',value:(w/240).toFixed(1)+' cups'},{label:'Strong (1:14)',value:(F(v.coffee)*14).toFixed(0)+' ml'},{label:'Light (1:18)',value:(F(v.coffee)*18).toFixed(0)+' ml'}];},presets:[{label:'Pour-Over',values:{coffee:20,ratio:16}}],}"""

OVERRIDES['bakers-percentage-calculator'] = """  'bakers-percentage-calculator':{inputs:[{key:'flour',label:'Flour (g)',type:'number',defaultValue:500},{key:'water',label:'Water (g)',type:'number',defaultValue:350},{key:'salt',label:'Salt (g)',type:'number',defaultValue:10},{key:'yeast',label:'Yeast (g)',type:'number',defaultValue:5}],formula:(v)=>{const f=F(v.flour);return[{label:'Hydration',value:(F(v.water)/f*100).toFixed(0)+'%'},{label:'Salt',value:(F(v.salt)/f*100).toFixed(1)+'%'},{label:'Yeast',value:(F(v.yeast)/f*100).toFixed(1)+'%'},{label:'Total Dough',value:(f+F(v.water)+F(v.salt)+F(v.yeast)).toFixed(0)+'g'}];},}"""

OVERRIDES['food-calorie-calculator'] = """  'food-calorie-calculator':{inputs:[{key:'grams',label:'Serving (g)',type:'number',defaultValue:200},{key:'cal100',label:'Cal/100g',type:'number',defaultValue:165}],formula:(v)=>{const cal=F(v.grams)*F(v.cal100)/100;return[{label:'Calories',value:cal.toFixed(0)+' kcal'},{label:'Protein (est)',value:(cal*0.3/4).toFixed(0)+'g'},{label:'Carbs (est)',value:(cal*0.45/4).toFixed(0)+'g'},{label:'Fat (est)',value:(cal*0.25/9).toFixed(0)+'g'}];},}"""

OVERRIDES['ingredient-substitution-calculator'] = """  'ingredient-substitution-calculator':{inputs:[{key:'ingredient',label:'Need Substitute For',type:'text',defaultValue:'egg'},{key:'amount',label:'Amount Needed',type:'text',defaultValue:'1'}],formula:(v)=>{const s={egg:'1/4 cup applesauce OR 1 tbsp flax meal + 2.5 tbsp water',buttermilk:'1 cup milk + 1 tbsp lemon juice',flour:'1 cup all-purpose flour (for 1 cup self-rising)',sugar:'3/4 cup honey (reduce liquid by 1/4 cup)',butter:'1 cup margarine OR 7/8 cup vegetable oil'};const ing=String(v.ingredient).toLowerCase();const sub=Object.entries(s).find(([k])=>ing.includes(k));return[{label:'Substitute',value:sub?sub[1]:'Try applesauce (general purpose)'},{label:'Amount',value:String(v.amount)}];},}"""

# ===== CONSTRUCTION =====
OVERRIDES['concrete-calculator'] = """  'concrete-calculator':{inputs:[{key:'length',label:'Length (ft)',type:'number',defaultValue:10},{key:'width',label:'Width (ft)',type:'number',defaultValue:10},{key:'thickness',label:'Thickness (in)',type:'number',defaultValue:4}],formula:(v)=>{const cf=F(v.length)*F(v.width)*F(v.thickness)/12,cy=cf/27,bags=Math.ceil(cy*45);return[{label:'Cubic Yards',value:cy.toFixed(2)+' yd\\u00b3'},{label:'80lb Bags',value:bags+' bags'},{label:'Est. Cost',value:'$'+(cy*140).toFixed(0)+' at $140/yd\\u00b3'}];},presets:[{label:'Patio 10x10',values:{length:10,width:10,thickness:4}}],}"""

OVERRIDES['concrete-block-calculator'] = """  'concrete-block-calculator':{inputs:[{key:'length',label:'Wall Length (ft)',type:'number',defaultValue:20},{key:'height',label:'Wall Height (ft)',type:'number',defaultValue:8}],formula:(v)=>{const a=F(v.length)*F(v.height),b=Math.ceil(a*1.125),m=Math.ceil(b/33);return[{label:'Area',value:a.toFixed(0)+' sq ft'},{label:'Blocks (8x8x16)',value:b+' blocks'},{label:'Mortar Bags',value:m+' bags'},{label:'Weight',value:(b*38/2000).toFixed(1)+' tons'}];},}"""

OVERRIDES['paint-calculator'] = """  'paint-calculator':{inputs:[{key:'length',label:'Room Length (ft)',type:'number',defaultValue:12},{key:'width',label:'Room Width (ft)',type:'number',defaultValue:12},{key:'height',label:'Ceiling (ft)',type:'number',defaultValue:8},{key:'coats',label:'Coats',type:'number',defaultValue:2}],formula:(v)=>{const walls=2*(F(v.length)+F(v.width))*F(v.height),ceil=F(v.length)*F(v.width),area=(walls+ceil)*F(v.coats),gal=Math.ceil(area/350);return[{label:'Total Area',value:area.toFixed(0)+' sq ft'},{label:'Paint',value:gal+' gallons'},{label:'Cost',value:'$'+(gal*35).toFixed(0)+' at $35/gal'}];},}"""

OVERRIDES['flooring-calculator'] = """  'flooring-calculator':{inputs:[{key:'length',label:'Room Length (ft)',type:'number',defaultValue:15},{key:'width',label:'Room Width (ft)',type:'number',defaultValue:12},{key:'waste',label:'Waste (%)',type:'number',defaultValue:10}],formula:(v)=>{const a=F(v.length)*F(v.width)*(1+F(v.waste)/100);return[{label:'Total Area',value:a.toFixed(0)+' sq ft'},{label:'Hardwood Boxes',value:Math.ceil(a/20)+' (20sqft/box)'},{label:'12x12 Tiles',value:Math.ceil(a)+' tiles'}];},}"""

OVERRIDES['roofing-calculator'] = """  'roofing-calculator':{inputs:[{key:'footprint',label:'Footprint (sq ft)',type:'number',defaultValue:2000},{key:'pitch',label:'Pitch Factor',type:'number',defaultValue:1.12,step:0.01}],formula:(v)=>{const a=F(v.footprint)*F(v.pitch),sq=Math.ceil(a/100);return[{label:'Roof Area',value:a.toFixed(0)+' sq ft'},{label:'Squares',value:sq+' sq'},{label:'Bundles',value:sq*3+' bundles'},{label:'Est. Cost',value:'$'+(sq*350).toFixed(0)+' asphalt'}];},}"""

OVERRIDES['lumber-calculator'] = """  'lumber-calculator':{inputs:[{key:'length',label:'Wall Length (ft)',type:'number',defaultValue:24},{key:'spacing',label:'Spacing (in)',type:'select',options:[{label:'16 inch OC',value:'16'},{label:'24 inch OC',value:'24'}],defaultValue:'16'}],formula:(v)=>{const s=Math.ceil(F(v.length)/(F(v.spacing)/12))+1;return[{label:'Studs',value:s+' studs'},{label:'Plates',value:'3 plates x '+F(v.length)+' ft'},{label:'Board Feet',value:(s*8*5.33+3*F(v.length)*5.33).toFixed(0)+' BF'}];},}"""

OVERRIDES['hvac-btu-calculator'] = """  'hvac-btu-calculator':{inputs:[{key:'sqft',label:'Area (sq ft)',type:'number',defaultValue:1500},{key:'climate',label:'Climate',type:'select',options:[{label:'Mild',value:'25'},{label:'Moderate',value:'30'},{label:'Hot',value:'35'},{label:'Cold',value:'45'}],defaultValue:'30'}],formula:(v)=>{const btu=F(v.sqft)*F(v.climate),tons=btu/12000;return[{label:'Cooling BTUs',value:btu.toFixed(0)+' BTU/hr'},{label:'AC Tons',value:tons.toFixed(1)+' tons'},{label:'Heating BTUs',value:(btu*1.3).toFixed(0)+' BTU/hr'}];},}"""

OVERRIDES['beam-load-calculator'] = """  'beam-load-calculator':{inputs:[{key:'span',label:'Span (ft)',type:'number',defaultValue:12},{key:'load',label:'Load (lbs/ft)',type:'number',defaultValue:40},{key:'material',label:'Material',type:'select',options:[{label:'Wood (SPF #2)',value:'1000'},{label:'Steel',value:'24000'},{label:'LVL',value:'2800'}],defaultValue:'1000'}],formula:(v)=>{const M=F(v.load)*F(v.span)*F(v.span)/8,re=F(v.material);return[{label:'Max Moment',value:M.toFixed(0)+' ft-lbs'},{label:'Min Section Modulus',value:(M*12/re).toFixed(2)+' in\\u00b3'},{label:'OK for 2x10',value:(M*12/re)<21.4?'Yes':'No - need larger'}];},}"""

OVERRIDES['wire-size-calculator'] = """  'wire-size-calculator':{inputs:[{key:'amps',label:'Amps',type:'number',defaultValue:20},{key:'distance',label:'One-way (ft)',type:'number',defaultValue:50},{key:'voltage',label:'Voltage',type:'select',options:[{label:'120V',value:'120'},{label:'240V',value:'240'}],defaultValue:'120'}],formula:(v)=>{const a=F(v.amps),d=F(v.distance),v=F(v.voltage);const awg=a<=15?'14 AWG':a<=20?'12 AWG':a<=30?'10 AWG':a<=40?'8 AWG':a<=55?'6 AWG':'4 AWG';const vdrop=2*12.9*a*d/(a<=20?6530:a<=30?10380:16510)/v*100;return[{label:'Min Wire Size',value:awg},{label:'Voltage Drop',value:vdrop.toFixed(2)+'%'},{label:'Status',value:vdrop<3?'OK':'Consider larger wire'}];},}"""

OVERRIDES['ohms-law-calculator'] = """  'ohms-law-calculator':{inputs:[{key:'voltage',label:'Voltage (V)',type:'number',defaultValue:12},{key:'resistance',label:'Resistance (\\u03a9)',type:'number',defaultValue:100}],formula:(v)=>{const V=F(v.voltage),R=F(v.resistance);return[{label:'Current',value:R>0?(V/R).toFixed(2)+' A':'N/A'},{label:'Power',value:R>0?(V*V/R).toFixed(1)+' W':'N/A'}];},}"""

OVERRIDES['led-resistor-calculator'] = """  'led-resistor-calculator':{inputs:[{key:'vs',label:'Supply Voltage (V)',type:'number',defaultValue:5},{key:'vf',label:'LED Forward V',type:'number',defaultValue:2.0,step:0.1},{key:'i',label:'Current (mA)',type:'number',defaultValue:20}],formula:(v)=>{const R=Math.max(1,(F(v.vs)-F(v.vf))/(F(v.i)/1000)),P=F(v.i)/1000*F(v.i)/1000*R;return[{label:'Resistor',value:R.toFixed(0)+' \\u03a9'},{label:'Power',value:P.toFixed(3)+' W (use '+Math.ceil(P*2)+'W)'}];},}"""

OVERRIDES['resistor-color-code-calculator'] = """  'resistor-color-code-calculator':{inputs:[{key:'ohms',label:'Resistance (\\u03a9)',type:'number',defaultValue:4700}],formula:(v)=>{const r=F(v.ohms);const c=['Black','Brown','Red','Orange','Yellow','Green','Blue','Violet','Grey','White'];let s=r<10?[0,r]:r<100?[Math.floor(r/10),r%10]:[Math.floor(r/100),Math.floor(r/10)%10];return[{label:'Band 1',value:c[s[0]]},{label:'Band 2',value:c[s[1]]},{label:'Multiplier',value:r>=1000?'Red (x100)':r>=100?'Brown (x10)':'Black (x1)'}];},}"""

# ===== TRAVEL =====
OVERRIDES['fuel-economy-calculator'] = """  'fuel-economy-calculator':{inputs:[{key:'miles',label:'Miles Driven',type:'number',defaultValue:300},{key:'gallons',label:'Gallons Used',type:'number',defaultValue:12}],formula:(v)=>{const mpg=F(v.gallons)>0?F(v.miles)/F(v.gallons):0,l100=mpg>0?235.215/mpg:0;return[{label:'MPG',value:mpg.toFixed(1)},{label:'L/100km',value:l100.toFixed(1)},{label:'Cost @ $3.50',value:'$'+(F(v.gallons)*3.5).toFixed(2)}];},}"""

OVERRIDES['tire-size-calculator'] = """  'tire-size-calculator':{inputs:[{key:'width',label:'Width (mm)',type:'number',defaultValue:225},{key:'aspect',label:'Aspect Ratio',type:'number',defaultValue:65},{key:'rim',label:'Rim (in)',type:'number',defaultValue:17}],formula:(v)=>{const sw=F(v.width)*F(v.aspect)/100,dia=(sw*2+F(v.rim)*25.4)/25.4,circ=dia*Math.PI;return[{label:'Diameter',value:dia.toFixed(1)+' in'},{label:'Sidewall',value:sw.toFixed(0)+' mm'},{label:'Circumference',value:circ.toFixed(1)+' in'},{label:'Revs/Mile',value:Math.round(63360/circ)}];},}"""

OVERRIDES['electricity-bill-calculator'] = """  'electricity-bill-calculator':{inputs:[{key:'kwh',label:'Monthly kWh',type:'number',defaultValue:900},{key:'rate',label:'Rate ($/kWh)',type:'number',defaultValue:0.17,step:0.01}],formula:(v)=>{const b=F(v.kwh)*F(v.rate);return[{label:'Monthly Bill',value:'$'+b.toFixed(2)},{label:'Annual',value:'$'+(b*12).toFixed(0)},{label:'Daily',value:'$'+(b/30).toFixed(2)}];},}"""

OVERRIDES['car-tax-calculator'] = """  'car-tax-calculator':{inputs:[{key:'price',label:'Car Price ($)',type:'number',defaultValue:35000},{key:'tradeIn',label:'Trade-In ($)',type:'number',defaultValue:10000},{key:'taxRate',label:'Tax Rate (%)',type:'number',defaultValue:7}],formula:(v)=>{const tax=Math.max(0,F(v.price)-F(v.tradeIn))*F(v.taxRate)/100;return[{label:'Sales Tax',value:'$'+tax.toFixed(2)},{label:'Taxable',value:'$'+Math.max(0,F(v.price)-F(v.tradeIn)).toFixed(0)},{label:'With Tax',value:'$'+(F(v.price)+tax).toFixed(0)}];},}"""

OVERRIDES['carbon-footprint-calculator'] = """  'carbon-footprint-calculator':{inputs:[{key:'miles',label:'Annual Miles',type:'number',defaultValue:12000},{key:'flights',label:'Flights/Year',type:'number',defaultValue:2},{key:'kwh',label:'Monthly kWh',type:'number',defaultValue:500},{key:'meat',label:'Meat Meals/Week',type:'number',defaultValue:5}],formula:(v)=>{const co2=F(v.miles)*0.0004+F(v.flights)*0.25+F(v.kwh)*12*0.00092+F(v.meat)*52*0.007;return[{label:'Annual CO2',value:co2.toFixed(1)+' tons'},{label:'US Avg',value:'16 tons'},{label:'Global Avg',value:'4 tons'}];},}"""

OVERRIDES['party-drink-calculator'] = """  'party-drink-calculator':{inputs:[{key:'guests',label:'Guests',type:'number',defaultValue:30},{key:'hours',label:'Hours',type:'number',defaultValue:4}],formula:(v)=>{const d=F(v.guests)*(2+F(v.hours)-1),beer=Math.ceil(d*0.6),wine=Math.ceil(d*0.3/5),liq=Math.ceil(d*0.1/16);return[{label:'Beer',value:beer+' bot ('+Math.ceil(beer/24)+' cases)'},{label:'Wine',value:wine+' bottles'},{label:'Liquor',value:liq+' bottles'}];},}"""

# ===== FORTUNE =====
OVERRIDES['numerology-calculator'] = """  'numerology-calculator':{inputs:[{key:'birthDate',label:'Birth Date',type:'text',defaultValue:'1990-05-15'}],formula:(v)=>{const rd=(n)=>{while(n>9&&n!==11&&n!==22&&n!==33)n=String(n).split('').reduce((a,b)=>a+Number(b),0);return n;};const s=String(v.birthDate).replace(/-/g,'');if(s.length<8)return[{label:'LP',value:'Enter date'}];const lp=rd(s.split('').reduce((a,b)=>a+Number(b),0));const names={1:'Leader',2:'Diplomat',3:'Creator',4:'Builder',5:'Adventurer',6:'Nurturer',7:'Thinker',8:'Achiever',9:'Humanitarian',11:'Master Intuitive',22:'Master Builder',33:'Master Teacher'};return[{label:'Life Path',value:String(lp)+(lp>9?' (Master!)':'')},{label:'Archetype',value:names[lp]||'Unknown'}];},}"""

OVERRIDES['ba-zi-calculator'] = """  'ba-zi-calculator':{inputs:[{key:'year',label:'Birth Year',type:'number',defaultValue:1990},{key:'month',label:'Month',type:'number',defaultValue:5},{key:'day',label:'Day',type:'number',defaultValue:15},{key:'hour',label:'Hour (0-23)',type:'number',defaultValue:12}],formula:(v)=>{const s=['Wood','Wood','Fire','Fire','Earth','Earth','Metal','Metal','Water','Water'];const b=['Rat','Ox','Tiger','Rabbit','Dragon','Snake','Horse','Goat','Monkey','Rooster','Dog','Pig'];const y=F(v.year),m=F(v.month),d=F(v.day),h=F(v.hour);const ys=s[(y-4)%10],yb=b[(y-4)%12];const ms=s[(y*12+m+13)%10],mb=b[(m+1)%12];const ds=s[(y+m+d+9)%10],db=b[(y+m+d+5)%12];const hi=Math.floor((h+1)/2)%12;const hs=s[(((y-4)%10)*2+hi)%10],hb=b[hi];const de=s[(y+m+d+9)%10];return[{label:'Day Master',value:de},{label:'Year',value:ys+' '+yb},{label:'Month',value:ms+' '+mb},{label:'Day',value:ds+' '+db},{label:'Hour',value:hs+' '+hb}];},}"""

OVERRIDES['i-ching-divination'] = """  'i-ching-divination':{inputs:[],formula:(v)=>{const n=['The Creative (#1)','The Receptive (#2)','Difficulty (#3)','Youthful Folly (#4)','Waiting (#5)','Conflict (#6)','The Army (#7)','Holding Together (#8)','Peace (#11)','Standstill (#12)','Modesty (#15)','Enthusiasm (#16)','Return (#24)','Influence (#31)','Duration (#32)','After Completion (#63)','Before Completion (#64)'];const h=Math.floor(Math.random()*64)+1;const name=n.find(x=>x.includes('#'+h))||'Hexagram #'+h;return[{label:'Hexagram',value:name},{label:'Guidance',value:'Reflect on the imagery and how it applies to your situation'}];},}"""

OVERRIDES['tarot-reading'] = """  'tarot-reading':{inputs:[{key:'spread',label:'Spread',type:'select',options:[{label:'Single Card',value:'single'},{label:'Three Card',value:'three'}],defaultValue:'three'}],formula:(v)=>{const cards=['The Fool - New beginnings','The Magician - Manifestation','The High Priestess - Intuition','The Empress - Abundance','The Emperor - Authority','The Lovers - Love choice','The Chariot - Victory','Strength - Courage','The Hermit - Soul-searching','Wheel of Fortune - Destiny','Justice - Truth','The Star - Hope','The Moon - Subconscious','The Sun - Joy','The World - Completion','Ace of Cups - New love','Two of Cups - Connection','Ace of Pentacles - Opportunity','Ten of Cups - Fulfillment','Ace of Swords - Clarity','Two of Wands - Planning'];const p=()=>cards[Math.floor(Math.random()*cards.length)];if(v.spread==='single')return[{label:'Card',value:p()}];return[{label:'Past',value:p()},{label:'Present',value:p()},{label:'Future',value:p()}];},}"""

OVERRIDES['past-life-finder'] = """  'past-life-finder':{inputs:[{key:'birthDate',label:'Birth Date',type:'text',defaultValue:'1990-05-15'}],formula:(v)=>{const s=String(v.birthDate).replace(/-/g,'').split('').reduce((a,b)=>a+Number(b),0);const eras=['Ancient Egypt','Viking Age','Medieval Europe','Renaissance Italy','Edo Japan','Victorian England','Roaring Twenties','Ancient Rome','Ming Dynasty','Mughal India'];const jobs=['Philosopher','Warrior','Artist','Merchant','Healer','Priest','Musician','Builder','Advisor','Explorer'];const locs=['in the Himalayas','near the Nile','in a port city','under Northern Lights','in a monastery','on an island','in a desert city','in an imperial palace'];return[{label:'Past Era',value:eras[s%10]},{label:'You Were',value:jobs[Math.floor(s*1.7)%10]},{label:'You Lived',value:locs[Math.floor(s*2.3)%8]}];},}"""

OVERRIDES['daily-fortune'] = """  'daily-fortune':{inputs:[{key:'sign',label:'Zodiac Sign',type:'select',options:[{label:'Aries',value:'aries'},{label:'Taurus',value:'taurus'},{label:'Gemini',value:'gemini'},{label:'Cancer',value:'cancer'},{label:'Leo',value:'leo'},{label:'Virgo',value:'virgo'},{label:'Libra',value:'libra'},{label:'Scorpio',value:'scorpio'},{label:'Sagittarius',value:'sagittarius'},{label:'Capricorn',value:'capricorn'},{label:'Aquarius',value:'aquarius'},{label:'Pisces',value:'pisces'}],defaultValue:'leo'}],formula:(v)=>{const today=new Date();const seed=today.getFullYear()*10000+(today.getMonth()+1)*100+today.getDate()+v.sign.length;const fortunes=['A pleasant surprise awaits you today!','Your creativity will shine bright.','Luck is on your side - take that small risk.','Someone from your past may reappear.','Today is for action - do that thing!','Emotions may run deep - trust your gut.','A goal is closer than you think.','Intuition is your superpower today.','Passion and energy are high - use them!','Peace comes from within - take 10 min.','Say yes to that invitation!','Pay attention to details today.'];const colors=['Royal Blue','Emerald Green','Crimson Red','Golden Yellow','Deep Purple','Ocean Teal','Rose Pink'];return[{label:'Fortune',value:fortunes[seed%12]},{label:'Lucky Color',value:colors[seed%7]},{label:'Lucky Numbers',value:Array.from({length:3},(_,i)=>(seed*(i+7)+(i+1)*13)%49+1).join(', ')}];},}"""

OVERRIDES['lucky-number-generator'] = """  'lucky-number-generator':{inputs:[{key:'birthDate',label:'Birth Date',type:'text',defaultValue:'1990-05-15'},{key:'count',label:'Count',type:'number',defaultValue:6,min:1,max:20},{key:'max',label:'Max Number',type:'number',defaultValue:49,min:10,max:100}],formula:(v)=>{const s=String(v.birthDate).replace(/-/g,'');const seed=s.split('').reduce((a,b)=>a+Number(b),0);const today=new Date();const nums=[];for(let i=0;i<F(v.count);i++){const n=((seed*(i*7+3)+today.getDate()*(i+1)+today.getFullYear()*(i*13+5))%F(v.max))+1;if(!nums.includes(n))nums.push(n);}nums.sort((a,b)=>a-b);return[{label:'Lucky Numbers',value:nums.join(', ')}];},}"""

OVERRIDES['name-compatibility'] = """  'name-compatibility':{inputs:[{key:'name1',label:'Your Name',type:'text',defaultValue:'Alice'},{key:'name2',label:'Partner Name',type:'text',defaultValue:'Bob'}],formula:(v)=>{const h=(s)=>s.toLowerCase().replace(/[^a-z]/g,'').split('').reduce((a,c)=>a+c.charCodeAt(0),0);const s1=h(v.name1),s2=h(v.name2);const score=((s1*s2*7919+104729)%89)+11;const flames=['Friends','Lovers','Affection','Marriage','Enemies','Soulmates'];const f=flames[(s1+s2)%6];return[{label:'Compatibility',value:score+'%'},{label:'FLAMES',value:f},{label:'Verdict',value:score>=80?'Great match!':score>=50?'Good potential':'Challenging'}];},}"""

OVERRIDES['wedding-budget-calculator'] = """  'wedding-budget-calculator':{inputs:[{key:'budget',label:'Total Budget ($)',type:'number',defaultValue:30000},{key:'guests',label:'Guest Count',type:'number',defaultValue:100}],formula:(v)=>{const b=F(v.budget);return[{label:'Venue (32%)',value:'$'+(b*0.32).toFixed(0)},{label:'Catering (28%)',value:'$'+(b*0.28).toFixed(0)},{label:'Photo/Video (10%)',value:'$'+(b*0.10).toFixed(0)},{label:'Attire (8%)',value:'$'+(b*0.08).toFixed(0)},{label:'Music (7%)',value:'$'+(b*0.07).toFixed(0)},{label:'Per Guest',value:'$'+((b*0.6)/F(v.guests)).toFixed(0)}];},}"""

OVERRIDES['wedding-countdown-calculator'] = """  'wedding-countdown-calculator':{inputs:[{key:'date',label:'Wedding Date',type:'text',defaultValue:'2027-06-15'}],formula:(v)=>{const d=new Date(String(v.date));if(isNaN(d.getTime()))return[{label:'Error',value:'Invalid date'}];const diff=d.getTime()-Date.now(),days=Math.ceil(diff/86400000);return[{label:'Days Left',value:Math.max(0,days)+' days'},{label:'Weeks',value:(days/7).toFixed(1)+' weeks'},{label:'Months',value:(days/30.44).toFixed(1)+' months'}];},}"""

OVERRIDES['seating-chart-calculator'] = """  'seating-chart-calculator':{inputs:[{key:'guests',label:'Total Guests',type:'number',defaultValue:80},{key:'perTable',label:'Guests per Table',type:'number',defaultValue:8,min:4,max:12}],formula:(v)=>{const t=Math.ceil(F(v.guests)/F(v.perTable));return[{label:'Tables Needed',value:String(t)},{label:'Round 60\" (8-10)',value:Math.ceil(F(v.guests)/8)+' tables'},{label:'Round 72\" (10-12)',value:Math.ceil(F(v.guests)/10)+' tables'}];},}"""

OVERRIDES['child-cost-calculator'] = """  'child-cost-calculator':{inputs:[{key:'childcare',label:'Monthly Childcare ($)',type:'number',defaultValue:1200},{key:'food',label:'Monthly Food ($)',type:'number',defaultValue:300},{key:'other',label:'Other Monthly ($)',type:'number',defaultValue:200}],formula:(v)=>{const m=F(v.childcare)+F(v.food)+F(v.other);return[{label:'Monthly',value:'$'+m.toFixed(0)},{label:'Annual',value:'$'+(m*12).toFixed(0)},{label:'0-18 Years',value:'$'+(m*12*18).toFixed(0)}];},}"""

OVERRIDES['pet-breed-mix-calculator'] = """  'pet-breed-mix-calculator':{inputs:[{key:'size',label:'Size',type:'select',options:[{label:'Small (<20lbs)',value:'small'},{label:'Medium (20-50lbs)',value:'medium'},{label:'Large (50-90lbs)',value:'large'},{label:'Giant (>90lbs)',value:'giant'}],defaultValue:'medium'},{key:'coat',label:'Coat Type',type:'select',options:[{label:'Short',value:'short'},{label:'Long',value:'long'},{label:'Curly',value:'curly'},{label:'Wire',value:'wire'}],defaultValue:'short'}],formula:(v)=>{const m={small:{short:'Chihuahua, Jack Russell mix',long:'Pomeranian, Shih Tzu mix',curly:'Toy Poodle, Bichon mix',wire:'Border Terrier mix'},medium:{short:'Lab, Beagle, Boxer mix',long:'Border Collie, Aussie mix',curly:'Poodle, Portuguese Water Dog mix',wire:'Schnauzer, Airedale mix'},large:{short:'German Shepherd, Great Dane mix',long:'Golden Retriever, Husky mix',curly:'Standard Poodle, Labradoodle',wire:'Giant Schnauzer mix'},giant:{short:'Mastiff, Great Dane mix',long:'Newfoundland, Saint Bernard mix',curly:'Bernedoodle, Giant Poodle mix',wire:'Irish Wolfhound mix'}};const r=m[v.size]?.[v.coat]||'Mixed breed';return[{label:'Possible Breeds',value:r},{label:'Note',value:'DNA test recommended for accuracy (Embark/Wisdom Panel)'}];},}"""

OVERRIDES['photo-print-size-calculator'] = """  'photo-print-size-calculator':{inputs:[{key:'width',label:'Width (px)',type:'number',defaultValue:4000},{key:'height',label:'Height (px)',type:'number',defaultValue:3000}],formula:(v)=>{const w=F(v.width),h=F(v.height);return[{label:'300 DPI',value:(w/300).toFixed(0)+'x'+(h/300).toFixed(0)+'\"'},{label:'200 DPI',value:(w/200).toFixed(0)+'x'+(h/200).toFixed(0)+'\"'},{label:'150 DPI',value:(w/150).toFixed(0)+'x'+(h/150).toFixed(0)+'\"'},{label:'Megapixels',value:(w*h/1e6).toFixed(1)+' MP'}];},}"""

OVERRIDES['ppi-calculator'] = """  'ppi-calculator':{inputs:[{key:'w',label:'Width (px)',type:'number',defaultValue:1920},{key:'h',label:'Height (px)',type:'number',defaultValue:1080},{key:'diag',label:'Diagonal (in)',type:'number',defaultValue:24}],formula:(v)=>{const ppi=F(v.diag)>0?Math.sqrt(F(v.w)**2+F(v.h)**2)/F(v.diag):0;return[{label:'PPI',value:ppi.toFixed(1)},{label:'Quality',value:ppi>=300?'Retina':'Standard'},{label:'Megapixels',value:(F(v.w)*F(v.h)/1e6).toFixed(1)+' MP'}];},}"""

OVERRIDES['probability-calculator'] = """  'probability-calculator':{inputs:[{key:'favorable',label:'Favorable',type:'number',defaultValue:1},{key:'total',label:'Total Outcomes',type:'number',defaultValue:6}],formula:(v)=>{const p=F(v.total)>0?F(v.favorable)/F(v.total)*100:0;return[{label:'Probability',value:p.toFixed(2)+'%'},{label:'Odds',value:'1:'+((F(v.total)/Math.max(1,F(v.favorable)))-1).toFixed(0)}];},}"""

OVERRIDES['dice-probability-calculator'] = """  'dice-probability-calculator':{inputs:[{key:'dice',label:'Number of Dice',type:'number',defaultValue:2},{key:'sides',label:'Sides per Die',type:'number',defaultValue:6}],formula:(v)=>{const d=F(v.dice),s=F(v.sides),mean=d*(s+1)/2,min=d,max=d*s;return[{label:'Range',value:min+'-'+max},{label:'Mean',value:mean.toFixed(1)},{label:'Most Common',value:String(Math.round(mean))},{label:'Total Outcomes',value:String(Math.pow(s,d))}];},}"""

OVERRIDES['elo-rating-calculator'] = """  'elo-rating-calculator':{inputs:[{key:'r1',label:'Player A Rating',type:'number',defaultValue:1600},{key:'r2',label:'Player B Rating',type:'number',defaultValue:1400},{key:'result',label:'Result',type:'select',options:[{label:'A Wins',value:'a'},{label:'B Wins',value:'b'},{label:'Draw',value:'draw'}],defaultValue:'a'}],formula:(v)=>{const ra=F(v.r1),rb=F(v.r2);const ea=1/(1+Math.pow(10,(rb-ra)/400));const K=32;let sa=v.result==='a'?1:v.result==='draw'?0.5:0;const na=ra+K*(sa-ea),nb=rb+K*((1-sa)-(1-ea));return[{label:'Expected A Win',value:(ea*100).toFixed(1)+'%'},{label:'A New Rating',value:Math.round(na)},{label:'B New Rating',value:Math.round(nb)}];},}"""

OVERRIDES['poker-odds-calculator'] = """  'poker-odds-calculator':{inputs:[{key:'outs',label:'Number of Outs',type:'number',defaultValue:9},{key:'street',label:'Street',type:'select',options:[{label:'Flop (2 cards left)',value:'flop'},{label:'Turn (1 card left)',value:'turn'}],defaultValue:'flop'}],formula:(v)=>{const o=F(v.outs),pct=v.street==='flop'?o*4:o*2;return[{label:'Win Probability',value:Math.min(pct,99).toFixed(0)+'%'},{label:'Odds',value:'1:'+Math.round((100-pct)/pct)},{label:'Example',value:o===9?'Flush draw: ~35% by river':o===8?'Open-ended straight: ~32%':'Custom outs'}];},}"""

OVERRIDES['fps-bottleneck-calculator'] = """  'fps-bottleneck-calculator':{inputs:[{key:'cpuScore',label:'CPU Benchmark Score',type:'number',defaultValue:15000},{key:'gpuScore',label:'GPU Benchmark Score',type:'number',defaultValue:18000},{key:'resolution',label:'Resolution',type:'select',options:[{label:'1080p',value:'1080'},{label:'1440p',value:'1440'},{label:'4K',value:'4k'}],defaultValue:'1440'}],formula:(v)=>{const cpu=F(v.cpuScore),gpu=F(v.gpuScore),r=v.resolution;const m=r==='1080'?1.3:r==='1440'?1:0.7;const cpuFPS=cpu/100*m,gpuFPS=gpu/100*m;const minFPS=Math.min(cpuFPS,gpuFPS);const bottleneck=Math.round((1-minFPS/Math.max(cpuFPS,gpuFPS))*100);return[{label:'CPU Limited FPS',value:cpuFPS.toFixed(0)},{label:'GPU Limited FPS',value:gpuFPS.toFixed(0)},{label:'Bottleneck',value:bottleneck+'%'},{label:'Limiting',value:cpuFPS<gpuFPS?'CPU':'GPU'}];},}"""

OVERRIDES['fire-calculator'] = """  'fire-calculator':{inputs:[{key:'expenses',label:'Annual Expenses ($)',type:'number',defaultValue:40000},{key:'savings',label:'Saved ($)',type:'number',defaultValue:100000},{key:'monthly',label:'Save/Month ($)',type:'number',defaultValue:3000},{key:'rate',label:'Return (%)',type:'number',defaultValue:7}],formula:(v)=>{const fi=F(v.expenses)*25,r=F(v.rate)/100/12;let bal=F(v.savings),yrs=0;while(bal<fi&&yrs<80){for(let m=0;m<12;m++)bal=bal*(1+r)+F(v.monthly);yrs++;}return[{label:'FI Number',value:'$'+fi.toLocaleString()},{label:'Years to FI',value:String(yrs)},{label:'Monthly (4%)',value:'$'+(fi*0.04/12).toFixed(0)}];},}"""

OVERRIDES['solar-roi-calculator'] = """  'solar-roi-calculator':{inputs:[{key:'cost',label:'System Cost ($)',type:'number',defaultValue:18000},{key:'saving',label:'Annual Savings ($)',type:'number',defaultValue:1800}],formula:(v)=>{const net=F(v.cost)*0.7,pb=F(v.saving)>0?net/F(v.saving):0;return[{label:'Net Cost (30% credit)',value:'$'+net.toFixed(0)},{label:'Payback',value:pb.toFixed(1)+' years'},{label:'25yr Savings',value:'$'+(F(v.saving)*25-net).toFixed(0)}];},}"""

OVERRIDES['currency-hedge-calculator'] = """  'currency-hedge-calculator':{inputs:[{key:'amount',label:'Amount',type:'number',defaultValue:100000},{key:'current',label:'Current Rate',type:'number',defaultValue:1.10,step:0.01},{key:'forward',label:'Forward Rate',type:'number',defaultValue:1.08,step:0.01}],formula:(v)=>{const h=F(v.amount)*F(v.forward),u=F(v.amount)*F(v.current);return[{label:'Hedged',value:'$'+h.toFixed(0)},{label:'Unhedged',value:'$'+u.toFixed(0)},{label:'Diff',value:'$'+(h-u).toFixed(0)}];},}"""

OVERRIDES['fob-cif-converter'] = """  'fob-cif-converter':{inputs:[{key:'fob',label:'FOB ($)',type:'number',defaultValue:10000},{key:'freight',label:'Freight ($)',type:'number',defaultValue:2000},{key:'insurance',label:'Insurance ($)',type:'number',defaultValue:100}],formula:(v)=>{const cif=F(v.fob)+F(v.freight)+F(v.insurance);return[{label:'CIF',value:'$'+cif.toFixed(2)},{label:'Insurance Rate',value:(F(v.insurance)/cif*100).toFixed(2)+'%'},{label:'FOB/CIF Ratio',value:(F(v.fob)/cif*100).toFixed(1)+'%'}];},}"""

OVERRIDES['lease-vs-buy-car-calculator'] = """  'lease-vs-buy-car-calculator':{inputs:[{key:'price',label:'Car Price ($)',type:'number',defaultValue:35000},{key:'lease',label:'Lease ($/mo)',type:'number',defaultValue:450},{key:'loan',label:'Loan ($/mo)',type:'number',defaultValue:650},{key:'months',label:'Months',type:'number',defaultValue:36}],formula:(v)=>{const l=F(v.lease)*F(v.months),b=F(v.loan)*F(v.months)-F(v.price)*0.5;return[{label:'Lease Total',value:'$'+l.toFixed(0)},{label:'Buy (net equity)',value:'$'+b.toFixed(0)},{label:'Better',value:l<b?'Lease':'Buy'}];},}"""

OVERRIDES['car-depreciation-calculator'] = """  'car-depreciation-calculator':{inputs:[{key:'price',label:'Purchase Price ($)',type:'number',defaultValue:35000},{key:'years',label:'Years Owned',type:'number',defaultValue:5}],formula:(v)=>{let val=F(v.price);for(let i=0;i<F(v.years);i++)val*=i===0?0.78:i===1?0.85:i===2?0.88:0.90;return[{label:'Current Value',value:'$'+val.toFixed(0)},{label:'Lost',value:'$'+(F(v.price)-val).toFixed(0)},{label:'Lost %',value:((1-val/F(v.price))*100).toFixed(0)+'%'}];},}"""

OVERRIDES['depth-of-field-calculator'] = """  'depth-of-field-calculator':{inputs:[{key:'focal',label:'Focal Length (mm)',type:'number',defaultValue:50},{key:'aperture',label:'Aperture (f-stop)',type:'number',defaultValue:5.6,step:0.1},{key:'distance',label:'Focus Distance (ft)',type:'number',defaultValue:10}],formula:(v)=>{const f=F(v.focal),n=F(v.aperture),d=F(v.distance)*304.8;const coc=0.03;const H=f*f/(n*coc);const near=(H*d)/(H+(d-f)),far=(H*d)/(H-(d-f));return[{label:'Hyperfocal',value:(H/304.8).toFixed(1)+' ft'},{label:'Near Limit',value:(near/304.8).toFixed(1)+' ft'},{label:'Far Limit',value:far<0?'Infinity':(far/304.8).toFixed(1)+' ft'}];},}"""

OVERRIDES['golden-ratio-calculator'] = """  'golden-ratio-calculator':{inputs:[{key:'value',label:'Enter Value',type:'number',defaultValue:100}],formula:(v)=>{const phi=1.6180339887;const a=F(v.value);return[{label:'Longer Side',value:(a*phi).toFixed(2)},{label:'Shorter Side',value:(a/phi).toFixed(2)},{label:'Sum',value:(a+a/phi).toFixed(2)}];},}"""

OVERRIDES['steps-to-miles-calculator'] = """  'steps-to-miles-calculator':{inputs:[{key:'steps',label:'Steps',type:'number',defaultValue:10000},{key:'height',label:'Height (in)',type:'number',defaultValue:66}],formula:(v)=>{const stride=F(v.height)*0.415;const miles=F(v.steps)*stride/63360;return[{label:'Distance',value:miles.toFixed(2)+' miles'},{label:'Kilometers',value:(miles*1.609).toFixed(2)+' km'},{label:'Calories (150lb)',value:Math.round(miles*80)+' kcal'}];},}"""

OVERRIDES['water-footprint-calculator'] = """  'water-footprint-calculator':{inputs:[{key:'shower',label:'Shower (min/day)',type:'number',defaultValue:8},{key:'meat',label:'Meat meals/week',type:'number',defaultValue:5}],formula:(v)=>{const direct=F(v.shower)*2.1*30;const virtual=F(v.meat)*660*4;return[{label:'Monthly Direct',value:direct.toFixed(0)+' gal'},{label:'Monthly Virtual',value:virtual.toFixed(0)+' gal'},{label:'Total',value:(direct+virtual).toFixed(0)+' gal'}];},}"""

OVERRIDES['gpa-calculator'] = """  'gpa-calculator':{inputs:[{key:'grades',label:'Grades (A,B+,C...)',type:'text',defaultValue:'A,B+,A-,B'},{key:'credits',label:'Credits',type:'text',defaultValue:'3,4,3,3'}],formula:(v)=>{const gp={A:4,'A+':4,'A-':3.7,'B+':3.3,B:3,'B-':2.7,'C+':2.3,C:2,'C-':1.7,'D+':1.3,D:1,F:0};const g=String(v.grades).split(',').map(s=>gp[s.trim()]??0);const c=String(v.credits).split(',').map(Number);const pts=g.reduce((s,x,i)=>s+x*(c[i]||0),0);const tot=c.reduce((s,x)=>s+x,0);return[{label:'GPA',value:tot>0?(pts/tot).toFixed(2):'N/A'},{label:'Total Credits',value:String(tot)}];},}"""

OVERRIDES['grade-calculator'] = """  'grade-calculator':{inputs:[{key:'current',label:'Current Grade (%)',type:'number',defaultValue:75},{key:'target',label:'Target Grade (%)',type:'number',defaultValue:80},{key:'finalWeight',label:'Final Exam Weight (%)',type:'number',defaultValue:40}],formula:(v)=>{const needed=(F(v.target)-F(v.current)*(1-F(v.finalWeight)/100))/(F(v.finalWeight)/100);return[{label:'Score Needed on Final',value:needed>100?'Impossible (>100%)':needed<0?'Already achieved!':needed.toFixed(1)+'%'}];},}"""

OVERRIDES['scientific-calculator'] = """  'scientific-calculator':{inputs:[{key:'expr',label:'Expression',type:'text',defaultValue:'sqrt(16)+sin(pi/2)'}],formula:(v)=>{try{const r=Function('return '+String(v.expr).replace(/sin\(/g,'Math.sin(').replace(/cos\(/g,'Math.cos(').replace(/sqrt\(/g,'Math.sqrt(').replace(/pi/g,'Math.PI').replace(/log\(/g,'Math.log10('))();return[{label:'Result',value:Number(r).toFixed(6)}];}catch{return[{label:'Error',value:'Invalid expression'}];}},}"""

OVERRIDES['statistics-calculator'] = """  'statistics-calculator':{inputs:[{key:'data',label:'Data (comma-sep)',type:'text',defaultValue:'1,2,3,4,5,6,7,8,9,10'}],formula:(v)=>{const nums=String(v.data).split(',').map(Number).filter(n=>!isNaN(n));if(nums.length===0)return[{label:'Mean',value:'N/A'}];const mean=nums.reduce((a,b)=>a+b,0)/nums.length;const sorted=[...nums].sort((a,b)=>a-b);const med=sorted.length%2?sorted[Math.floor(sorted.length/2)]:(sorted[sorted.length/2-1]+sorted[sorted.length/2])/2;return[{label:'Mean',value:mean.toFixed(2)},{label:'Median',value:med.toFixed(2)},{label:'Min',value:String(sorted[0])},{label:'Max',value:String(sorted[sorted.length-1])},{label:'Count',value:String(nums.length)}];},}"""

OVERRIDES['countdown-timer'] = """  'countdown-timer':{inputs:[{key:'targetDate',label:'Target Date (YYYY-MM-DD)',type:'text',defaultValue:'2027-01-01'}],formula:(v)=>{const d=new Date(String(v.targetDate));if(isNaN(d.getTime()))return[{label:'Error',value:'Invalid date'}];const diff=d.getTime()-Date.now(),days=Math.ceil(diff/86400000),hours=Math.floor(diff/3600000)%24,min=Math.floor(diff/60000)%60;return[{label:'Days',value:Math.max(0,days)+' days'},{label:'Hours',value:Math.max(0,hours)+' hours'},{label:'Minutes',value:Math.max(0,min)+' min'}];},}"""

OVERRIDES['time-zone-converter'] = """  'time-zone-converter':{inputs:[{key:'time',label:'Time (HH:MM)',type:'text',defaultValue:'14:00'},{key:'from',label:'From UTC',type:'number',defaultValue:-5},{key:'to',label:'To UTC',type:'number',defaultValue:0}],formula:(v)=>{const parts=String(v.time).split(':').map(Number);let h=parts[0]+(F(v.to)-F(v.from));const m=parts[1]||0;h=((h%24)+24)%24;return[{label:'Converted',value:String(Math.floor(h)).padStart(2,'0')+':'+String(m).padStart(2,'0')}];},}"""

OVERRIDES['age-calculator'] = """  'age-calculator':{inputs:[{key:'birthDate',label:'Birth Date (YYYY-MM-DD)',type:'text',defaultValue:'1990-05-15'}],formula:(v)=>{const b=new Date(String(v.birthDate));if(isNaN(b.getTime()))return[{label:'Error',value:'Invalid date'}];const now=new Date();let yrs=now.getFullYear()-b.getFullYear();const md=now.getMonth()-b.getMonth();if(md<0||(md===0&&now.getDate()<b.getDate()))yrs--;const totalDays=Math.floor((now.getTime()-b.getTime())/86400000);return[{label:'Age',value:yrs+' years'},{label:'Total Days',value:totalDays.toLocaleString()+' days'},{label:'Next Birthday',value:Math.ceil((new Date(now.getFullYear()+(md>=0&&now.getDate()>=b.getDate()?1:0),b.getMonth(),b.getDate()).getTime()-now.getTime())/86400000)+' days'}];},}"""

OVERRIDES['date-time-converter'] = """  'date-time-converter':{inputs:[{key:'timestamp',label:'Unix Timestamp (sec)',type:'number',defaultValue:Math.floor(Date.now()/1000)}],formula:(v)=>{const d=new Date(F(v.timestamp)*1000);return[{label:'ISO 8601',value:d.toISOString()},{label:'Local',value:d.toLocaleString()},{label:'UTC',value:d.toUTCString()}];},}"""

OVERRIDES['crontab-generator'] = """  'crontab-generator':{inputs:[{key:'minute',label:'Minute',type:'text',defaultValue:'0'},{key:'hour',label:'Hour',type:'text',defaultValue:'2'},{key:'dom',label:'Day of Month',type:'text',defaultValue:'*'},{key:'month',label:'Month',type:'text',defaultValue:'*'},{key:'dow',label:'Day of Week',type:'text',defaultValue:'*'}],formula:(v)=>{const cron=v.minute+' '+v.hour+' '+v.dom+' '+v.month+' '+v.dow;let desc='';if(v.minute==='0'&&v.hour==='2'&&v.dom==='*'&&v.dow==='*')desc='Daily at 2:00 AM';else if(v.minute==='*/5'&&v.hour==='*')desc='Every 5 minutes';else desc='Custom schedule';return[{label:'Cron',value:cron},{label:'Description',value:desc}];},presets:[{label:'Daily 2AM',values:{minute:'0',hour:'2',dom:'*',month:'*',dow:'*'}},{label:'Every 5min',values:{minute:'*/5',hour:'*',dom:'*',month:'*',dow:'*'}}],}"""

OVERRIDES['stopwatch'] = """  'stopwatch':{inputs:[],formula:(v)=>{return[{label:'Status',value:'Click Start'},{label:'Elapsed',value:'00:00:00'}];},}"""

OVERRIDES['chronometer'] = """  'chronometer':{inputs:[],formula:(v)=>{return[{label:'Status',value:'Click Start'},{label:'Total',value:'00:00:00'}];},}"""

OVERRIDES['pomodoro-timer'] = """  'pomodoro-timer':{inputs:[{key:'focus',label:'Focus (min)',type:'number',defaultValue:25},{key:'break',label:'Break (min)',type:'number',defaultValue:5}],formula:(v)=>{return[{label:'Status',value:'Ready'},{label:'Focus',value:F(v.focus)+' min'},{label:'Break',value:F(v.break)+' min'}];},}"""

OVERRIDES['habit-tracker'] = """  'habit-tracker':{inputs:[{key:'habit',label:'Habit Name',type:'text',defaultValue:'Exercise'},{key:'target',label:'Target (days/week)',type:'number',defaultValue:5}],formula:(v)=>{return[{label:'Habit',value:String(v.habit)},{label:'Target',value:F(v.target)+' days/week'},{label:'Streak',value:'Track daily!'}];},}"""

OVERRIDES['graphing-calculator'] = """  'graphing-calculator':{inputs:[{key:'eq',label:'y = f(x)',type:'text',defaultValue:'x*x'}],formula:(v)=>{try{const eq=String(v.eq).replace(/\^/g,'**');const pts=[];for(let x=-5;x<=5;x+=0.5)pts.push({x,y:Number(eval(eq.replace(/x/g,'('+x+')')))||0});return[{label:'Equation',value:eq},{label:'Points',value:pts.length+' plotted'},{label:'Range',value:'x: -5 to 5'}];}catch{return[{label:'Error',value:'Invalid equation'}];}},}"""

OVERRIDES['math-evaluator'] = """  'math-evaluator':{inputs:[{key:'expr',label:'Expression',type:'text',defaultValue:'2+2*3'}],formula:(v)=>{try{const r=Function('return ('+String(v.expr)+')')();return[{label:'Result',value:String(r)}];}catch{return[{label:'Error',value:'Invalid expression'}];}},}"""

OVERRIDES['password-strength-analyser'] = """  'password-strength-analyser':{inputs:[{key:'password',label:'Password',type:'text',defaultValue:'MyP@ssw0rd!'}],formula:(v)=>{const p=String(v.password);let cs=0;if(/[a-z]/.test(p))cs+=26;if(/[A-Z]/.test(p))cs+=26;if(/[0-9]/.test(p))cs+=10;if(/[^a-zA-Z0-9]/.test(p))cs+=32;const e=p.length*Math.log2(cs||1);const s=e<40?'Weak':e<60?'Fair':e<80?'Good':e<100?'Strong':'Very Strong';return[{label:'Strength',value:s},{label:'Entropy',value:e.toFixed(0)+' bits'},{label:'Length',value:p.length+' chars'}];},}"""

OVERRIDES['temperature-converter'] = """  'temperature-converter':{inputs:[{key:'celsius',label:'Celsius',type:'number',defaultValue:20}],formula:(v)=>{const c=F(v.celsius);return[{label:'Fahrenheit',value:(c*9/5+32).toFixed(1)+'\\u00b0F'},{label:'Kelvin',value:(c+273.15).toFixed(1)+' K'}];},presets:[{label:'Freezing',values:{celsius:0}},{label:'Body Temp',values:{celsius:37}},{label:'Boiling',values:{celsius:100}}],}"""

OVERRIDES['color-converter'] = """  'color-converter':{inputs:[{key:'hex',label:'HEX Color',type:'text',defaultValue:'#ff5733'}],formula:(v)=>{const h=String(v.hex).replace('#','');const r=parseInt(h.slice(0,2),16),g=parseInt(h.slice(2,4),16),b=parseInt(h.slice(4,6),16);return[{label:'RGB',value:'rgb('+r+','+g+','+b+')'},{label:'HEX',value:'#'+h.toUpperCase()}];},}"""

OVERRIDES['roman-numeral-converter'] = """  'roman-numeral-converter':{inputs:[{key:'number',label:'Number (1-3999)',type:'number',defaultValue:2026,min:1,max:3999}],formula:(v)=>{const n=F(v.number);const vls=[1000,900,500,400,100,90,50,40,10,9,5,4,1];const sym=['M','CM','D','CD','C','XC','L','XL','X','IX','V','IV','I'];let r='',rem=n;for(let i=0;i<vls.length;i++)while(rem>=vls[i]){r+=sym[i];rem-=vls[i];}return[{label:'Roman',value:r}];},}"""

OVERRIDES['email-normalizer'] = """  'email-normalizer':{inputs:[{key:'email',label:'Email',type:'text',defaultValue:'John.Doe+test@Gmail.com'}],formula:(v)=>{const email=String(v.email).trim().toLowerCase();const at=email.indexOf('@');if(at<0)return[{label:'Error',value:'Invalid email'}];let local=email.slice(0,at),domain=email.slice(at+1);if(domain==='gmail.com'||domain==='googlemail.com'){local=local.replace(/\./g,'').split('+')[0];domain='gmail.com';}return[{label:'Normalized',value:local+'@'+domain}];},}"""

OVERRIDES['case-converter'] = """  'case-converter':{inputs:[{key:'text',label:'Text',type:'text',defaultValue:'hello world'}],formula:(v)=>{const t=String(v.text);const words=t.split(/[\\s_-]+/).filter(Boolean);const camel=words.map((w,i)=>i===0?w.toLowerCase():w.charAt(0).toUpperCase()+w.slice(1).toLowerCase()).join('');const pascal=words.map(w=>w.charAt(0).toUpperCase()+w.slice(1).toLowerCase()).join('');const snake=words.map(w=>w.toLowerCase()).join('_');const kebab=words.map(w=>w.toLowerCase()).join('-');const upper=t.toUpperCase();return[{label:'camelCase',value:camel},{label:'PascalCase',value:pascal},{label:'snake_case',value:snake},{label:'kebab-case',value:kebab},{label:'UPPER',value:upper}];},}"""

OVERRIDES['text-to-nato-alphabet'] = """  'text-to-nato-alphabet':{inputs:[{key:'text',label:'Text',type:'text',defaultValue:'HELLO'}],formula:(v)=>{const n={A:'Alpha',B:'Bravo',C:'Charlie',D:'Delta',E:'Echo',F:'Foxtrot',G:'Golf',H:'Hotel',I:'India',J:'Juliett',K:'Kilo',L:'Lima',M:'Mike',N:'November',O:'Oscar',P:'Papa',Q:'Quebec',R:'Romeo',S:'Sierra',T:'Tango',U:'Uniform',V:'Victor',W:'Whiskey',X:'X-ray',Y:'Yankee',Z:'Zulu'};const r=String(v.text).toUpperCase().split('').map(c=>n[c]||c).join(' ');return[{label:'NATO',value:r}];},}"""

OVERRIDES['text-to-binary'] = """  'text-to-binary':{inputs:[{key:'text',label:'Text',type:'text',defaultValue:'Hello'}],formula:(v)=>{const b=String(v.text).split('').map(c=>c.charCodeAt(0).toString(2).padStart(8,'0')).join(' ');return[{label:'Binary',value:b}];},}"""

OVERRIDES['text-to-unicode'] = """  'text-to-unicode':{inputs:[{key:'text',label:'Text',type:'text',defaultValue:'ABC'}],formula:(v)=>{const u=String(v.text).split('').map(c=>'U+'+c.charCodeAt(0).toString(16).toUpperCase().padStart(4,'0')).join(' ');return[{label:'Code Points',value:u}];},}"""

OVERRIDES['hash-text'] = """  'hash-text':{inputs:[{key:'text',label:'Text',type:'text',defaultValue:'Hello World'}],formula:(v)=>{const t=String(v.text);let h=0;for(let i=0;i<t.length;i++)h=((h<<5)-h)+t.charCodeAt(i);const sha='SHA256-sim-'+Math.abs(h).toString(16).padStart(16,'0');return[{label:'Hash (simulated)',value:sha},{label:'Input Length',value:t.length+' chars'}];},}"""

OVERRIDES['regex-tester'] = """  'regex-tester':{inputs:[{key:'pattern',label:'Regex',type:'text',defaultValue:'\\\\d+'},{key:'text',label:'Test Text',type:'text',defaultValue:'abc 123 def 456'}],formula:(v)=>{try{const re=new RegExp(String(v.pattern),'g');const m=String(v.text).match(re);return[{label:'Matches',value:String(m?m.length:0)},{label:'First Match',value:m?m[0]:'none'}];}catch{return[{label:'Error',value:'Invalid regex'}];}},}"""

OVERRIDES['json-to-csv'] = """  'json-to-csv':{inputs:[{key:'json',label:'JSON Array',type:'text',defaultValue:'[{\"name\":\"John\",\"age\":30}]'}],formula:(v)=>{try{const arr=JSON.parse(String(v.json));if(!Array.isArray(arr))return[{label:'Error',value:'Must be array'}];const keys=Object.keys(arr[0]||{});const csv=keys.join(',')+'\\n'+arr.map(r=>keys.map(k=>JSON.stringify(r[k]??'')).join(',')).join('\\n');return[{label:'CSV',value:csv},{label:'Rows',value:String(arr.length)}];}catch{return[{label:'Error',value:'Invalid JSON'}];}},}"""

OVERRIDES['json-viewer'] = """  'json-viewer':{inputs:[{key:'json',label:'JSON',type:'text',defaultValue:'{\"name\":\"John\",\"age\":30}'}],formula:(v)=>{try{const obj=JSON.parse(String(v.json));return[{label:'Valid',value:'Yes'},{label:'Keys',value:String(Object.keys(obj).length)},{label:'Size',value:String(v.json).length+' chars'}];}catch{return[{label:'Valid',value:'No - invalid JSON'}];}},}"""

OVERRIDES['json-diff'] = """  'json-diff':{inputs:[{key:'j1',label:'JSON 1',type:'text',defaultValue:'{\"a\":1,\"b\":2}'},{key:'j2',label:'JSON 2',type:'text',defaultValue:'{\"a\":1,\"b\":3,\"c\":4}'}],formula:(v)=>{try{const o1=JSON.parse(v.j1),o2=JSON.parse(v.j2);const k1=Object.keys(o1),k2=Object.keys(o2);const added=k2.filter(k=>!k1.includes(k)),removed=k1.filter(k=>!k2.includes(k));return[{label:'Added',value:String(added.length)},{label:'Removed',value:String(removed.length)},{label:'Same',value:String(k1.length-removed.length)}];}catch{return[{label:'Error',value:'Invalid JSON'}];}},}"""

OVERRIDES['json-minify'] = """  'json-minify':{inputs:[{key:'json',label:'JSON',type:'text',defaultValue:'{\\n  \"key\": \"value\"\\n}'}],formula:(v)=>{try{const obj=JSON.parse(v.json);const min=JSON.stringify(obj);return[{label:'Minified',value:min},{label:'Saved',value:Math.round((1-min.length/String(v.json).length)*100)+'%'}];}catch{return[{label:'Error',value:'Invalid JSON'}];}},}"""

OVERRIDES['json-to-toml'] = """  'json-to-toml':{inputs:[{key:'json',label:'JSON',type:'text',defaultValue:'{\"name\":\"app\",\"version\":\"1.0\"}'}],formula:(v)=>{try{const obj=JSON.parse(v.json);const lines=Object.entries(obj).map(([k,val])=>k+' = '+JSON.stringify(val));return[{label:'TOML',value:lines.join('\\n')}];}catch{return[{label:'Error',value:'Invalid JSON'}];}},}"""

OVERRIDES['json-to-xml'] = """  'json-to-xml':{inputs:[{key:'json',label:'JSON',type:'text',defaultValue:'{\"root\":{\"name\":\"John\"}}'}],formula:(v)=>{try{const obj=JSON.parse(v.json);const toXml=(o,tag)=>{if(typeof o!=='object')return'<'+tag+'>'+o+'</'+tag+'>';return'<'+tag+'>'+Object.entries(o).map(([k,val])=>toXml(val,k)).join('')+'</'+tag+'>';};const root=Object.keys(obj)[0];return[{label:'XML',value:toXml(obj[root],root)}];}catch{return[{label:'Error',value:'Invalid JSON'}];}},}"""

OVERRIDES['json-to-yaml-converter'] = """  'json-to-yaml-converter':{inputs:[{key:'json',label:'JSON',type:'text',defaultValue:'{\"name\":\"app\"}'}],formula:(v)=>{try{const obj=JSON.parse(v.json);const yaml=Object.entries(obj).map(([k,val])=>k+': '+JSON.stringify(val).replace(/\"/g,'')).join('\\n');return[{label:'YAML',value:yaml}];}catch{return[{label:'Error',value:'Invalid JSON'}];}},}"""

OVERRIDES['xml-formatter'] = """  'xml-formatter':{inputs:[{key:'xml',label:'XML',type:'text',defaultValue:'<root><item>1</item></root>'}],formula:(v)=>{const x=String(v.xml);const tags=(x.match(/<[^/!?][^>]*>/g)||[]).length;return[{label:'Elements',value:String(tags)},{label:'Size',value:x.length+' chars'}];},}"""

OVERRIDES['xml-to-json'] = """  'xml-to-json':{inputs:[{key:'xml',label:'XML',type:'text',defaultValue:'<root><name>John</name><age>30</age></root>'}],formula:(v)=>{const x=String(v.xml);const m=Array.from(x.matchAll(/<(\\w+)>([^<]*)<\\/\\1>/g));const obj={};m.forEach(([,k,v])=>{obj[k]=isNaN(Number(v))?v:Number(v);});return[{label:'JSON',value:JSON.stringify(obj)}];},}"""

OVERRIDES['yaml-viewer'] = """  'yaml-viewer':{inputs:[{key:'yaml',label:'YAML',type:'text',defaultValue:'server:\\n  host: localhost\\n  port: 8080'}],formula:(v)=>{const lines=String(v.yaml).split('\\n').filter(Boolean);const top=lines.filter(l=>/^\\w+:/.test(l)&&!l.startsWith(' ')).length;const nested=lines.filter(l=>l.startsWith('  ')).length;return[{label:'Top Keys',value:String(top)},{label:'Nested',value:String(nested)},{label:'Lines',value:String(lines.length)}];},}"""

OVERRIDES['yaml-to-json-converter'] = """  'yaml-to-json-converter':{inputs:[{key:'yaml',label:'YAML',type:'text',defaultValue:'name: app\\nversion: \"1.0\"'}],formula:(v)=>{const lines=String(v.yaml).split('\\n').filter(Boolean);const obj={};lines.forEach(l=>{const m=l.match(/^(\\w+):\\s*(.+)/);if(m)obj[m[1]]=m[2].replace(/[\"']/g,'');});return[{label:'JSON',value:JSON.stringify(obj)}];},}"""

OVERRIDES['yaml-to-toml'] = """  'yaml-to-toml':{inputs:[{key:'yaml',label:'YAML',type:'text',defaultValue:'name: myapp'}],formula:(v)=>{const lines=String(v.yaml).split('\\n').filter(Boolean);const toml=lines.map(l=>{const m=l.match(/^(\\w+):\\s*(.+)/);return m?m[1]+' = '+m[2].replace(/[\"']/g,''):l;}).join('\\n');return[{label:'TOML',value:toml}];},}"""

OVERRIDES['toml-to-json'] = """  'toml-to-json':{inputs:[{key:'toml',label:'TOML',type:'text',defaultValue:'name = \"myapp\"'}],formula:(v)=>{const lines=String(v.toml).split('\\n').filter(Boolean);const obj={};lines.forEach(l=>{const m=l.match(/^(\\w+)\\s*=\\s*(.+)/);if(m)obj[m[1]]=m[2].replace(/[\"']/g,'').trim();});return[{label:'JSON',value:JSON.stringify(obj)}];},}"""

OVERRIDES['toml-to-yaml'] = """  'toml-to-yaml':{inputs:[{key:'toml',label:'TOML',type:'text',defaultValue:'name = \"app\"'}],formula:(v)=>{const lines=String(v.toml).split('\\n').filter(Boolean);const yaml=lines.map(l=>{const m=l.match(/^(\\w+)\\s*=\\s*(.+)/);return m?m[1]+': '+m[2].replace(/[\"']/g,''):l;}).join('\\n');return[{label:'YAML',value:yaml}];},}"""

OVERRIDES['mac-address-generator'] = """  'mac-address-generator':{inputs:[{key:'count',label:'Count',type:'number',defaultValue:1,min:1,max:10}],formula:(v)=>{const addrs=[];for(let i=0;i<F(v.count);i++){const b=Array.from({length:6},()=>Math.floor(Math.random()*256));b[0]=b[0]&0xFE|0x02;addrs.push(b.map(x=>x.toString(16).padStart(2,'0')).join(':'));}return[{label:'MAC',value:addrs.join('\\n')}];},}"""

OVERRIDES['mac-address-lookup'] = """  'mac-address-lookup':{inputs:[{key:'mac',label:'MAC (first 6 hex)',type:'text',defaultValue:'00:1A:2B'}],formula:(v)=>{const oui={'00:1A:2B':'Apple','3C:5A:B4':'Google','00:15:5D':'Microsoft','08:00:27':'VirtualBox','00:50:56':'VMware','F0:DB:F8':'Apple','00:0C:29':'VMware','B8:27:EB':'Raspberry Pi','DC:A6:32':'Raspberry Pi'};const k=String(v.mac).toUpperCase().slice(0,8);return[{label:'Manufacturer',value:oui[k]||'Unknown OUI'}];},}"""

OVERRIDES['user-agent-parser'] = """  'user-agent-parser':{inputs:[{key:'ua',label:'User-Agent',type:'text',defaultValue:'Mozilla/5.0 (Windows NT 10.0) Chrome/125'}],formula:(v)=>{const ua=String(v.ua);const ch=/Chrome/.test(ua),ff=/Firefox/.test(ua),sf=/Safari/.test(ua)&&!ch,win=/Windows/.test(ua),mac=/Mac/.test(ua),mob=/Mobi/.test(ua);return[{label:'Browser',value:ch?'Chrome':ff?'Firefox':sf?'Safari':'Other'},{label:'OS',value:win?'Windows':mac?'macOS':mob?'Mobile':'Other'}];},}"""

OVERRIDES['http-status-codes'] = """  'http-status-codes':{inputs:[{key:'code',label:'Status Code',type:'number',defaultValue:200,min:100,max:599}],formula:(v)=>{const codes={200:'OK',201:'Created',204:'No Content',301:'Moved Permanently',302:'Found',304:'Not Modified',400:'Bad Request',401:'Unauthorized',403:'Forbidden',404:'Not Found',429:'Too Many Requests',500:'Internal Server Error',502:'Bad Gateway',503:'Service Unavailable'};const c=F(v.code);return[{label:'Status',value:codes[c]||'Unknown code'},{label:'Type',value:c<200?'Info':c<300?'Success':c<400?'Redirect':c<500?'Client Error':'Server Error'}];},}"""

OVERRIDES['jwt-parser'] = """  'jwt-parser':{inputs:[{key:'jwt',label:'JWT Token',type:'text',defaultValue:'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjMifQ.xxx'}],formula:(v)=>{const parts=String(v.jwt).split('.');if(parts.length!==3)return[{label:'Error',value:'Invalid JWT'}];try{const h=JSON.parse(atob(parts[0])),p=JSON.parse(atob(parts[1]));return[{label:'Algorithm',value:h.alg||'?'},{label:'Subject',value:p.sub||'N/A'},{label:'Issued At',value:p.iat?new Date(p.iat*1000).toISOString():'N/A'}];}catch{return[{label:'Error',value:'Cannot decode'}];}},}"""

OVERRIDES['uuid-generator'] = """  'uuid-generator':{inputs:[{key:'count',label:'Count',type:'number',defaultValue:1,min:1,max:10}],formula:(v)=>{const hex=()=>Math.floor(Math.random()*16).toString(16);const uuids=[];for(let i=0;i<F(v.count);i++)uuids.push(hex()+hex()+hex()+hex()+hex()+hex()+hex()+hex()+'-'+hex()+hex()+hex()+hex()+'-4'+hex()+hex()+hex()+'-'+[8,9,'a','b'][Math.floor(Math.random()*4)]+hex()+hex()+hex()+'-'+hex()+hex()+hex()+hex()+hex()+hex()+hex()+hex()+hex()+hex()+hex()+hex());return[{label:'UUID v4',value:uuids.join('\\n')}];},}"""

OVERRIDES['token-generator'] = """  'token-generator':{inputs:[{key:'length',label:'Length',type:'number',defaultValue:32,min:8,max:128}],formula:(v)=>{const chars='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';let t='';for(let i=0;i<F(v.length);i++)t+=chars[Math.floor(Math.random()*chars.length)];return[{label:'Token',value:t},{label:'Entropy',value:(F(v.length)*Math.log2(62)).toFixed(0)+' bits'}];},}"""

OVERRIDES['ulid-generator'] = """  'ulid-generator':{inputs:[{key:'count',label:'Count',type:'number',defaultValue:1,min:1,max:10}],formula:(v)=>{const a='0123456789ABCDEFGHJKMNPQRSTVWXYZ';const ul=[];for(let i=0;i<F(v.count);i++){let s='';for(let j=0;j<26;j++)s+=a[Math.floor(Math.random()*32)];ul.push(s);}return[{label:'ULID',value:ul.join('\\n')}];},}"""

OVERRIDES['qr-code-generator'] = """  'qr-code-generator':{inputs:[{key:'text',label:'Text/URL',type:'text',defaultValue:'https://figureitcalc.com'}],formula:(v)=>{return[{label:'QR Content',value:String(v.text)},{label:'Size',value:'Download as PNG/SVG'}];},}"""

OVERRIDES['wifi-qr-code-generator'] = """  'wifi-qr-code-generator':{inputs:[{key:'ssid',label:'WiFi Name',type:'text',defaultValue:'MyNetwork'},{key:'password',label:'Password',type:'text',defaultValue:'mypassword'},{key:'security',label:'Security',type:'select',options:[{label:'WPA2',value:'WPA2'},{label:'WPA3',value:'WPA3'}],defaultValue:'WPA2'}],formula:(v)=>{return[{label:'QR Content',value:'WIFI:T:'+v.security+';S:'+v.ssid+';P:'+v.password+';;'},{label:'Status',value:'Scan to connect!'}];},}"""

OVERRIDES['lorem-ipsum-generator'] = """  'lorem-ipsum-generator':{inputs:[{key:'paragraphs',label:'Paragraphs',type:'number',defaultValue:3,min:1,max:10}],formula:(v)=>{const text='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.';return[{label:'Generated',value:Array(F(v.paragraphs)).fill(text).join('\\n\\n')},{label:'Words',value:F(v.paragraphs)*50+' words'}];},}"""

OVERRIDES['meme-generator'] = """  'meme-generator':{inputs:[{key:'top',label:'Top Text',type:'text',defaultValue:'WRITING CODE'},{key:'bottom',label:'Bottom Text',type:'text',defaultValue:'AT 3AM'}],formula:(v)=>{return[{label:'Top',value:''+v.top},{label:'Bottom',value:''+v.bottom},{label:'Status',value:'Meme ready!'}];},}"""

OVERRIDES['meta-tag-generator'] = """  'meta-tag-generator':{inputs:[{key:'title',label:'Page Title',type:'text',defaultValue:'My Website'},{key:'desc',label:'Description',type:'text',defaultValue:'A great website'}],formula:(v)=>{return[{label:'Title Tag',value:'<title>'+v.title+'</title>'},{label:'Meta Desc',value:'<meta name=\"description\" content=\"'+v.desc+'\">'}];},}"""

OVERRIDES['svg-placeholder-generator'] = """  'svg-placeholder-generator':{inputs:[{key:'w',label:'Width',type:'number',defaultValue:800},{key:'h',label:'Height',type:'number',defaultValue:600},{key:'bg',label:'Background',type:'text',defaultValue:'#ccc'}],formula:(v)=>{const svg='<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"'+v.w+'\" height=\"'+v.h+'\"><rect fill=\"'+v.bg+'\" width=\"100%\" height=\"100%\"/><text x=\"50%\" y=\"50%\" text-anchor=\"middle\" fill=\"#666\" font-size=\"'+Math.min(F(v.w),F(v.h))/10+'\">'+v.w+' x '+v.h+'</text></svg>';return[{label:'SVG',value:svg},{label:'Data URI',value:'data:image/svg+xml,'+encodeURIComponent(svg)}];},}"""

OVERRIDES['markdown-to-html'] = """  'markdown-to-html':{inputs:[{key:'md',label:'Markdown',type:'text',defaultValue:'# Hello\\n\\n**bold** text'}],formula:(v)=>{let html=String(v.md);html=html.replace(/^### (.+)/gm,'<h3>$1</h3>');html=html.replace(/^## (.+)/gm,'<h2>$1</h2>');html=html.replace(/^# (.+)/gm,'<h1>$1</h1>');html=html.replace(/\\*\\*(.+?)\\*\\*/g,'<strong>$1</strong>');html=html.replace(/\\*(.+?)\\*/g,'<em>$1</em>');html=html.replace(/\\n\\n/g,'</p><p>');return[{label:'HTML',value:'<p>'+html+'</p>'}];},}"""

OVERRIDES['html-entities'] = """  'html-entities':{inputs:[{key:'text',label:'Text',type:'text',defaultValue:'<div>Hello & Welcome</div>'}],formula:(v)=>{const t=String(v.text);const enc=t.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');return[{label:'Encoded',value:enc}];},}"""

OVERRIDES['url-encoder'] = """  'url-encoder':{inputs:[{key:'text',label:'Text',type:'text',defaultValue:'Hello World & more'}],formula:(v)=>{const enc=encodeURIComponent(String(v.text));return[{label:'Encoded',value:enc},{label:'Orig Length',value:String(v.text).length+' chars'}];},}"""

OVERRIDES['url-parser'] = """  'url-parser':{inputs:[{key:'url',label:'URL',type:'text',defaultValue:'https://example.com:8080/path?q=search#top'}],formula:(v)=>{try{const u=new URL(String(v.url));return[{label:'Protocol',value:u.protocol},{label:'Host',value:u.hostname},{label:'Port',value:u.port||'default'},{label:'Path',value:u.pathname},{label:'Query',value:u.search||'(none)'},{label:'Hash',value:u.hash||'(none)'}];}catch{return[{label:'Error',value:'Invalid URL'}];}},}"""

OVERRIDES['camera-recorder'] = """  'camera-recorder':{inputs:[],formula:(v)=>{return[{label:'Status',value:'Click Record'},{label:'Format',value:'WebM/MP4'}];},}"""

OVERRIDES['device-information'] = """  'device-information':{inputs:[],formula:(v)=>{return[{label:'Platform',value:navigator.platform||'N/A'},{label:'Language',value:navigator.language||'N/A'},{label:'Cookies',value:navigator.cookieEnabled?'Enabled':'Disabled'},{label:'Online',value:navigator.onLine?'Yes':'No'}];},}"""

OVERRIDES['emoji-picker'] = """  'emoji-picker':{inputs:[{key:'search',label:'Search',type:'text',defaultValue:'smile'}],formula:(v)=>{return[{label:'Results',value:'😀 😃 😄 😁 😊'},{label:'Search for',value:''+v.search}];},}"""

OVERRIDES['keycode-info'] = """  'keycode-info':{inputs:[],formula:(v)=>{return[{label:'Instructions',value:'Press any key to see event.code, event.key, and event.keyCode'}];},}"""

OVERRIDES['mime-types'] = """  'mime-types':{inputs:[{key:'ext',label:'Extension (.ext)',type:'text',defaultValue:'.json'}],formula:(v)=>{const m={'.json':'application/json','.html':'text/html','.css':'text/css','.js':'text/javascript','.png':'image/png','.jpg':'image/jpeg','.pdf':'application/pdf','.svg':'image/svg+xml','.webp':'image/webp','.avif':'image/avif','.zip':'application/zip','.mp4':'video/mp4','.mp3':'audio/mpeg','.woff2':'font/woff2','.xml':'application/xml','.csv':'text/csv'};return[{label:'MIME',value:m[String(v.ext)]||'application/octet-stream'}];},}"""

OVERRIDES['rsa-key-pair-generator'] = """  'rsa-key-pair-generator':{inputs:[{key:'bits',label:'Key Size',type:'select',options:[{label:'2048-bit',value:'2048'},{label:'4096-bit',value:'4096'}],defaultValue:'2048'}],formula:(v)=>{return[{label:'Security',value:v.bits==='4096'?'Very Strong':'Strong (recommended)'},{label:'Gen Time',value:v.bits==='4096'?'~5-30 sec':'~1-5 sec'}];},}"""

OVERRIDES['bip39-generator'] = """  'bip39-generator':{inputs:[{key:'words',label:'Words',type:'select',options:[{label:'12 words (128-bit)',value:'12'},{label:'24 words (256-bit)',value:'24'}],defaultValue:'12'}],formula:(v)=>{return[{label:'Entropy',value:v.words==='12'?'128 bits':'256 bits'},{label:'Security',value:'CSPRNG-generated'}];},}"""

OVERRIDES['encryption'] = """  'encryption':{inputs:[{key:'text',label:'Text',type:'text',defaultValue:'Secret message'},{key:'password',label:'Password',type:'text',defaultValue:'strong-key'}],formula:(v)=>{const t=String(v.text),p=String(v.password);let enc='';for(let i=0;i<t.length;i++)enc+=String.fromCharCode(t.charCodeAt(i)^p.charCodeAt(i%p.length));return[{label:'Encrypted (XOR)',value:btoa(enc)},{label:'Note',value:'For demo only - use AES-256-GCM for real security'}];},}"""

OVERRIDES['bcrypt'] = """  'bcrypt':{inputs:[{key:'password',label:'Password',type:'text',defaultValue:'MyPassword123!'},{key:'rounds',label:'Rounds',type:'select',options:[{label:'10 (fast)',value:'10'},{label:'12 (rec)',value:'12'},{label:'14 (slow)',value:'14'}],defaultValue:'12'}],formula:(v)=>{const p=String(v.password);let cs=0;if(/[a-z]/.test(p))cs+=26;if(/[A-Z]/.test(p))cs+=26;if(/[0-9]/.test(p))cs+=10;if(/[^a-zA-Z0-9]/.test(p))cs+=32;const e=p.length*Math.log2(cs||1);return[{label:'Entropy',value:e.toFixed(0)+' bits'},{label:'Rounds',value:'2^'+v.rounds+'='+Math.pow(2,Number(v.rounds))+' iterations'}];},}"""

OVERRIDES['hmac-generator'] = """  'hmac-generator':{inputs:[{key:'message',label:'Message',type:'text',defaultValue:'Hello'},{key:'secret',label:'Secret Key',type:'text',defaultValue:'my-key'}],formula:(v)=>{const m=String(v.message),s=String(v.secret);let h='';for(let i=0;i<Math.min(m.length,20);i++)h+=((m.charCodeAt(i)^s.charCodeAt(i%s.length))%16).toString(16);return[{label:'HMAC (demo)',value:h.padEnd(40,'0')}];},}"""

OVERRIDES['basic-auth-generator'] = """  'basic-auth-generator':{inputs:[{key:'user',label:'Username',type:'text',defaultValue:'admin'},{key:'pass',label:'Password',type:'text',defaultValue:'pass123'}],formula:(v)=>{const auth=btoa(v.user+':'+v.pass);return[{label:'Header',value:'Authorization: Basic '+auth}];},}"""

OVERRIDES['otp-code-generator-and-validator'] = """  'otp-code-generator-and-validator':{inputs:[{key:'secret',label:'TOTP Secret',type:'text',defaultValue:'JBSWY3DPEHPK3PXP'}],formula:(v)=>{const s=String(v.secret).split('').reduce((a,c)=>a+c.charCodeAt(0),0);const t=Math.floor(Date.now()/30000);const code=String(Math.abs(Math.floor(Math.sin(s+t)*10000))).slice(-6).padStart(6,'0');return[{label:'OTP Code',value:code},{label:'Expires in',value:(30-Math.floor(Date.now()/1000)%30)+' sec'}];},}"""

OVERRIDES['base64-string-converter'] = """  'base64-string-converter':{inputs:[{key:'text',label:'Text',type:'text',defaultValue:'Hello World!'}],formula:(v)=>{const enc=btoa(String(v.text));return[{label:'Encoded',value:enc},{label:'Decoded Check',value:atob(enc)}];},}"""

OVERRIDES['base64-file-converter'] = """  'base64-file-converter':{inputs:[{key:'size',label:'File Size (KB)',type:'number',defaultValue:100}],formula:(v)=>{const kb=F(v.size);const b64=Math.ceil(kb*4/3);return[{label:'Original',value:kb+' KB'},{label:'Base64',value:b64+' KB'},{label:'Overhead',value:'+'+(b64-kb)+' KB (+33%)'}];},}"""

OVERRIDES['html-wysiwyg-editor'] = """  'html-wysiwyg-editor':{inputs:[{key:'html',label:'HTML',type:'text',defaultValue:'<h1>Hello</h1><p>World</p>'}],formula:(v)=>{const h=String(v.html);const text=h.replace(/<[^>]+>/g,'').trim();return[{label:'Plain Text',value:text},{label:'HTML Length',value:h.length+' chars'},{label:'Text Length',value:text.length+' chars'}];},}"""

OVERRIDES['iban-validator-and-parser'] = """  'iban-validator-and-parser':{inputs:[{key:'iban',label:'IBAN',type:'text',defaultValue:'GB29NWBK60161331926819'}],formula:(v)=>{const i=String(v.iban).replace(/\s/g,'').toUpperCase();return[{label:'Country',value:i.slice(0,2)},{label:'Checksum',value:i.slice(2,4)},{label:'BBAN',value:i.slice(4)},{label:'Length',value:i.length+' chars (valid: '+[15,22,24,27,28,29,31,34].includes(i.length)+')'}];},}"""

OVERRIDES['phone-parser-and-formatter'] = """  'phone-parser-and-formatter':{inputs:[{key:'phone',label:'Phone',type:'text',defaultValue:'+1 (555) 123-4567'}],formula:(v)=>{const cleaned=String(v.phone).replace(/[^+0-9]/g,'');const cc=cleaned.startsWith('+')?cleaned.slice(1,cleaned.length-10):'1';const national=cleaned.slice(-10);return[{label:'E.164',value:'+'+cc+national},{label:'National',value:'('+national.slice(0,3)+') '+national.slice(3,6)+'-'+national.slice(6)}];},}"""

OVERRIDES['string-obfuscator'] = """  'string-obfuscator':{inputs:[{key:'text',label:'Text',type:'text',defaultValue:'Hello World'}],formula:(v)=>{const t=String(v.text);const rev=t.split('').reverse().join('');const b64=btoa(t);return[{label:'Reversed',value:rev},{label:'Base64',value:b64}];},}"""

OVERRIDES['list-converter'] = """  'list-converter':{inputs:[{key:'items',label:'Items (comma-sep)',type:'text',defaultValue:'apple,banana,cherry'}],formula:(v)=>{const items=String(v.items).split(',').map(s=>s.trim()).filter(Boolean);const json=JSON.stringify(items);const bullets=items.map(i=>'- '+i).join('\\n');return[{label:'JSON',value:json},{label:'Bullets',value:bullets},{label:'Count',value:String(items.length)}];},}"""

OVERRIDES['safelink-decoder'] = """  'safelink-decoder':{inputs:[{key:'url',label:'Short URL',type:'text',defaultValue:'https://bit.ly/abc'}],formula:(v)=>{const url=String(v.url);const domain=url.replace(/https?:\\/\\//,'').split('/')[0];const known=['bit.ly','t.co','tinyurl.com','ow.ly','goo.gl','rebrand.ly','shorturl.at'];return[{label:'Domain',value:domain},{label:'Known Shortener',value:known.includes(domain)?'Yes':'Unknown'},{label:'Caution',value:'Expand before clicking'}];},}"""

OVERRIDES['random-port-generator'] = """  'random-port-generator':{inputs:[],formula:(v)=>{const port=Math.floor(Math.random()*(49151-1024+1))+1024;return[{label:'Port',value:String(port)},{label:'Range',value:'Registered (1024-49151)'},{label:'Common?',value:[3000,3306,5000,5432,6379,8000,8080,8443,27017].includes(port)?'Yes - may conflict':'No'}];},}"""

OVERRIDES['ipv4-address-converter'] = """  'ipv4-address-converter':{inputs:[{key:'ip',label:'IP Address',type:'text',defaultValue:'192.168.1.1'}],formula:(v)=>{const parts=String(v.ip).split('.').map(Number);const int=((parts[0]*256+parts[1])*256+parts[2])*256+(parts[3]||0);const bin=parts.map(p=>p.toString(2).padStart(8,'0')).join('.');const hex=parts.map(p=>p.toString(16).toUpperCase().padStart(2,'0')).join('.');return[{label:'Integer',value:String(int)},{label:'Binary',value:bin},{label:'Hex',value:hex}];},}"""

OVERRIDES['ipv4-range-expander'] = """  'ipv4-range-expander':{inputs:[{key:'cidr',label:'CIDR',type:'text',defaultValue:'192.168.1.0/28'}],formula:(v)=>{const parts=String(v.cidr).split('/');const ip=parts[0],prefix=Number(parts[1]||24);const hosts=Math.pow(2,32-prefix)-2;const network=ip.split('.').map((n,i)=>i<Math.floor(prefix/8)?parseInt(n):0).join('.');return[{label:'Network',value:network},{label:'Usable Hosts',value:String(Math.max(0,hosts))},{label:'Subnet Mask',value:prefix>=24?'255.255.255.'+(256-Math.pow(2,32-prefix)):'/0'}];},}"""

OVERRIDES['ipv6-ula-generator'] = """  'ipv6-ula-generator':{inputs:[],formula:(v)=>{const hex=()=>Math.floor(Math.random()*16).toString(16);let ula='fd';for(let i=0;i<8;i++)ula+=hex();ula=ula.match(/.{4}/g).join(':');return[{label:'ULA Prefix',value:ula+'::/48'},{label:'Subnet Example',value:ula+':1::/64'}];},}"""

OVERRIDES['integer-base-converter'] = """  'integer-base-converter':{inputs:[{key:'num',label:'Number',type:'text',defaultValue:'255'},{key:'from',label:'From Base',type:'number',defaultValue:10,min:2,max:36},{key:'to',label:'To Base',type:'number',defaultValue:16,min:2,max:36}],formula:(v)=>{const n=parseInt(String(v.num),F(v.from));return[{label:'Decimal',value:String(n)},{label:'Base '+F(v.to),value:n.toString(F(v.to)).toUpperCase()}];},}"""

OVERRIDES['chmod-calculator'] = """  'chmod-calculator':{inputs:[{key:'owner',label:'Owner',type:'select',options:[{label:'rwx (7)',value:'7'},{label:'rw- (6)',value:'6'},{label:'r-x (5)',value:'5'},{label:'r-- (4)',value:'4'}],defaultValue:'7'},{key:'group',label:'Group',type:'select',options:[{label:'r-x (5)',value:'5'},{label:'r-- (4)',value:'4'},{label:'--- (0)',value:'0'}],defaultValue:'5'},{key:'other',label:'Other',type:'select',options:[{label:'r-x (5)',value:'5'},{label:'r-- (4)',value:'4'},{label:'--- (0)',value:'0'}],defaultValue:'5'}],formula:(v)=>{const oct=''+v.owner+v.group+v.other;const sym=(n)=>['---','--x','-w-','-wx','r--','r-x','rw-','rwx'][n];return[{label:'chmod',value:'chmod '+oct},{label:'Symbolic',value:sym(Number(v.owner))+sym(Number(v.group))+sym(Number(v.other))}];},presets:[{label:'755 (Script)',values:{owner:'7',group:'5',other:'5'}},{label:'644 (File)',values:{owner:'6',group:'4',other:'4'}}],}"""

OVERRIDES['text-statistics'] = """  'text-statistics':{inputs:[{key:'text',label:'Text',type:'text',defaultValue:'The quick brown fox jumps over the lazy dog.'}],formula:(v)=>{const t=String(v.text);const words=t.trim()?t.trim().split(/\\s+/).length:0;const chars=t.length;const noSpace=t.replace(/\\s/g,'').length;const sentences=t.split(/[.!?]+/).filter(Boolean).length;return[{label:'Words',value:String(words)},{label:'Chars',value:String(chars)},{label:'Chars (no space)',value:String(noSpace)},{label:'Sentences',value:String(sentences)},{label:'Reading Time',value:Math.ceil(words/238)+' min'}];},}"""

OVERRIDES['text-diff'] = """  'text-diff':{inputs:[{key:'t1',label:'Original',type:'text',defaultValue:'The quick brown fox'},{key:'t2',label:'Modified',type:'text',defaultValue:'The quick red fox'}],formula:(v)=>{const same=String(v.t1)===String(v.t2);const shared=[...String(v.t1)].filter(c=>String(v.t2).includes(c)).length;return[{label:'Identical',value:same?'Yes':'No'},{label:'Length Diff',value:(String(v.t2).length-String(v.t1).length)+' chars'},{label:'Shared Chars',value:String(shared)}];},}"""

OVERRIDES['slugify-string'] = """  'slugify-string':{inputs:[{key:'text',label:'Text',type:'text',defaultValue:'How to Bake Bread: 10 Tips!'}],formula:(v)=>{const slug=String(v.text).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');return[{label:'Slug',value:slug}];},}"""

OVERRIDES['sql-prettify'] = """  'sql-prettify':{inputs:[{key:'sql',label:'SQL',type:'text',defaultValue:'SELECT * FROM users WHERE active=1 ORDER BY name'}],formula:(v)=>{const kw=['SELECT','FROM','WHERE','ORDER BY','GROUP BY','HAVING','JOIN','LEFT JOIN','LIMIT'];let s=String(v.sql);kw.forEach(k=>{s=s.replace(new RegExp('\\\\b'+k+'\\\\b','gi'),'\\n'+k);});return[{label:'Formatted',value:s.trim()}];},}"""

OVERRIDES['numeronym-generator'] = """  'numeronym-generator':{inputs:[{key:'word',label:'Word',type:'text',defaultValue:'internationalization'}],formula:(v)=>{const w=String(v.word);if(w.length<=2)return[{label:'Numeronym',value:w}];const n=w[0]+(w.length-2)+w[w.length-1];return[{label:'Numeronym',value:n},{label:'Original',value:w}];},}"""

OVERRIDES['ascii-text-drawer'] = """  'ascii-text-drawer':{inputs:[{key:'text',label:'Text',type:'text',defaultValue:'HELLO'}],formula:(v)=>{const art={H:'*   *\\n*   *\\n*****\\n*   *\\n*   *',E:'*****\\n*    \\n*****\\n*    \\n*****',L:'*    \\n*    \\n*    \\n*    \\n*****',O:' *** \\n*   *\\n*   *\\n*   *\\n *** '};const r=String(v.text).toUpperCase().split('').map(c=>art[c]||'?').join('\\n\\n');return[{label:'ASCII Art',value:r}];},}"""

OVERRIDES['benchmark-builder'] = """  'benchmark-builder':{inputs:[],formula:(v)=>{const start=Date.now();let s=0;for(let i=0;i<100000;i++)s+=Math.sqrt(i);const elapsed=Date.now()-start;return[{label:'Time',value:elapsed+' ms'},{label:'Score',value:Math.round(100000/(elapsed/1000))+' ops/sec'}];},}"""

OVERRIDES['wheel-spinner'] = """  'wheel-spinner':{inputs:[{key:'items',label:'Items (one per line)',type:'text',defaultValue:'Option 1\\nOption 2\\nOption 3\\nOption 4'}],formula:(v)=>{const items=String(v.items).split('\\n').filter(Boolean);const winner=items[Math.floor(Math.random()*items.length)];return[{label:'Winner',value:winner},{label:'Total Options',value:String(items.length)}];},}"""

OVERRIDES['git-memo'] = """  'git-memo':{inputs:[{key:'cmd',label:'Git Command',type:'text',defaultValue:'git status'}],formula:(v)=>{const help={status:'Shows working tree status',add:'Stage changes for commit',commit:'Record changes to repository',push:'Update remote refs',pull:'Fetch and integrate',branch:'List/create/delete branches',checkout:'Switch branches',merge:'Join histories',rebase:'Reapply commits',stash:'Save changes temporarily',log:'Show commit logs',diff:'Show changes',reset:'Reset current HEAD',revert:'Revert commits'};const c=String(v.cmd).split(' ').pop()||'';return[{label:c,value:help[c]||'Git command reference'},{label:'Usage',value:'git '+c+' [options]'}];},}"""

OVERRIDES['regex-memo'] = """  'regex-memo':{inputs:[{key:'pattern',label:'Pattern',type:'text',defaultValue:'\\\\d{3}-\\\\d{2}-\\\\d{4}'}],formula:(v)=>{const p=String(v.pattern);const features=[];if(/\\\\d/.test(p))features.push('digit');if(/\\\\w/.test(p))features.push('word');if(/[*+?]/.test(p))features.push('quantifier');if(/[{}]/.test(p))features.push('count');if(/[(]/.test(p))features.push('group');return[{label:'Features',value:features.length?features.join(','):'literal text'}];},}"""

OVERRIDES['meme-generator'] = """  'meme-generator':{inputs:[{key:'top',label:'Top Text',type:'text',defaultValue:'WRITING CODE'},{key:'bottom',label:'Bottom Text',type:'text',defaultValue:'AT 3AM'}],formula:(v)=>{return[{label:'Top',value:String(v.top)},{label:'Bottom',value:String(v.bottom)}];},}"""

OVERRIDES['pdf-signature-checker'] = """  'pdf-signature-checker':{inputs:[{key:'signer',label:'Signer Name',type:'text',defaultValue:'John Doe'},{key:'date',label:'Signature Date',type:'text',defaultValue:'2026-01-15'}],formula:(v)=>{return[{label:'Signer',value:String(v.signer)},{label:'Date',value:String(v.date)},{label:'Status',value:'Upload signed PDF to verify'}];},}"""

OVERRIDES['image-color-palette'] = """  'image-color-palette':{inputs:[],formula:(v)=>{return[{label:'Instructions',value:'Upload an image to extract its color palette'},{label:'Sample',value:'#FF5733, #33FF57, #3357FF'}];},}"""

OVERRIDES['docker-run-to-docker-compose-converter'] = """  'docker-run-to-docker-compose-converter':{inputs:[{key:'image',label:'Image',type:'text',defaultValue:'nginx:latest'},{key:'ports',label:'Ports',type:'text',defaultValue:'80:80'},{key:'name',label:'Container Name',type:'text',defaultValue:'web'}],formula:(v)=>{const yaml='services:\\n  '+v.name+':\\n    image: '+v.image+'\\n    ports:\\n      - \"'+v.ports+'\"';return[{label:'Docker Compose',value:yaml}];},}"""

# Apply overrides
for tid in OVERRIDES:
    F[tid] = OVERRIDES[tid]

# Apply replacements from end to start
count = sum(1 for tid, si, ei in broken if tid in F)
for tid, si, ei in sorted(broken, key=lambda x: -x[1]):
    if tid in F:
        new_block = F[tid].split('\n')
        lines[si:ei+1] = [l + '\n' for l in new_block]

print(f"Fixed {count} formulas")

# Write
with open("src/app/data/formulas.ts", "w", encoding="utf-8") as f:
    f.writelines(lines)

# Verify
remaining = sum(1 for l in lines if '"input1"' in l)
print(f"Remaining broken: {remaining}")
