with open("src/app/data/formulas.ts", "r", encoding="utf-8") as f:
    content = f.read()

F = {}

F['mortgage-calculator'] = "  'mortgage-calculator': {\n    inputs: [{key:'price',label:'Home Price ($)',type:'number',defaultValue:350000},{key:'down',label:'Down Payment (%)',type:'number',defaultValue:20},{key:'rate',label:'Interest Rate (%)',type:'number',defaultValue:6.3},{key:'term',label:'Loan Term (years)',type:'number',defaultValue:30}],\n    formula: (v) => { const P=F(v.price)*(1-F(v.down)/100),r=F(v.rate)/100/12,n=F(v.term)*12; const M=r>0?P*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):P/n; return [{label:'P&I Payment',value:'$'+M.toFixed(2)},{label:'Total Cost',value:'$'+(M*n).toFixed(0)},{label:'Total Interest',value:'$'+(M*n-P).toFixed(0)},{label:'Down Payment',value:'$'+(F(v.price)*F(v.down)/100).toFixed(0)}]; },\n    presets: [{label:'20%Down 30yr',values:{price:350000,down:20,rate:6.3,term:30}},{label:'FHA 3.5%',values:{price:300000,down:3.5,rate:6.5,term:30}}],\n  },"

F['tip-calculator'] = "  'tip-calculator': {\n    inputs: [{key:'bill',label:'Bill Amount ($)',type:'number',defaultValue:80},{key:'tipPct',label:'Tip (%)',type:'number',defaultValue:18},{key:'people',label:'Split Among',type:'number',defaultValue:3}],\n    formula: (v) => { const tip=F(v.bill)*F(v.tipPct)/100,total=F(v.bill)+tip,pp=F(v.people)>0?total/F(v.people):total; return [{label:'Tip',value:'$'+tip.toFixed(2)},{label:'Total',value:'$'+total.toFixed(2)},{label:'Per Person',value:'$'+pp.toFixed(2)}]; },\n    presets: [{label:'15pct',values:{bill:50,tipPct:15,people:2}},{label:'20pct',values:{bill:80,tipPct:20,people:3}}],\n  },"

F['discount-calculator'] = "  'discount-calculator': {\n    inputs: [{key:'price',label:'Original Price ($)',type:'number',defaultValue:100},{key:'discount',label:'Discount (%)',type:'number',defaultValue:20}],\n    formula: (v) => { const s=F(v.price)*F(v.discount)/100; return [{label:'You Save',value:'$'+s.toFixed(2)},{label:'Final Price',value:'$'+(F(v.price)-s).toFixed(2)}]; },\n    presets: [{label:'20pct off',values:{price:100,discount:20}},{label:'50pct off',values:{price:80,discount:50}}],\n  },"

F['compound-interest-calculator'] = "  'compound-interest-calculator': {\n    inputs: [{key:'principal',label:'Initial Invest ($)',type:'number',defaultValue:10000},{key:'monthly',label:'Monthly Add ($)',type:'number',defaultValue:200},{key:'rate',label:'Return (%)',type:'number',defaultValue:7},{key:'years',label:'Years',type:'number',defaultValue:20}],\n    formula: (v) => { const P=F(v.principal),pmt=F(v.monthly),r=F(v.rate)/100/12,n=F(v.years)*12; const fv=P*Math.pow(1+r,n)+(r>0?pmt*(Math.pow(1+r,n)-1)/r:pmt*n); const inv=P+pmt*n; return [{label:'Future Value',value:'$'+fv.toFixed(2)},{label:'Total Invested',value:'$'+inv.toFixed(0)},{label:'Interest',value:'$'+(fv-inv).toFixed(0)}]; },\n    presets: [{label:'30yr Retire',values:{principal:50000,monthly:500,rate:7,years:30}}],\n  },"

F['retirement-calculator'] = "  'retirement-calculator': {\n    inputs: [{key:'age',label:'Current Age',type:'number',defaultValue:30},{key:'retireAge',label:'Retire Age',type:'number',defaultValue:65},{key:'savings',label:'Savings ($)',type:'number',defaultValue:50000},{key:'monthly',label:'Monthly ($)',type:'number',defaultValue:500},{key:'rate',label:'Return (%)',type:'number',defaultValue:7}],\n    formula: (v) => { const P=F(v.savings),pmt=F(v.monthly),r=F(v.rate)/100/12,n=(F(v.retireAge)-F(v.age))*12; const fv=P*Math.pow(1+r,n)+(r>0?pmt*(Math.pow(1+r,n)-1)/r:pmt*n); return [{label:'Retirement Nest Egg',value:'$'+fv.toFixed(0)},{label:'Monthly (4%)',value:'$'+(fv*0.04/12).toFixed(0)},{label:'Contributed',value:'$'+(P+pmt*n).toFixed(0)}]; },\n    presets: [{label:'Start at 25',values:{age:25,retireAge:65,savings:10000,monthly:500,rate:7}}],\n  },"

F['temperature-converter'] = "  'temperature-converter': {\n    inputs: [{key:'celsius',label:'Celsius',type:'number',defaultValue:20},{key:'toUnit',label:'Convert To',type:'select',options:[{label:'Fahrenheit',value:'f'},{label:'Kelvin',value:'k'},{label:'Both',value:'both'}],defaultValue:'both'}],\n    formula: (v) => { const c=F(v.celsius),f=c*9/5+32,k=c+273.15; const r=[]; if(v.toUnit==='f'||v.toUnit==='both')r.push({label:'Fahrenheit',value:f.toFixed(1)+' degF'}); if(v.toUnit==='k'||v.toUnit==='both')r.push({label:'Kelvin',value:k.toFixed(1)+' K'}); r.push({label:'Celsius',value:c.toFixed(1)+' degC'}); return r; },\n    presets: [{label:'Freezing',values:{celsius:0,toUnit:'both'}},{label:'Body',values:{celsius:37,toUnit:'both'}},{label:'Boiling',values:{celsius:100,toUnit:'both'}}],\n  },"

F['fuel-cost-calculator'] = "  'fuel-cost-calculator': {\n    inputs: [{key:'distance',label:'Distance (miles)',type:'number',defaultValue:300},{key:'mpg',label:'Fuel Econ (MPG)',type:'number',defaultValue:25},{key:'fuelPrice',label:'Fuel Price ($/gal)',type:'number',defaultValue:3.50}],\n    formula: (v) => { const gal=F(v.distance)/F(v.mpg),cost=gal*F(v.fuelPrice); return [{label:'Fuel Needed',value:gal.toFixed(1)+' gal'},{label:'Trip Cost',value:'$'+cost.toFixed(2)},{label:'$/Mile',value:'$'+(F(v.fuelPrice)/F(v.mpg)).toFixed(3)}]; },\n    presets: [{label:'300mi Trip',values:{distance:300,mpg:25,fuelPrice:3.50}}],\n  },"

F['currency-converter'] = "  'currency-converter': {\n    inputs: [{key:'amount',label:'Amount',type:'number',defaultValue:100},{key:'rate',label:'Exchange Rate',type:'number',defaultValue:0.92,step:0.01}],\n    formula: (v) => { const r=F(v.amount)*F(v.rate); return [{label:'Converted',value:r.toFixed(2)},{label:'Inverse',value:(1/F(v.rate)).toFixed(4)}]; },\n    presets: [{label:'USD-EUR',values:{amount:100,rate:0.92}},{label:'USD-GBP',values:{amount:100,rate:0.79}}],\n  },"

F['percentage-calculator'] = "  'percentage-calculator': {\n    inputs: [{key:'value',label:'Part Value',type:'number',defaultValue:42},{key:'total',label:'Total Value',type:'number',defaultValue:60}],\n    formula: (v) => { const p=F(v.total)>0?F(v.value)/F(v.total)*100:0; return [{label:'Percentage',value:p.toFixed(2)+'%'},{label:'Remaining',value:(100-p).toFixed(2)+'%'}]; },\n    presets: [{label:'42/60',values:{value:42,total:60}},{label:'85/100',values:{value:85,total:100}}],\n  },"

# === BATCH 4: ALL REMAINING TOOLS ===
F['concrete-calculator'] = "  'concrete-calculator': {\n    inputs: [{key:'length',label:'Length (ft)',type:'number',defaultValue:10},{key:'width',label:'Width (ft)',type:'number',defaultValue:10},{key:'thickness',label:'Thickness (in)',type:'number',defaultValue:4}],\n    formula: (v) => { const cf=F(v.length)*F(v.width)*F(v.thickness)/12,cy=cf/27,bags=Math.ceil(cy*45); return [{label:'Cubic Yards',value:cy.toFixed(2)+' yd3'},{label:'80lb Bags',value:bags+' bags'},{label:'Cost $140/yd3',value:'$'+(cy*140).toFixed(0)}]; },\n    presets: [{label:'10x10 Patio',values:{length:10,width:10,thickness:4}}],\n  },"

F['paint-calculator'] = "  'paint-calculator': {\n    inputs: [{key:'length',label:'Room Length (ft)',type:'number',defaultValue:12},{key:'width',label:'Room Width (ft)',type:'number',defaultValue:12},{key:'height',label:'Ceiling (ft)',type:'number',defaultValue:8},{key:'coats',label:'Coats',type:'number',defaultValue:2}],\n    formula: (v) => { const walls=2*(F(v.length)+F(v.width))*F(v.height),ceil=F(v.length)*F(v.width),a=(walls+ceil)*F(v.coats),gal=Math.ceil(a/350); return [{label:'Area',value:a.toFixed(0)+' sqft'},{label:'Paint',value:gal+' gal'},{label:'Cost $35/gal',value:'$'+(gal*35).toFixed(0)}]; },\n  },"

F['flooring-calculator'] = "  'flooring-calculator': {\n    inputs: [{key:'length',label:'Room Length (ft)',type:'number',defaultValue:15},{key:'width',label:'Room Width (ft)',type:'number',defaultValue:12},{key:'waste',label:'Waste (%)',type:'number',defaultValue:10}],\n    formula: (v) => { const a=F(v.length)*F(v.width)*(1+F(v.waste)/100); return [{label:'Area',value:a.toFixed(0)+' sqft'},{label:'Hardwood Boxes',value:Math.ceil(a/20)+' boxes'},{label:'12x12 Tiles',value:Math.ceil(a)+' tiles'}]; },\n  },"

F['age-calculator'] = "  'age-calculator': {\n    inputs: [{key:'birth',label:'Birth Date (YYYY-MM-DD)',type:'text',defaultValue:'1990-05-15'}],\n    formula: (v) => { const b=new Date(String(v.birth)); if(isNaN(b.getTime()))return[{label:'Error',value:'Enter valid date'}]; const n=new Date(); var y=n.getFullYear()-b.getFullYear(); var md=n.getMonth()-b.getMonth(); if(md<0||(md===0&&n.getDate()<b.getDate()))y--; var d=Math.floor((n.getTime()-b.getTime())/86400000); return [{label:'Age',value:y+' years'},{label:'Days',value:d.toLocaleString()},{label:'Next Bday',value:Math.ceil((new Date(n.getFullYear()+(md>=0?1:0),b.getMonth(),b.getDate()).getTime()-n.getTime())/86400000)+' days'}]; },\n  },"

F['date-time-converter'] = "  'date-time-converter': {\n    inputs: [{key:'ts',label:'Unix Timestamp (sec)',type:'number',defaultValue:1716500000}],\n    formula: (v) => { const d=new Date(F(v.ts)*1000); return [{label:'ISO 8601',value:d.toISOString()},{label:'Local',value:d.toLocaleString()},{label:'UTC',value:d.toUTCString()}]; },\n  },"

F['time-zone-converter'] = "  'time-zone-converter': {\n    inputs: [{key:'time',label:'Time (HH:MM)',type:'text',defaultValue:'14:00'},{key:'from',label:'From UTC',type:'number',defaultValue:-5},{key:'to',label:'To UTC',type:'number',defaultValue:0}],\n    formula: (v) => { const p=String(v.time).split(':').map(Number); var h=p[0]+(F(v.to)-F(v.from)),m=p[1]||0; h=((h%24)+24)%24; return [{label:'Converted',value:String(Math.floor(h)).padStart(2,'0')+':'+String(m).padStart(2,'0')}]; },\n  },"

F['password-strength-analyser'] = "  'password-strength-analyser': {\n    inputs: [{key:'pw',label:'Password',type:'text',defaultValue:'MyP@ssw0rd2026!'}],\n    formula: (v) => { const p=String(v.pw); var cs=0; if(/[a-z]/.test(p))cs+=26; if(/[A-Z]/.test(p))cs+=26; if(/[0-9]/.test(p))cs+=10; if(/[^a-zA-Z0-9]/.test(p))cs+=32; const e=p.length*Math.log2(cs||1); const s=e<40?'Weak':e<60?'Fair':e<80?'Good':e<100?'Strong':'Very Strong'; return [{label:'Strength',value:s},{label:'Entropy',value:e.toFixed(0)+' bits'},{label:'Length',value:p.length+' chars'}]; },\n  },"

F['json-viewer'] = "  'json-viewer': {\n    inputs: [{key:'json',label:'JSON String',type:'text',defaultValue:'{\"name\":\"John\",\"age\":30}'}],\n    formula: (v) => { try{const o=JSON.parse(String(v.json)); return [{label:'Valid',value:'Yes'},{label:'Keys',value:String(Object.keys(o).length)},{label:'Size',value:String(v.json).length+' chars'}]; }catch(e){return [{label:'Valid',value:'No'},{label:'Error',value:e.message}];} },\n  },"

F['base64-string-converter'] = "  'base64-string-converter': {\n    inputs: [{key:'text',label:'Text',type:'text',defaultValue:'Hello World!'}],\n    formula: (v) => { const e=btoa(String(v.text)); return [{label:'Encoded',value:e},{label:'Original',value:''+v.text}]; },\n  },"

F['hash-text'] = "  'hash-text': {\n    inputs: [{key:'text',label:'Text',type:'text',defaultValue:'Hello World'}],\n    formula: (v) => { const t=String(v.text); var h=0; for(var i=0;i<t.length;i++)h=((h<<5)-h)+t.charCodeAt(i); return [{label:'Hash(hex)',value:Math.abs(h).toString(16).padStart(8,'0')},{label:'Length',value:t.length+' chars'}]; },\n  },"

F['url-encoder'] = "  'url-encoder': {\n    inputs: [{key:'text',label:'Text',type:'text',defaultValue:'Hello World & more'}],\n    formula: (v) => { const e=encodeURIComponent(String(v.text)); return [{label:'Encoded',value:e},{label:'Length',value:e.length+' chars'}]; },\n  },"

F['text-statistics'] = "  'text-statistics': {\n    inputs: [{key:'text',label:'Text',type:'text',defaultValue:'The quick brown fox jumps over the lazy dog.'}],\n    formula: (v) => { const t=String(v.text),w=t.trim()?t.trim().split(/\\s+/).length:0,c=t.length,ns=t.replace(/\\s/g,'').length,s=t.split(/[.!?]+/).filter(Boolean).length; return [{label:'Words',value:String(w)},{label:'Chars',value:String(c)},{label:'Chars no space',value:String(ns)},{label:'Sentences',value:String(s)},{label:'Read Time',value:Math.ceil(w/238)+' min'}]; },\n  },"

F['case-converter'] = "  'case-converter': {\n    inputs: [{key:'text',label:'Input Text',type:'text',defaultValue:'hello world example'}],\n    formula: (v) => { const t=String(v.text),w=t.split(/[\\s_-]+/).filter(Boolean); const cam=w.map(function(x,i){return i===0?x.toLowerCase():x.charAt(0).toUpperCase()+x.slice(1).toLowerCase()}).join(''); const pas=w.map(function(x){return x.charAt(0).toUpperCase()+x.slice(1).toLowerCase()}).join(''); const sn=w.map(function(x){return x.toLowerCase()}).join('_'); const kb=w.map(function(x){return x.toLowerCase()}).join('-'); return [{label:'camelCase',value:cam},{label:'PascalCase',value:pas},{label:'snake_case',value:sn},{label:'kebab-case',value:kb}]; },\n  },"

F['roman-numeral-converter'] = "  'roman-numeral-converter': {\n    inputs: [{key:'num',label:'Number (1-3999)',type:'number',defaultValue:2026}],\n    formula: (v) => { const n=F(v.num),vls=[1000,900,500,400,100,90,50,40,10,9,5,4,1],sym=['M','CM','D','CD','C','XC','L','XL','X','IX','V','IV','I']; var r='',rem=n; for(var i=0;i<vls.length;i++)while(rem>=vls[i]){r+=sym[i];rem-=vls[i];} return [{label:'Roman',value:r}]; },\n  },"

F['color-converter'] = "  'color-converter': {\n    inputs: [{key:'hex',label:'HEX Color (#RRGGBB)',type:'text',defaultValue:'#FF5733'}],\n    formula: (v) => { const h=String(v.hex).replace('#',''); if(!/^[0-9A-Fa-f]{6}$/.test(h))return[{label:'Error',value:'Invalid HEX'}]; const r=parseInt(h.slice(0,2),16),g=parseInt(h.slice(2,4),16),b=parseInt(h.slice(4,6),16); return [{label:'RGB',value:'rgb('+r+','+g+','+b+')'},{label:'HEX',value:'#'+h.toUpperCase()}]; },\n  },"

F['gpa-calculator'] = "  'gpa-calculator': {\n    inputs: [{key:'grades',label:'Grades (A,B+,C-)',type:'text',defaultValue:'A,B+,A-,B'},{key:'credits',label:'Credits (3,4,3,3)',type:'text',defaultValue:'3,4,3,3'}],\n    formula: (v) => { const gp={A:4,'A+':4,'A-':3.7,'B+':3.3,B:3,'B-':2.7,'C+':2.3,C:2,'C-':1.7,D:1,F:0}; const g=String(v.grades).split(',').map(function(s){return gp[s.trim()]||0}); const c=String(v.credits).split(',').map(Number); const pts=g.reduce(function(s,x,i){return s+x*(c[i]||0)},0),tot=c.reduce(function(s,x){return s+x},0); return [{label:'GPA',value:tot>0?(pts/tot).toFixed(2):'N/A'},{label:'Credits',value:String(tot)}]; },\n  },"

F['grade-calculator'] = "  'grade-calculator': {\n    inputs: [{key:'cur',label:'Current Grade (%)',type:'number',defaultValue:75},{key:'target',label:'Target Grade (%)',type:'number',defaultValue:80},{key:'fw',label:'Final Weight (%)',type:'number',defaultValue:40}],\n    formula: (v) => { const n=(F(v.target)-F(v.cur)*(1-F(v.fw)/100))/(F(v.fw)/100); return [{label:'Need on Final',value:n>100?'Impossible!':n<0?'Already there!':n.toFixed(1)+'%'}]; },\n  },"

F['probability-calculator'] = "  'probability-calculator': {\n    inputs: [{key:'fav',label:'Favorable',type:'number',defaultValue:1},{key:'tot',label:'Total',type:'number',defaultValue:6}],\n    formula: (v) => { const p=F(v.tot)>0?F(v.fav)/F(v.tot)*100:0; return [{label:'Probability',value:p.toFixed(2)+'%'},{label:'Odds',value:'1:'+Math.round((F(v.tot)-F(v.fav))/Math.max(1,F(v.fav)))}]; },\n  },"

F['car-loan-calculator'] = "  'car-loan-calculator': {\n    inputs: [{key:'price',label:'Car Price ($)',type:'number',defaultValue:35000},{key:'down',label:'Down (%)',type:'number',defaultValue:20},{key:'rate',label:'APR (%)',type:'number',defaultValue:6},{key:'term',label:'Term (months)',type:'number',defaultValue:60}],\n    formula: (v) => { const P=F(v.price)*(1-F(v.down)/100),r=F(v.rate)/100/12,n=F(v.term); const M=r>0?P*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):P/n; return [{label:'Monthly',value:'$'+M.toFixed(2)},{label:'Total Interest',value:'$'+(M*n-P).toFixed(0)}]; },\n  },"

F['roi-calculator'] = "  'roi-calculator': {\n    inputs: [{key:'invested',label:'Invested ($)',type:'number',defaultValue:10000},{key:'returned',label:'Returned ($)',type:'number',defaultValue:12000}],\n    formula: (v) => { const roi=F(v.invested)>0?(F(v.returned)-F(v.invested))/F(v.invested)*100:0; return [{label:'ROI',value:roi.toFixed(2)+'%'},{label:'Gain',value:'$'+(F(v.returned)-F(v.invested)).toFixed(2)}]; },\n  },"

F['emi-calculator'] = "  'emi-calculator': {\n    inputs: [{key:'loan',label:'Loan ($)',type:'number',defaultValue:20000},{key:'rate',label:'Rate (%)',type:'number',defaultValue:8},{key:'months',label:'Tenure (mo)',type:'number',defaultValue:36}],\n    formula: (v) => { const P=F(v.loan),r=F(v.rate)/100/12,n=F(v.months),emi=r>0?P*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):P/n; return [{label:'EMI',value:'$'+emi.toFixed(2)},{label:'Total',value:'$'+(emi*n).toFixed(0)},{label:'Interest',value:'$'+(emi*n-P).toFixed(0)}]; },\n  },"

F['inflation-calculator'] = "  'inflation-calculator': {\n    inputs: [{key:'amount',label:'Amount ($)',type:'number',defaultValue:10000},{key:'rate',label:'Inflation (%)',type:'number',defaultValue:3},{key:'years',label:'Years',type:'number',defaultValue:10}],\n    formula: (v) => { const f=F(v.amount)*Math.pow(1+F(v.rate)/100,F(v.years)),t=F(v.amount)/Math.pow(1+F(v.rate)/100,F(v.years)); return [{label:'Future Cost',value:'$'+f.toFixed(2)},{label:'Today Worth',value:'$'+t.toFixed(2)}]; },\n  },"

F['profit-margin-calculator'] = "  'profit-margin-calculator': {\n    inputs: [{key:'price',label:'Selling Price ($)',type:'number',defaultValue:100},{key:'cost',label:'COGS ($)',type:'number',defaultValue:60}],\n    formula: (v) => { const p=F(v.price)-F(v.cost),m=F(v.price)>0?p/F(v.price)*100:0,mu=F(v.cost)>0?p/F(v.cost)*100:0; return [{label:'Profit',value:'$'+p.toFixed(2)},{label:'Margin',value:m.toFixed(1)+'%'},{label:'Markup',value:mu.toFixed(1)+'%'}]; },\n  },"

F['net-worth-calculator'] = "  'net-worth-calculator': {\n    inputs: [{key:'cash',label:'Cash ($)',type:'number',defaultValue:10000},{key:'invest',label:'Investments ($)',type:'number',defaultValue:50000},{key:'property',label:'Property ($)',type:'number',defaultValue:300000},{key:'debt',label:'Debt ($)',type:'number',defaultValue:200000}],\n    formula: (v) => { const a=F(v.cash)+F(v.invest)+F(v.property),d=F(v.debt); return [{label:'Assets',value:'$'+a.toLocaleString()},{label:'Debt',value:'$'+d.toLocaleString()},{label:'Net Worth',value:'$'+(a-d).toLocaleString()}]; },\n  },"

F['home-equity-calculator'] = "  'home-equity-calculator': {\n    inputs: [{key:'val',label:'Home Value ($)',type:'number',defaultValue:350000},{key:'mtg',label:'Mortgage ($)',type:'number',defaultValue:200000}],\n    formula: (v) => { const e=F(v.val)-F(v.mtg),p=F(v.val)>0?e/F(v.val)*100:0; return [{label:'Equity',value:'$'+e.toLocaleString()},{label:'Equity %',value:p.toFixed(1)+'%'},{label:'LTV',value:(100-p).toFixed(1)+'%'}]; },\n  },"

F['stock-return-calculator'] = "  'stock-return-calculator': {\n    inputs: [{key:'buy',label:'Buy ($)',type:'number',defaultValue:100},{key:'sell',label:'Sell ($)',type:'number',defaultValue:130},{key:'shares',label:'Shares',type:'number',defaultValue:10}],\n    formula: (v) => { const p=(F(v.sell)-F(v.buy))*F(v.shares),pct=F(v.buy)>0?(F(v.sell)-F(v.buy))/F(v.buy)*100:0; return [{label:'P&L',value:'$'+p.toFixed(2)},{label:'Return',value:pct.toFixed(2)+'%'}]; },\n  },"

F['cooking-time-calculator'] = "  'cooking-time-calculator': {\n    inputs: [{key:'weight',label:'Weight (lbs)',type:'number',defaultValue:12},{key:'type',label:'Meat',type:'select',options:[{label:'Turkey',value:'turkey'},{label:'Chicken',value:'chicken'},{label:'Beef',value:'beef'},{label:'Pork',value:'pork'}],defaultValue:'turkey'}],\n    formula: (v) => { const r={turkey:15,chicken:20,beef:18,pork:25}; const m=F(v.weight)*r[String(v.type)]; return [{label:'Cook Time',value:Math.round(m)+' min ('+(m/60).toFixed(1)+' hrs)'},{label:'Rest Time',value:Math.round(m*0.15)+' min'},{label:'Internal',value:'165F poultry / 145F beef,pork'}]; },\n    presets: [{label:'12lb Turkey',values:{weight:12,type:'turkey'}}],\n  },"

F['bakers-percentage-calculator'] = "  'bakers-percentage-calculator': {\n    inputs: [{key:'flour',label:'Flour (g)',type:'number',defaultValue:500},{key:'water',label:'Water (g)',type:'number',defaultValue:350},{key:'salt',label:'Salt (g)',type:'number',defaultValue:10},{key:'yeast',label:'Yeast (g)',type:'number',defaultValue:5}],\n    formula: (v) => { const f=F(v.flour); return [{label:'Hydration',value:(F(v.water)/f*100).toFixed(0)+'%'},{label:'Salt',value:(F(v.salt)/f*100).toFixed(1)+'%'},{label:'Yeast',value:(F(v.yeast)/f*100).toFixed(1)+'%'},{label:'Total',value:(f+F(v.water)+F(v.salt)+F(v.yeast)).toFixed(0)+'g'}]; },\n  },"

F['coffee-ratio-calculator'] = "  'coffee-ratio-calculator': {\n    inputs: [{key:'coffee',label:'Coffee (g)',type:'number',defaultValue:20},{key:'ratio',label:'Water Ratio (1:X)',type:'number',defaultValue:16}],\n    formula: (v) => { const w=F(v.coffee)*F(v.ratio),cups=w/240; return [{label:'Water',value:w.toFixed(0)+' ml'},{label:'Cups',value:cups.toFixed(1)+' cups'},{label:'Strong(1:14)',value:(F(v.coffee)*14)+' ml'},{label:'Light(1:18)',value:(F(v.coffee)*18)+' ml'}]; },\n    presets: [{label:'Pour-Over',values:{coffee:20,ratio:16}}],\n  },"

F['ideal-weight-calculator'] = "  'ideal-weight-calculator': {\n    inputs: [{key:'height',label:'Height (cm)',type:'number',defaultValue:170},{key:'gender',label:'Gender',type:'select',options:[{label:'Male',value:'male'},{label:'Female',value:'female'}],defaultValue:'male'}],\n    formula: (v) => { const h=F(v.height); const r=v.gender==='male'?52+1.9*(h-152.4)/2.54:49+1.7*(h-152.4)/2.54; const m=v.gender==='male'?56.2+1.41*(h-152.4)/2.54:53.1+1.36*(h-152.4)/2.54; const lo=18.5*Math.pow(h/100,2),hi=24.9*Math.pow(h/100,2); return [{label:'BMI Range',value:lo.toFixed(0)+'-'+hi.toFixed(0)+' kg'},{label:'Robinson',value:r.toFixed(1)+' kg'},{label:'Miller',value:m.toFixed(1)+' kg'}]; },\n  },"

F['macro-calculator'] = "  'macro-calculator': {\n    inputs: [{key:'cal',label:'Daily Calories',type:'number',defaultValue:2000},{key:'pro',label:'Protein (%)',type:'number',defaultValue:30},{key:'fat',label:'Fat (%)',type:'number',defaultValue:25}],\n    formula: (v) => { const cal=F(v.cal),p=F(v.pro),f=F(v.fat),c=100-p-f; return [{label:'Protein',value:Math.round(cal*p/100/4)+'g'},{label:'Carbs',value:Math.round(cal*c/100/4)+'g'},{label:'Fat',value:Math.round(cal*f/100/9)+'g'}]; },\n    presets: [{label:'Balanced',values:{cal:2000,pro:30,fat:25}},{label:'Keto',values:{cal:2000,pro:25,fat:70}}],\n  },"

F['water-intake-calculator'] = "  'water-intake-calculator': {\n    inputs: [{key:'wt',label:'Weight (lbs)',type:'number',defaultValue:150},{key:'act',label:'Activity',type:'select',options:[{label:'Sedentary',value:'1'},{label:'Moderate',value:'1.2'},{label:'Active',value:'1.4'}],defaultValue:'1'}],\n    formula: (v) => { const b=F(v.wt)*0.67*F(v.act); return [{label:'Daily',value:b.toFixed(0)+' oz'},{label:'Liters',value:(b/33.8).toFixed(1)+' L'},{label:'Glasses',value:Math.round(b/8)+' glasses'}]; },\n  },"

F['heart-rate-zone-calculator'] = "  'heart-rate-zone-calculator': {\n    inputs: [{key:'age',label:'Age',type:'number',defaultValue:30},{key:'rest',label:'Resting HR',type:'number',defaultValue:65}],\n    formula: (v) => { const mx=208-0.7*F(v.age),hrr=mx-F(v.rest); return [{label:'Max HR',value:Math.round(mx)+' bpm'},{label:'Zone 2 FatBurn',value:Math.round(F(v.rest)+hrr*0.5)+'-'+Math.round(F(v.rest)+hrr*0.6)+' bpm'},{label:'Zone 4 Threshold',value:Math.round(F(v.rest)+hrr*0.7)+'-'+Math.round(F(v.rest)+hrr*0.8)+' bpm'},{label:'Zone 5 Max',value:Math.round(F(v.rest)+hrr*0.8)+'-'+Math.round(mx)+' bpm'}]; },\n  },"

F['dog-age-calculator'] = "  'dog-age-calculator': {\n    inputs: [{key:'age',label:'Dog Age (yrs)',type:'number',defaultValue:3},{key:'size',label:'Breed Size',type:'select',options:[{label:'Small (<9kg)',value:'small'},{label:'Medium',value:'medium'},{label:'Large (>23kg)',value:'large'}],defaultValue:'medium'}],\n    formula: (v) => { const a=F(v.age); var h=16*Math.log(a)+31; if(v.size==='large')h*=1.15; if(v.size==='small')h*=0.85; return [{label:'Human Age',value:Math.round(h)+' yrs'},{label:'Stage',value:a<1?'Puppy':a<2?'Adolescent':a<7?'Adult':a<10?'Senior':'Geriatric'}]; },\n  },"

F['cat-age-calculator'] = "  'cat-age-calculator': {\n    inputs: [{key:'age',label:'Cat Age (yrs)',type:'number',defaultValue:3}],\n    formula: (v) => { const a=F(v.age); var h=a<=1?15:a<=2?24:24+(a-2)*4; return [{label:'Human Age',value:Math.round(h)+' yrs'},{label:'Stage',value:a<0.5?'Kitten':a<2?'Junior':a<6?'Prime':a<10?'Mature':a<14?'Senior':'Geriatric'}]; },\n  },"

F['tdee-calculator'] = "  'tdee-calculator': {\n    inputs: [{key:'wt',label:'Weight (kg)',type:'number',defaultValue:70},{key:'ht',label:'Height (cm)',type:'number',defaultValue:175},{key:'age',label:'Age',type:'number',defaultValue:30},{key:'gen',label:'Gender',type:'select',options:[{label:'Male',value:'male'},{label:'Female',value:'female'}],defaultValue:'male'},{key:'act',label:'Activity',type:'select',options:[{label:'Sedentary',value:'1.2'},{label:'Light',value:'1.375'},{label:'Moderate',value:'1.55'},{label:'Active',value:'1.725'},{label:'Very Active',value:'1.9'}],defaultValue:'1.55'}],\n    formula: (v) => { const w=F(v.wt),h=F(v.ht),a=F(v.age),act=F(v.act); const bmr=v.gen==='male'?10*w+6.25*h-5*a+5:10*w+6.25*h-5*a-161; const tdee=bmr*act; return [{label:'BMR',value:bmr.toFixed(0)+' cal'},{label:'TDEE',value:tdee.toFixed(0)+' cal'},{label:'Lose(-500)',value:(tdee-500).toFixed(0)+' cal'},{label:'Gain(+500)',value:(tdee+500).toFixed(0)+' cal'}]; },\n    presets: [{label:'Moderate Male 30',values:{wt:70,ht:175,age:30,gen:'male',act:'1.55'}}],\n  },"

F['body-fat-calculator'] = "  'body-fat-calculator': {\n    inputs: [{key:'ht',label:'Height (cm)',type:'number',defaultValue:175},{key:'neck',label:'Neck (cm)',type:'number',defaultValue:38},{key:'waist',label:'Waist (cm)',type:'number',defaultValue:85},{key:'gen',label:'Gender',type:'select',options:[{label:'Male',value:'male'},{label:'Female',value:'female'}],defaultValue:'male'}],\n    formula: (v) => { const h=F(v.ht),n=F(v.neck),w=F(v.waist); var bf=v.gen==='male'?86.01*Math.log10(Math.max(1,w-n))-70.041*Math.log10(h)+36.76:163.205*Math.log10(Math.max(1,w+n-h))-97.684*Math.log10(h)-78.387; bf=Math.max(3,Math.abs(bf)); return [{label:'Body Fat',value:bf.toFixed(1)+'%'},{label:'Category',value:bf<6?'Essential':bf<14?'Athlete':bf<18?'Fitness':bf<25?'Average':'Above Avg'}]; },\n  },"

F['sheng-xiao-compatibility'] = "  'sheng-xiao-compatibility': {\n    inputs: [{key:'z1',label:'Your Sign',type:'select',options:[{label:'Rat',value:'rat'},{label:'Ox',value:'ox'},{label:'Tiger',value:'tiger'},{label:'Rabbit',value:'rabbit'},{label:'Dragon',value:'dragon'},{label:'Snake',value:'snake'},{label:'Horse',value:'horse'},{label:'Goat',value:'goat'},{label:'Monkey',value:'monkey'},{label:'Rooster',value:'rooster'},{label:'Dog',value:'dog'},{label:'Pig',value:'pig'}],defaultValue:'dragon'},{key:'z2',label:'Partner',type:'select',options:[{label:'Rat',value:'rat'},{label:'Ox',value:'ox'},{label:'Tiger',value:'tiger'},{label:'Rabbit',value:'rabbit'},{label:'Dragon',value:'dragon'},{label:'Snake',value:'snake'},{label:'Horse',value:'horse'},{label:'Goat',value:'goat'},{label:'Monkey',value:'monkey'},{label:'Rooster',value:'rooster'},{label:'Dog',value:'dog'},{label:'Pig',value:'pig'}],defaultValue:'monkey'}],\n    formula: (v) => { const h={rat:['dragon','monkey'],ox:['snake','rooster'],tiger:['horse','dog'],rabbit:['goat','pig'],dragon:['rat','monkey'],snake:['ox','rooster'],horse:['tiger','dog'],goat:['rabbit','pig'],monkey:['rat','dragon'],rooster:['ox','snake'],dog:['tiger','horse'],pig:['rabbit','goat']}; const c={rat:'horse',ox:'goat',tiger:'monkey',rabbit:'rooster',dragon:'dog',snake:'pig',horse:'rat',goat:'ox',monkey:'tiger',rooster:'rabbit',dog:'dragon',pig:'snake'}; var s=50; if(h[v.z1]&&h[v.z1].includes(v.z2))s+=35; if(c[v.z1]===v.z2)s-=30; if(v.z1===v.z2)s+=15; return [{label:'Match',value:s+'%'},{label:'Rating',value:s>=90?'Heaven-Matched':s>=70?'Great':s>=50?'OK':s>=30?'Challenging':'Clash'}]; },\n  },"

F['soulmate-finder'] = "  'soulmate-finder': {\n    inputs: [{key:'b1',label:'Your Bday',type:'text',defaultValue:'1990-05-15'},{key:'b2',label:'Partner Bday',type:'text',defaultValue:'1992-08-22'}],\n    formula: (v) => { const rd=function(n){while(n>9&&n!==11&&n!==22&&n!==33)n=String(n).split('').reduce(function(a,b){return a+Number(b)},0);return n;}; const d1=String(v.b1).replace(/-/g,''),d2=String(v.b2).replace(/-/g,''); if(d1.length<8||d2.length<8)return[{label:'Score',value:'Enter dates'}]; const lp1=rd(d1.split('').reduce(function(a,b){return a+Number(b)},0)),lp2=rd(d2.split('').reduce(function(a,b){return a+Number(b)},0)); const grps=[[1,5,7],[2,4,8],[3,6,9]]; const sg=grps.some(function(g){return g.includes(lp1)&&g.includes(lp2)}); const lps=lp1===lp2?95:sg?82:50; const m1=Number(d1.slice(4,6)),m2=Number(d2.slice(4,6)),sd=Math.abs(m1-m2),ss=sd<=1?90:sd<=2?78:45; const f=Math.min(99,Math.round(lps*0.5+ss*0.5)); return [{label:'Soulmate',value:f+'%'},{label:'Type',value:f>=90?'TwinFlames':f>=75?'DeepBond':f>=55?'Karmic':f>=35?'Growth':'Passing'},{label:'Your LP',value:String(lp1)},{label:'Partner LP',value:String(lp2)}]; },\n  },"

F['numerology-calculator'] = "  'numerology-calculator': {\n    inputs: [{key:'bday',label:'Birth Date',type:'text',defaultValue:'1990-05-15'}],\n    formula: (v) => { const rd=function(n){while(n>9&&n!==11&&n!==22&&n!==33)n=String(n).split('').reduce(function(a,b){return a+Number(b)},0);return n;}; const s=String(v.bday).replace(/-/g,''); if(s.length<8)return[{label:'LP',value:'Enter date'}]; const lp=rd(s.split('').reduce(function(a,b){return a+Number(b)},0)); const nm={1:'Leader',2:'Diplomat',3:'Creator',4:'Builder',5:'Adventurer',6:'Nurturer',7:'Thinker',8:'Achiever',9:'Humanitarian',11:'Master Intuitive',22:'Master Builder',33:'Master Teacher'}; return [{label:'Life Path',value:String(lp)+(lp>9?' (Master!)':'')},{label:'Archetype',value:nm[lp]||'Unknown'}]; },\n  },"

F['scientific-calculator'] = "  'scientific-calculator': {\n    inputs: [{key:'expr',label:'Expression',type:'text',defaultValue:'sqrt(16)+sin(PI/2)*2'}],\n    formula: (v) => { try{var x=String(v.expr).replace(/PI/gi,String(Math.PI)).replace(/sin/gi,'Math.sin').replace(/cos/gi,'Math.cos').replace(/tan/gi,'Math.tan').replace(/sqrt/gi,'Math.sqrt').replace(/abs/gi,'Math.abs'); var r=Function('\"use strict\";return ('+x+')')(); return[{label:'Result',value:Number(r).toFixed(6)}]; }catch(e){return[{label:'Error',value:'Invalid'}];} },\n  },"

F['car-depreciation-calculator'] = "  'car-depreciation-calculator': {\n    inputs: [{key:'price',label:'Purchase ($)',type:'number',defaultValue:35000},{key:'years',label:'Years',type:'number',defaultValue:5}],\n    formula: (v) => { var val=F(v.price); var r=[0.78,0.85,0.88,0.90,0.92]; for(var i=0;i<Math.min(F(v.years),5);i++)val*=r[i]; return [{label:'Value',value:'$'+val.toFixed(0)},{label:'Lost',value:'$'+(F(v.price)-val).toFixed(0)},{label:'Lost %',value:((1-val/F(v.price))*100).toFixed(0)+'%'}]; },\n  },"

F['electricity-bill-calculator'] = "  'electricity-bill-calculator': {\n    inputs: [{key:'kwh',label:'Monthly kWh',type:'number',defaultValue:900},{key:'rate',label:'Rate ($/kWh)',type:'number',defaultValue:0.17,step:0.01}],\n    formula: (v) => { const b=F(v.kwh)*F(v.rate); return [{label:'Monthly',value:'$'+b.toFixed(2)},{label:'Annual',value:'$'+(b*12).toFixed(0)}]; },\n  },"

# Apply
count = 0

# === FINAL BATCH ===
F['car-tax-calculator'] = "  'car-tax-calculator': {\n    inputs: [{key:'price',label:'Car Price ($)',type:'number',defaultValue:35000},{key:'trade',label:'Trade-In ($)',type:'number',defaultValue:10000},{key:'tax',label:'Tax Rate (%)',type:'number',defaultValue:7}],\n    formula: (v) => { const t=Math.max(0,F(v.price)-F(v.trade))*F(v.tax)/100; return [{label:'Taxable',value:'$'+Math.max(0,F(v.price)-F(v.trade)).toFixed(0)},{label:'Tax Due',value:'$'+t.toFixed(2)},{label:'Total OTD',value:'$'+(F(v.price)+t).toFixed(0)}]; },\n  },"

F['break-even-calculator'] = "  'break-even-calculator': {\n    inputs: [{key:'fc',label:'Fixed Costs ($)',type:'number',defaultValue:10000},{key:'p',label:'Price/Unit ($)',type:'number',defaultValue:50},{key:'vc',label:'Variable Cost ($)',type:'number',defaultValue:30}],\n    formula: (v) => { const cm=F(v.p)-F(v.vc),be=cm>0?Math.ceil(F(v.fc)/cm):0; return [{label:'Break-Even',value:be+' units'},{label:'Revenue',value:'$'+(be*F(v.p)).toFixed(0)},{label:'Margin/Unit',value:'$'+cm.toFixed(2)}]; },\n  },"

F['cpm-calculator'] = "  'cpm-calculator': {\n    inputs: [{key:'cost',label:'Ad Cost ($)',type:'number',defaultValue:500},{key:'imp',label:'Impressions',type:'number',defaultValue:100000}],\n    formula: (v) => { const c=F(v.imp)>0?F(v.cost)/F(v.imp)*1000:0; return [{label:'CPM',value:'$'+c.toFixed(2)},{label:'CPC 2%CTR',value:'$'+(c/20).toFixed(2)}]; },\n  },"

F['crypto-profit-calculator'] = "  'crypto-profit-calculator': {\n    inputs: [{key:'buy',label:'Buy Price ($)',type:'number',defaultValue:40000},{key:'sell',label:'Sell Price ($)',type:'number',defaultValue:50000},{key:'amt',label:'Amount',type:'number',defaultValue:0.1,step:0.01}],\n    formula: (v) => { const g=(F(v.sell)-F(v.buy))*F(v.amt),r=F(v.buy)>0?g/(F(v.buy)*F(v.amt))*100:0; return [{label:'P&L',value:'$'+g.toFixed(2)},{label:'ROI',value:r.toFixed(2)+'%'}]; },\n  },"

F['dividend-yield-calculator'] = "  'dividend-yield-calculator': {\n    inputs: [{key:'div',label:'Annual Div ($)',type:'number',defaultValue:2.50},{key:'price',label:'Stock Price ($)',type:'number',defaultValue:50}],\n    formula: (v) => { const y=F(v.price)>0?F(v.div)/F(v.price)*100:0; return [{label:'Yield',value:y.toFixed(2)+'%'},{label:'$/mo',value:'$'+(F(v.div)/12).toFixed(3)}]; },\n  },"

F['down-payment-calculator'] = "  'down-payment-calculator': {\n    inputs: [{key:'price',label:'Home Price ($)',type:'number',defaultValue:300000},{key:'pct',label:'Target (%)',type:'number',defaultValue:20},{key:'saved',label:'Saved ($)',type:'number',defaultValue:30000},{key:'mo',label:'Save/Mo ($)',type:'number',defaultValue:1000}],\n    formula: (v) => { const t=F(v.price)*F(v.pct)/100,n=Math.max(0,t-F(v.saved)),m=F(v.mo)>0?Math.ceil(n/F(v.mo)):999; return [{label:'Need',value:'$'+t.toFixed(0)},{label:'Left',value:'$'+n.toFixed(0)},{label:'Months',value:m>900?'N/A':String(m)}]; },\n  },"

F['early-payoff-calculator'] = "  'early-payoff-calculator': {\n    inputs: [{key:'bal',label:'Balance ($)',type:'number',defaultValue:200000},{key:'rate',label:'Rate (%)',type:'number',defaultValue:6},{key:'mo',label:'Months Left',type:'number',defaultValue:300},{key:'extra',label:'Extra ($/mo)',type:'number',defaultValue:200}],\n    formula: (v) => { const P=F(v.bal),r=F(v.rate)/100/12,n=F(v.mo),norm=P*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1); var b=P,m=0,pmt=norm+F(v.extra); while(b>0&&m<1500){b=b*(1+r)-pmt;m++;} return [{label:'Payoff',value:m+' mo'},{label:'Saved',value:'$'+Math.max(0,norm*n-pmt*m).toFixed(0)}]; },\n  },"

F['fire-calculator'] = "  'fire-calculator': {\n    inputs: [{key:'exp',label:'Annual Expenses ($)',type:'number',defaultValue:40000},{key:'saved',label:'Savings ($)',type:'number',defaultValue:100000},{key:'mo',label:'Save/Mo ($)',type:'number',defaultValue:3000},{key:'rate',label:'Return (%)',type:'number',defaultValue:7}],\n    formula: (v) => { const fi=F(v.exp)*25,r=F(v.rate)/100/12; var b=F(v.saved),y=0; while(b<fi&&y<80){for(var m=0;m<12;m++)b=b*(1+r)+F(v.mo);y++;} return [{label:'FI Number',value:'$'+fi.toLocaleString()},{label:'Years',value:String(y)},{label:'$/mo(4%)',value:'$'+(fi*0.04/12).toFixed(0)}]; },\n  },"

F['fob-cif-converter'] = "  'fob-cif-converter': {\n    inputs: [{key:'fob',label:'FOB ($)',type:'number',defaultValue:10000},{key:'freight',label:'Freight ($)',type:'number',defaultValue:2000},{key:'ins',label:'Insurance ($)',type:'number',defaultValue:100}],\n    formula: (v) => { const c=F(v.fob)+F(v.freight)+F(v.ins); return [{label:'CIF',value:'$'+c.toFixed(2)},{label:'Ins Rate',value:(F(v.ins)/c*100).toFixed(2)+'%'}]; },\n  },"

F['currency-hedge-calculator'] = "  'currency-hedge-calculator': {\n    inputs: [{key:'amt',label:'Amount',type:'number',defaultValue:100000},{key:'cur',label:'Current Rate',type:'number',defaultValue:1.10,step:0.01},{key:'fwd',label:'Forward Rate',type:'number',defaultValue:1.08,step:0.01}],\n    formula: (v) => { const h=F(v.amt)*F(v.fwd),u=F(v.amt)*F(v.cur); return [{label:'Hedged',value:'$'+h.toFixed(0)},{label:'Unhedged',value:'$'+u.toFixed(0)},{label:'Diff',value:'$'+(h-u).toFixed(0)}]; },\n  },"

F['import-duty-calculator'] = "  'import-duty-calculator': {\n    inputs: [{key:'cif',label:'CIF ($)',type:'number',defaultValue:10000},{key:'duty',label:'Duty (%)',type:'number',defaultValue:10},{key:'vat',label:'VAT (%)',type:'number',defaultValue:0}],\n    formula: (v) => { const d=F(v.cif)*F(v.duty)/100,b=F(v.cif)+d,vt=b*F(v.vat)/100; return [{label:'Duty',value:'$'+d.toFixed(2)},{label:'VAT',value:'$'+vt.toFixed(2)},{label:'Total',value:'$'+(F(v.cif)+d+vt).toFixed(2)}]; },\n  },"

F['invoice-hours-calculator'] = "  'invoice-hours-calculator': {\n    inputs: [{key:'hrs',label:'Hours',type:'number',defaultValue:40,step:0.5},{key:'rate',label:'Rate ($/hr)',type:'number',defaultValue:75}],\n    formula: (v) => { const s=F(v.hrs)*F(v.rate),t=s*0.15; return [{label:'Subtotal',value:'$'+s.toFixed(2)},{label:'Tax(15%)',value:'$'+t.toFixed(2)},{label:'Total',value:'$'+(s+t).toFixed(2)}]; },\n  },"

F['landed-cost-calculator'] = "  'landed-cost-calculator': {\n    inputs: [{key:'fob',label:'FOB ($)',type:'number',defaultValue:10000},{key:'freight',label:'Freight ($)',type:'number',defaultValue:2000},{key:'ins',label:'Insurance ($)',type:'number',defaultValue:100},{key:'duty',label:'Duty (%)',type:'number',defaultValue:10}],\n    formula: (v) => { const c=F(v.fob)+F(v.freight)+F(v.ins),d=c*F(v.duty)/100; return [{label:'CIF',value:'$'+c.toFixed(2)},{label:'Duty',value:'$'+d.toFixed(2)},{label:'Landed',value:'$'+(c+d).toFixed(2)}]; },\n  },"

F['lease-vs-buy-car-calculator'] = "  'lease-vs-buy-car-calculator': {\n    inputs: [{key:'price',label:'Car Price ($)',type:'number',defaultValue:35000},{key:'lease',label:'Lease ($/mo)',type:'number',defaultValue:450},{key:'loan',label:'Loan ($/mo)',type:'number',defaultValue:650},{key:'mo',label:'Months',type:'number',defaultValue:36}],\n    formula: (v) => { const l=F(v.lease)*F(v.mo),b=F(v.loan)*F(v.mo)-F(v.price)*0.5; return [{label:'Lease',value:'$'+l.toFixed(0)},{label:'Buy(equity)',value:'$'+b.toFixed(0)},{label:'Better',value:l<b?'Lease':'Buy'}]; },\n  },"

F['loan-comparison-calculator'] = "  'loan-comparison-calculator': {\n    inputs: [{key:'l1',label:'Loan 1 ($)',type:'number',defaultValue:200000},{key:'r1',label:'Rate 1 (%)',type:'number',defaultValue:6},{key:'t1',label:'Term 1 (yr)',type:'number',defaultValue:30},{key:'l2',label:'Loan 2 ($)',type:'number',defaultValue:200000},{key:'r2',label:'Rate 2 (%)',type:'number',defaultValue:5.5},{key:'t2',label:'Term 2 (yr)',type:'number',defaultValue:15}],\n    formula: (v) => { const c=function(P,rt,yr){var mr=rt/100/12,mn=yr*12,pmt=mr>0?P*mr*Math.pow(1+mr,mn)/(Math.pow(1+mr,mn)-1):P/mn;return{mo:pmt,tt:pmt*mn};};var a=c(F(v.l1),F(v.r1),F(v.t1)),b=c(F(v.l2),F(v.r2),F(v.t2));return[{label:'L1 Mo',value:'$'+a.mo.toFixed(2)},{label:'L1 Total',value:'$'+a.tt.toFixed(0)},{label:'L2 Mo',value:'$'+b.mo.toFixed(2)},{label:'L2 Total',value:'$'+b.tt.toFixed(0)}]; },\n  },"

F['mileage-calculator'] = "  'mileage-calculator': {\n    inputs: [{key:'miles',label:'Miles',type:'number',defaultValue:500},{key:'rate',label:'IRS Rate ($)',type:'number',defaultValue:0.70,step:0.01}],\n    formula: (v) => { const r=F(v.miles)*F(v.rate); return [{label:'Reimburse',value:'$'+r.toFixed(2)}]; },\n  },"

F['property-tax-calculator'] = "  'property-tax-calculator': {\n    inputs: [{key:'val',label:'Assessed ($)',type:'number',defaultValue:300000},{key:'rate',label:'Tax Rate (%)',type:'number',defaultValue:1.2,step:0.01}],\n    formula: (v) => { const a=F(v.val)*F(v.rate)/100; return [{label:'Annual',value:'$'+a.toFixed(2)},{label:'Monthly',value:'$'+(a/12).toFixed(2)}]; },\n  },"

F['renovation-cost-calculator'] = "  'renovation-cost-calculator': {\n    inputs: [{key:'kitchen',label:'Kitchen ($)',type:'number',defaultValue:25000},{key:'bath',label:'Bath ($)',type:'number',defaultValue:12000},{key:'floor',label:'Floor ($)',type:'number',defaultValue:5000},{key:'paint',label:'Paint ($)',type:'number',defaultValue:3000}],\n    formula: (v) => { const t=F(v.kitchen)+F(v.bath)+F(v.floor)+F(v.paint); return [{label:'Total',value:'$'+t.toLocaleString()},{label:'+15%',value:'$'+(t*1.15).toFixed(0)}]; },\n  },"

F['rent-vs-buy-calculator'] = "  'rent-vs-buy-calculator': {\n    inputs: [{key:'rent',label:'Rent ($/mo)',type:'number',defaultValue:1500},{key:'price',label:'Home Price ($)',type:'number',defaultValue:350000},{key:'rate',label:'Mortgage (%)',type:'number',defaultValue:6.5},{key:'yr',label:'Years',type:'number',defaultValue:7}],\n    formula: (v) => { const rt=F(v.rent)*12*F(v.yr),P=F(v.price)*0.8,r=F(v.rate)/100/12,n=30*12,M=r>0?P*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):P/n,bt=F(v.price)*0.2+M*12*F(v.yr); return [{label:'Rent',value:'$'+rt.toLocaleString()},{label:'Buy',value:'$'+bt.toLocaleString()},{label:'Better',value:rt<bt?'Rent':'Buy'}]; },\n  },"

F['solar-roi-calculator'] = "  'solar-roi-calculator': {\n    inputs: [{key:'cost',label:'System Cost ($)',type:'number',defaultValue:18000},{key:'saving',label:'Annual Savings ($)',type:'number',defaultValue:1800}],\n    formula: (v) => { const n=F(v.cost)*0.7,pb=F(v.saving)>0?n/F(v.saving):0; return [{label:'Net(30%)',value:'$'+n.toFixed(0)},{label:'Payback',value:pb.toFixed(1)+' yr'},{label:'25yrSave',value:'$'+(F(v.saving)*25-n).toFixed(0)}]; },\n  },"

F['tariff-impact-calculator'] = "  'tariff-impact-calculator': {\n    inputs: [{key:'fob',label:'FOB/Unit ($)',type:'number',defaultValue:100},{key:'old',label:'Old Tariff (%)',type:'number',defaultValue:10},{key:'new',label:'New Tariff (%)',type:'number',defaultValue:25},{key:'units',label:'Units',type:'number',defaultValue:1000}],\n    formula: (v) => { const o=F(v.fob)*F(v.old)/100*F(v.units),n=F(v.fob)*F(v.new)/100*F(v.units); return [{label:'Old Duty',value:'$'+o.toFixed(0)},{label:'New Duty',value:'$'+n.toFixed(0)},{label:'Increase',value:'$'+(n-o).toFixed(0)}]; },\n  },"

F['travel-budget-calculator'] = "  'travel-budget-calculator': {\n    inputs: [{key:'days',label:'Days',type:'number',defaultValue:7},{key:'flight',label:'Flight ($)',type:'number',defaultValue:400},{key:'hotel',label:'Hotel/Nt ($)',type:'number',defaultValue:150},{key:'food',label:'Food/Day ($)',type:'number',defaultValue:50}],\n    formula: (v) => { const t=F(v.flight)+F(v.hotel)*F(v.days)+F(v.food)*F(v.days); return [{label:'Total',value:'$'+t.toFixed(0)},{label:'Per Day',value:'$'+(t/F(v.days)).toFixed(0)}]; },\n  },"

F['carbon-footprint-calculator'] = "  'carbon-footprint-calculator': {\n    inputs: [{key:'miles',label:'Annual Miles',type:'number',defaultValue:12000},{key:'flights',label:'Flights/Yr',type:'number',defaultValue:2},{key:'kwh',label:'Monthly kWh',type:'number',defaultValue:500},{key:'meat',label:'Meat meals/wk',type:'number',defaultValue:5}],\n    formula: (v) => { const co2=F(v.miles)*0.0004+F(v.flights)*0.25+F(v.kwh)*12*0.00092+F(v.meat)*52*0.007; return [{label:'CO2',value:co2.toFixed(1)+' tons'},{label:'US Avg',value:'16 tons'},{label:'Target',value:'2 tons'}]; },\n  },"

F['water-footprint-calculator'] = "  'water-footprint-calculator': {\n    inputs: [{key:'shower',label:'Showers/Wk',type:'number',defaultValue:7},{key:'meat',label:'Meat meals/Wk',type:'number',defaultValue:5},{key:'laundry',label:'Laundry/Wk',type:'number',defaultValue:3}],\n    formula: (v) => { const d=F(v.shower)*17+F(v.laundry)*40,v=F(v.meat)*660*4; return [{label:'Direct',value:d.toFixed(0)+' gal'},{label:'Virtual(food)',value:v.toFixed(0)+' gal'},{label:'Total/Wk',value:(d+v).toFixed(0)+' gal'}]; },\n  },"

F['party-drink-calculator'] = "  'party-drink-calculator': {\n    inputs: [{key:'guests',label:'Guests',type:'number',defaultValue:30},{key:'hours',label:'Hours',type:'number',defaultValue:4}],\n    formula: (v) => { const d=F(v.guests)*(2+F(v.hours)-1),beer=Math.ceil(d*0.6),wine=Math.ceil(d*0.3/5),liq=Math.ceil(d*0.1/16); return [{label:'Beer',value:beer+' bot('+Math.ceil(beer/24)+' cases)'},{label:'Wine',value:wine+' bottles'},{label:'Liquor',value:liq+' bottles'}]; },\n  },"

F['wedding-budget-calculator'] = "  'wedding-budget-calculator': {\n    inputs: [{key:'budget',label:'Budget ($)',type:'number',defaultValue:30000},{key:'guests',label:'Guests',type:'number',defaultValue:100}],\n    formula: (v) => { const b=F(v.budget); return [{label:'Venue(32%)',value:'$'+(b*0.32).toFixed(0)},{label:'Catering(28%)',value:'$'+(b*0.28).toFixed(0)},{label:'Photo(10%)',value:'$'+(b*0.10).toFixed(0)},{label:'Per Guest',value:'$'+((b*0.6)/F(v.guests)).toFixed(0)}]; },\n  },"

F['wedding-countdown-calculator'] = "  'wedding-countdown-calculator': {\n    inputs: [{key:'date',label:'Wedding Date',type:'text',defaultValue:'2027-06-15'}],\n    formula: (v) => { const d=new Date(String(v.date)); if(isNaN(d.getTime()))return[{label:'Error',value:'Invalid date'}]; const diff=d.getTime()-Date.now(),days=Math.ceil(diff/86400000); return [{label:'Days',value:Math.max(0,days)+' days'},{label:'Weeks',value:(days/7).toFixed(1)+' wks'},{label:'Months',value:(days/30.44).toFixed(1)+' mos'}]; },\n  },"

F['seating-chart-calculator'] = "  'seating-chart-calculator': {\n    inputs: [{key:'guests',label:'Guests',type:'number',defaultValue:80},{key:'per',label:'Per Table',type:'number',defaultValue:8}],\n    formula: (v) => { const t=Math.ceil(F(v.guests)/F(v.per)); return [{label:'Tables',value:String(t)},{label:'60in(8)',value:Math.ceil(F(v.guests)/8)+' tables'},{label:'72in(10)',value:Math.ceil(F(v.guests)/10)+' tables'}]; },\n  },"

F['elo-rating-calculator'] = "  'elo-rating-calculator': {\n    inputs: [{key:'ra',label:'Player A Rating',type:'number',defaultValue:1600},{key:'rb',label:'Player B Rating',type:'number',defaultValue:1400},{key:'res',label:'Result',type:'select',options:[{label:'A Wins',value:'a'},{label:'B Wins',value:'b'},{label:'Draw',value:'draw'}],defaultValue:'a'}],\n    formula: (v) => { const ra=F(v.ra),rb=F(v.rb),ea=1/(1+Math.pow(10,(rb-ra)/400)),K=32,sa=v.res==='a'?1:v.res==='draw'?0.5:0; return [{label:'A Expected',value:(ea*100).toFixed(1)+'%'},{label:'A New',value:String(Math.round(ra+K*(sa-ea)))},{label:'B New',value:String(Math.round(rb+K*((1-sa)-(1-ea))))}]; },\n  },"

F['poker-odds-calculator'] = "  'poker-odds-calculator': {\n    inputs: [{key:'outs',label:'Outs',type:'number',defaultValue:9},{key:'street',label:'Street',type:'select',options:[{label:'Flop(2 cards)',value:'flop'},{label:'Turn(1 card)',value:'turn'}],defaultValue:'flop'}],\n    formula: (v) => { const o=F(v.outs),pct=v.street==='flop'?Math.min(99,o*4-(o>8?1:0)):Math.min(99,o*2); return [{label:'Win %',value:pct.toFixed(0)+'%'},{label:'Odds',value:'1:'+Math.round((100-pct)/pct)}]; },\n  },"

F['dice-probability-calculator'] = "  'dice-probability-calculator': {\n    inputs: [{key:'dice',label:'Dice',type:'number',defaultValue:2},{key:'sides',label:'Sides',type:'number',defaultValue:6}],\n    formula: (v) => { const d=F(v.dice),s=F(v.sides),mn=d,mx=d*s,avg=d*(s+1)/2; return [{label:'Range',value:mn+'-'+mx},{label:'Average',value:avg.toFixed(1)},{label:'Outcomes',value:Math.pow(s,d).toLocaleString()}]; },\n  },"

F['fps-bottleneck-calculator'] = "  'fps-bottleneck-calculator': {\n    inputs: [{key:'cpu',label:'CPU Score',type:'number',defaultValue:15000},{key:'gpu',label:'GPU Score',type:'number',defaultValue:18000},{key:'res',label:'Resolution',type:'select',options:[{label:'1080p','1080'},{label:'1440p','1440'},{label:'4K','4k'}],defaultValue:'1440'}],\n    formula: (v) => { const m=v.res==='1080'?1.3:v.res==='1440'?1:0.7,cf=F(v.cpu)/100*m,gf=F(v.gpu)/100*m,bt=Math.round((1-Math.min(cf,gf)/Math.max(cf,gf))*100); return [{label:'CPU FPS',value:cf.toFixed(0)},{label:'GPU FPS',value:gf.toFixed(0)},{label:'Bottleneck',value:bt+'%'},{label:'Limit',value:cf<gf?'CPU':'GPU'}]; },\n  },"

F['golden-ratio-calculator'] = "  'golden-ratio-calculator': {\n    inputs: [{key:'val',label:'Value',type:'number',defaultValue:100}],\n    formula: (v) => { const phi=1.6180339887,a=F(v.val); return [{label:'Longer(x phi)',value:(a*phi).toFixed(2)},{label:'Shorter(/ phi)',value:(a/phi).toFixed(2)}]; },\n  },"

F['pet-calorie-calculator'] = "  'pet-calorie-calculator': {\n    inputs: [{key:'wt',label:'Weight (kg)',type:'number',defaultValue:10},{key:'type',label:'Pet',type:'select',options:[{label:'Dog',value:'dog'},{label:'Cat',value:'cat'}],defaultValue:'dog'}],\n    formula: (v) => { const rer=70*Math.pow(F(v.wt),0.75),der=v.type==='dog'?rer*1.6:rer*1.2; return [{label:'RER',value:rer.toFixed(0)+' kcal'},{label:'Daily',value:der.toFixed(0)+' kcal'},{label:'Diet',value:(der*0.8).toFixed(0)+' kcal'}]; },\n  },"

F['pet-breed-mix-calculator'] = "  'pet-breed-mix-calculator': {\n    inputs: [{key:'size',label:'Size',type:'select',options:[{label:'Small','small'},{label:'Medium','medium'},{label:'Large','large'}],defaultValue:'medium'},{key:'coat',label:'Coat',type:'select',options:[{label:'Short','short'},{label:'Long','long'},{label:'Curly','curly'}],defaultValue:'short'}],\n    formula: (v) => { const r={medium:{short:'Lab/Beagle/Boxer mix',long:'Collie/Aussie mix',curly:'Poodle/Doodle mix'},small:{short:'Chihuahua/JRT mix',long:'Pom/Shih Tzu',curly:'Toy Poodle/Bichon'},large:{short:'GSD/Great Dane',long:'Golden/Husky',curly:'Standard Poodle'}}; return [{label:'Possible',value:(r[v.size]||{})[v.coat]||'Mixed breed'},{label:'Note',value:'DNA test for accuracy'}]; },\n  },"

F['recipe-converter'] = "  'recipe-converter': {\n    inputs: [{key:'orig',label:'Original Servings',type:'number',defaultValue:4},{key:'want',label:'Desired Servings',type:'number',defaultValue:8}],\n    formula: (v) => { const r=F(v.want)/F(v.orig); return [{label:'Scale',value:r.toFixed(2)+'x'},{label:'1 cup ->',value:(1*r).toFixed(2)+' cups'},{label:'2 tbsp ->',value:(2*r).toFixed(1)+' tbsp'}]; },\n  },"

F['food-calorie-calculator'] = "  'food-calorie-calculator': {\n    inputs: [{key:'grams',label:'Serving (g)',type:'number',defaultValue:200},{key:'cal100',label:'Cal/100g',type:'number',defaultValue:165},{key:'servings',label:'Servings',type:'number',defaultValue:1}],\n    formula: (v) => { const cal=F(v.grams)*F(v.cal100)/100*F(v.servings); return [{label:'Calories',value:cal.toFixed(0)+' kcal'},{label:'Protein est',value:(cal*0.3/4).toFixed(0)+'g'},{label:'Carbs est',value:(cal*0.45/4).toFixed(0)+'g'},{label:'Fat est',value:(cal*0.25/9).toFixed(0)+'g'}]; },\n  },"

F['ingredient-substitution-calculator'] = "  'ingredient-substitution-calculator': {\n    inputs: [{key:'ing',label:'Need to Replace',type:'text',defaultValue:'egg'},{key:'amt',label:'Amount',type:'number',defaultValue:1,step:0.25}],\n    formula: (v) => { const s={egg:'1/4 cup applesauce OR 1 tbsp flax+2.5 tbsp water',buttermilk:'1 cup milk+1 tbsp lemon juice',butter:'1 cup margarine OR 7/8 cup oil',sugar:'3/4 cup honey',flour:'1 cup AP+1.5 tsp baking powder+1/4 tsp salt'}; const i=String(v.ing).toLowerCase(); const m=Object.entries(s).find(function(e){return i.includes(e[0])}); return [{label:'Substitute',value:m?m[1]:'Try applesauce for general substitution'}]; },\n  },"

F['fuel-economy-calculator'] = "  'fuel-economy-calculator': {\n    inputs: [{key:'miles',label:'Miles',type:'number',defaultValue:300},{key:'gal',label:'Gallons',type:'number',defaultValue:12}],\n    formula: (v) => { const m=F(v.gal)>0?F(v.miles)/F(v.gal):0,l=m>0?235.215/m:0; return [{label:'MPG',value:m.toFixed(1)},{label:'L/100km',value:l.toFixed(1)}]; },\n  },"

F['tire-size-calculator'] = "  'tire-size-calculator': {\n    inputs: [{key:'width',label:'Width (mm)',type:'number',defaultValue:225},{key:'aspect',label:'Aspect',type:'number',defaultValue:65},{key:'rim',label:'Rim (in)',type:'number',defaultValue:17}],\n    formula: (v) => { const sw=F(v.width)*F(v.aspect)/100,dia=(sw*2+F(v.rim)*25.4)/25.4,circ=dia*Math.PI; return [{label:'Diameter',value:dia.toFixed(1)+' in'},{label:'Sidewall',value:sw.toFixed(0)+' mm'},{label:'Rev/mi',value:Math.round(63360/circ)}]; },\n  },"

F['countdown-timer'] = "  'countdown-timer': {\n    inputs: [{key:'date',label:'Target Date',type:'text',defaultValue:'2027-01-01'}],\n    formula: (v) => { const d=new Date(String(v.date)); if(isNaN(d.getTime()))return[{label:'Error',value:'Invalid date'}]; const diff=d.getTime()-Date.now(),days=Math.floor(diff/86400000),hrs=Math.floor((diff%86400000)/3600000),min=Math.floor((diff%3600000)/60000); return [{label:'Days',value:Math.max(0,days)+' days'},{label:'Hours',value:Math.max(0,hrs)+' hrs'},{label:'Minutes',value:Math.max(0,min)+' min'}]; },\n  },"

F['bsa-calculator'] = "  'bsa-calculator': {\n    inputs: [{key:'ht',label:'Height (cm)',type:'number',defaultValue:175},{key:'wt',label:'Weight (kg)',type:'number',defaultValue:70}],\n    formula: (v) => { const b=Math.sqrt(F(v.ht)*F(v.wt)/3600); return [{label:'BSA',value:b.toFixed(3)+' m2'}]; },\n  },"

F['baby-growth-calculator'] = "  'baby-growth-calculator': {\n    inputs: [{key:'mo',label:'Age (months)',type:'number',defaultValue:6},{key:'wt',label:'Weight (kg)',type:'number',defaultValue:7.5},{key:'gen',label:'Gender',type:'select',options:[{label:'Boy',value:'boy'},{label:'Girl',value:'girl'}],defaultValue:'boy'}],\n    formula: (v) => { const m=F(v.mo),w=F(v.wt); const med=v.gen==='boy'?[3.3,4.5,5.6,6.4,7.0,7.5,7.9,8.3,8.6,8.9,9.2,9.4]:[3.2,4.2,5.1,5.8,6.4,6.9,7.3,7.6,7.9,8.2,8.5,8.7]; const i=Math.min(11,Math.floor(m)); const pct=med[i]>0?Math.round(w/med[i]*50):50; return [{label:'Weight',value:w+' kg'},{label:'Median',value:med[i].toFixed(1)+' kg'},{label:'~Pctl',value:pct+'th'}]; },\n  },"

F['child-cost-calculator'] = "  'child-cost-calculator': {\n    inputs: [{key:'care',label:'Childcare ($/mo)',type:'number',defaultValue:1200},{key:'food',label:'Food ($/mo)',type:'number',defaultValue:300},{key:'other',label:'Other ($/mo)',type:'number',defaultValue:200}],\n    formula: (v) => { const m=F(v.care)+F(v.food)+F(v.other); return [{label:'Monthly',value:'$'+m.toFixed(0)},{label:'Annual',value:'$'+(m*12).toFixed(0)},{label:'0-18yr',value:'$'+(m*12*18).toFixed(0)}]; },\n  },"

F['due-date-calculator'] = "  'due-date-calculator': {\n    inputs: [{key:'lmp',label:'Last Period (YYYY-MM-DD)',type:'text',defaultValue:'2026-06-01'}],\n    formula: (v) => { const l=new Date(String(v.lmp)); if(isNaN(l.getTime()))return[{label:'Error',value:'Invalid date'}]; const d=new Date(l);d.setDate(d.getDate()+280);const n=new Date();const days=Math.ceil((d.getTime()-n.getTime())/86400000);return[{label:'Due Date',value:d.toISOString().slice(0,10)},{label:'Days Left',value:Math.max(0,days)+' days'}]; },\n  },"

F['ovulation-calculator'] = "  'ovulation-calculator': {\n    inputs: [{key:'lmp',label:'Last Period',type:'text',defaultValue:'2026-06-01'},{key:'cycle',label:'Cycle (days)',type:'number',defaultValue:28}],\n    formula: (v) => { const l=new Date(String(v.lmp)); if(isNaN(l.getTime()))return[{label:'Error',value:'Invalid date'}]; const o=new Date(l);o.setDate(o.getDate()+F(v.cycle)-14);const f=new Date(o);f.setDate(f.getDate()-5);return[{label:'Ovulation',value:o.toISOString().slice(0,10)},{label:'Fertile From',value:f.toISOString().slice(0,10)}]; },\n  },"

F['sleep-cycle-calculator'] = "  'sleep-cycle-calculator': {\n    inputs: [{key:'wake',label:'Wake Hour (0-23)',type:'number',defaultValue:7}],\n    formula: (v) => { const w=F(v.wake),t=[]; for(var i=6;i>=3;i--){var h=(w-(i*1.5)-0.25+24)%24,hr=Math.floor(h),mn=Math.round((h-hr)*60);t.push(String(hr).padStart(2,'0')+':'+String(mn).padStart(2,'0')+' ('+i+' cycles)');} return [{label:'Ideal(6c)',value:t[0]},{label:'Good(5c)',value:t[1]},{label:'OK(4c)',value:t[2]}]; },\n  },"

F['statistics-calculator'] = "  'statistics-calculator': {\n    inputs: [{key:'data',label:'Data (comma-sep)',type:'text',defaultValue:'1,2,3,4,5,6,7,8,9,10'}],\n    formula: (v) => { const n=String(v.data).split(',').map(Number).filter(function(x){return !isNaN(x)}); if(!n.length)return[{label:'Error',value:'No data'}]; const m=n.reduce(function(a,b){return a+b},0)/n.length; const s=[].concat(n).sort(function(a,b){return a-b}); const med=s.length%2?s[Math.floor(s.length/2)]:(s[s.length/2-1]+s[s.length/2])/2; const vr=n.reduce(function(a,x){return a+Math.pow(x-m,2)},0)/n.length; return [{label:'Mean',value:m.toFixed(2)},{label:'Median',value:med.toFixed(2)},{label:'Std Dev',value:Math.sqrt(vr).toFixed(2)},{label:'Min',value:String(s[0])},{label:'Max',value:String(s[s.length-1])}]; },\n  },"

F['math-evaluator'] = "  'math-evaluator': {\n    inputs: [{key:'expr',label:'Expression',type:'text',defaultValue:'2+2*3'}],\n    formula: (v) => { try{var r=Function('\"use strict\";return ('+String(v.expr)+')')(); return[{label:'Result',value:String(r)}]; }catch(e){return[{label:'Error',value:'Invalid'}];} },\n  },"

F['graphing-calculator'] = "  'graphing-calculator': {\n    inputs: [{key:'eq',label:'y = f(x)',type:'text',defaultValue:'x*x'}],\n    formula: (v) => { var pts=[]; try{var eq=String(v.eq).replace(/\\^/g,'**'); for(var x=-5;x<=5;x+=0.5){try{var y=Function('x','return '+eq)(x); if(!isNaN(y)&&isFinite(y))pts.push({x:x.toFixed(1),y:y.toFixed(2)});}catch(e){}} return[{label:'Points',value:pts.length+' plotted'},{label:'Range',value:'x:-5 to 5'}]; }catch(e){return[{label:'Error',value:'Invalid equation'}];} },\n  },"

F['steps-to-miles-calculator'] = "  'steps-to-miles-calculator': {\n    inputs: [{key:'steps',label:'Steps',type:'number',defaultValue:10000},{key:'stride',label:'Stride (in)',type:'number',defaultValue:30}],\n    formula: (v) => { const m=F(v.steps)*F(v.stride)/63360,km=m*1.609; return [{label:'Distance',value:m.toFixed(2)+' mi'},{label:'Km',value:km.toFixed(2)+' km'},{label:'Cal(150lb)',value:Math.round(m*80)+' kcal'}]; },\n  },"

F['annuity-calculator'] = "  'annuity-calculator': {\n    inputs: [{key:'pmt',label:'Payment ($)',type:'number',defaultValue:1000},{key:'rate',label:'Rate (%)',type:'number',defaultValue:6},{key:'n',label:'Periods (yr)',type:'number',defaultValue:20}],\n    formula: (v) => { const pmt=F(v.pmt),r=F(v.rate)/100,n=F(v.n); const fv=r>0?pmt*((Math.pow(1+r,n)-1)/r):pmt*n; return [{label:'Future Value',value:'$'+fv.toFixed(2)},{label:'Invested',value:'$'+(pmt*n).toFixed(0)},{label:'Interest',value:'$'+(fv-pmt*n).toFixed(0)}]; },\n  },"

F['roofing-calculator'] = "  'roofing-calculator': {\n    inputs: [{key:'foot',label:'Footprint (sqft)',type:'number',defaultValue:2000},{key:'pitch',label:'Pitch Factor',type:'number',defaultValue:1.12,step:0.01}],\n    formula: (v) => { const a=F(v.foot)*F(v.pitch),sq=Math.ceil(a/100); return [{label:'Area',value:a.toFixed(0)+' sqft'},{label:'Squares',value:sq+' sq'},{label:'Bundles',value:sq*3+' bdl'},{label:'Cost',value:'$'+(sq*350).toFixed(0)}]; },\n  },"

F['lumber-calculator'] = "  'lumber-calculator': {\n    inputs: [{key:'len',label:'Wall Length (ft)',type:'number',defaultValue:24},{key:'spacing',label:'Stud Spacing',type:'select',options:[{label:'16in OC',value:'16'},{label:'24in OC',value:'24'}],defaultValue:'16'}],\n    formula: (v) => { const s=Math.ceil(F(v.len)/(F(v.spacing)/12))+1,p=3,bf=s*8*1.5*3.5/12+p*F(v.len)*1.5*3.5/12; return [{label:'Studs',value:s+' studs'},{label:'Plates',value:p+' plates'},{label:'BF',value:bf.toFixed(0)+' BF'}]; },\n  },"

F['concrete-block-calculator'] = "  'concrete-block-calculator': {\n    inputs: [{key:'len',label:'Wall Length (ft)',type:'number',defaultValue:20},{key:'ht',label:'Wall Height (ft)',type:'number',defaultValue:8}],\n    formula: (v) => { const a=F(v.len)*F(v.ht),b=Math.ceil(a*1.125),m=Math.ceil(b/33); return [{label:'Area',value:a.toFixed(0)+' sqft'},{label:'Blocks',value:b+' blocks'},{label:'Mortar',value:m+' bags'}]; },\n  },"

F['hvac-btu-calculator'] = "  'hvac-btu-calculator': {\n    inputs: [{key:'sqft',label:'Area (sqft)',type:'number',defaultValue:1500},{key:'climate',label:'Climate',type:'select',options:[{label:'Mild','25'},{label:'Moderate','30'},{label:'Hot','35'}],defaultValue:'30'}],\n    formula: (v) => { const b=F(v.sqft)*F(v.climate),t=b/12000; return [{label:'Cooling',value:b.toFixed(0)+' BTU'},{label:'AC Tons',value:t.toFixed(1)+' tons'},{label:'Heat',value:(b*1.3).toFixed(0)+' BTU'}]; },\n  },"

F['beam-load-calculator'] = "  'beam-load-calculator': {\n    inputs: [{key:'span',label:'Span (ft)',type:'number',defaultValue:12},{key:'load',label:'Load (lbs/ft)',type:'number',defaultValue:40},{key:'mat',label:'Material',type:'select',options:[{label:'Wood SPF','1000'},{label:'LVL','2800'},{label:'Steel','24000'}],defaultValue:'1000'}],\n    formula: (v) => { const M=F(v.load)*F(v.span)*F(v.span)/8,S=M*12/F(v.mat); return [{label:'Moment',value:M.toFixed(0)+' ft-lb'},{label:'S req',value:S.toFixed(2)+' in3'},{label:'2x10 OK?',value:S<=21.4?'Yes':'No'}]; },\n  },"

F['wire-size-calculator'] = "  'wire-size-calculator': {\n    inputs: [{key:'amps',label:'Amps',type:'number',defaultValue:20},{key:'dist',label:'Distance (ft)',type:'number',defaultValue:50},{key:'volt',label:'Voltage',type:'select',options:[{label:'120V','120'},{label:'240V','240'}],defaultValue:'120'}],\n    formula: (v) => { const a=F(v.amps),d=F(v.dist),v=F(v.volt); const g=a<=15?'14':a<=20?'12':a<=30?'10':a<=40?'8':a<=55?'6':'4'; const area=a<=20?6530:a<=30?10380:16510; const vd=2*12.9*a*d/area/v*100; return [{label:'Wire',value:g+' AWG'},{label:'V Drop',value:vd.toFixed(2)+'%'},{label:'OK?',value:vd<3?'Yes':'Upsize'}]; },\n  },"

F['ohms-law-calculator'] = "  'ohms-law-calculator': {\n    inputs: [{key:'v',label:'Voltage (V)',type:'number',defaultValue:12},{key:'r',label:'Resistance (ohm)',type:'number',defaultValue:100}],\n    formula: (v) => { const V=F(v.v),R=F(v.r),I=R>0?V/R:0; return [{label:'Current',value:I.toFixed(2)+' A'},{label:'Power',value:(V*I).toFixed(1)+' W'}]; },\n  },"

F['led-resistor-calculator'] = "  'led-resistor-calculator': {\n    inputs: [{key:'vs',label:'Supply V',type:'number',defaultValue:5},{key:'vf',label:'LED Vf',type:'number',defaultValue:2.0,step:0.1},{key:'i',label:'Current (mA)',type:'number',defaultValue:20}],\n    formula: (v) => { const R=Math.max(1,(F(v.vs)-F(v.vf))/(F(v.i)/1000)),P=F(v.i)/1000*F(v.i)/1000*R; return [{label:'Resistor',value:R.toFixed(0)+' ohm'},{label:'Power',value:P.toFixed(3)+' W'},{label:'Use',value:Math.ceil(P*2)+'W min'}]; },\n  },"

F['resistor-color-code-calculator'] = "  'resistor-color-code-calculator': {\n    inputs: [{key:'ohms',label:'Resistance (ohm)',type:'number',defaultValue:4700}],\n    formula: (v) => { const r=F(v.ohms),c=['Black','Brown','Red','Orange','Yellow','Green','Blue','Violet','Grey','White']; const d=r<10?[0,r]:r<100?[Math.floor(r/10),r%10]:[Math.floor(r/100),Math.floor(r/10)%10]; return [{label:'Band 1',value:c[d[0]]},{label:'Band 2',value:c[d[1]]},{label:'Multiplier',value:r>=1000?'Red x100':r>=100?'Brown x10':'Black x1'}]; },\n  },"

for tid, replacement in F.items():
    start = content.find("'"+tid+"': {")
    if start < 0: continue
    depth = 0
    end = start
    for i in range(start, len(content)):
        if content[i] == '{': depth += 1
        if content[i] == '}': depth -= 1
        if depth == 0 and content[i] == '}':
            end = i + 1
            if end < len(content) and content[end] == ',': end += 1
            break
    content = content[:start] + replacement + content[end:]
    count += 1

with open("src/app/data/formulas.ts", "w", encoding="utf-8") as f:
    f.write(content)

print(f"Fixed {count} tools")
print(f"input1 remain: {content.count(chr(34)+'input1'+chr(34))}")
